// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tflite_micro runtime version 0.dev20250802032821-g14638b6.
#pragma once
#include <stdint.h>

const int16_t space_to_depth_bs4_small_s16_input_tensor[64] = {
    48,  20,  -83, 46,   -109, -3, -77, 18,  92,  28,  13,  42,  -44, -23, -43, 2,   40,   -119, -26,  36,  -93, -98,
    -23, -94, 119, 18,   90,   4,  87,  -30, -91, 59,  -44, 91,  113, -57, 81,  -54, -120, 53,   -110, -59, 4,   -19,
    42,  40,  36,  -120, -38,  15, 4,   92,  -33, -41, -49, -53, 98,  53,  -80, -67, 4,    -78,  -84,  -50};
