// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t where_3d_sparse_s16_condition_input_tensor[8] = {0, 500, 0, 0, -100, 0, 200, 0};
