// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define WHERE_3D_SPARSE_S16_FORCE_NO_QUANTIZE true
#define WHERE_3D_SPARSE_S16_SHAPE                                                                                      \
    {                                                                                                                  \
        2, 2, 2,                                                                                                       \
    }
#define WHERE_3D_SPARSE_S16_CONDITION_VALUES                                                                           \
    {                                                                                                                  \
        0, 500, 0, 0, -100, 0, 200, 0,                                                                                 \
    }
#define WHERE_3D_SPARSE_S16_RANK 3
#define WHERE_3D_SPARSE_S16_SIZE 8
#define WHERE_3D_SPARSE_S16_COND_SIZE 8
