// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t edge_equal_k_1d_valid_33ch_3w_bias[33] = {
    20797,  834,    16244,  31244,  1855,  -26620, 14426,  3322,   -24391, 20660,  -24171,
    20095,  -14219, -77141, -20770, 9049,  27554,  44584,  32482,  -38360, -33818, 43225,
    -13888, 18176,  -13543, -30790, 15638, -19720, -14270, -36800, 20996,  -22356, -35478};

const int32_t *const edge_equal_k_1d_valid_33ch_3w_biases = edge_equal_k_1d_valid_33ch_3w_bias;
