// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t edge_equal_k_1d_valid_33ch_3w_output_shift[33] = {-9, -8, -8,  -9, -10, -9, -8, -8, -8, -9, -8,
                                                                -8, -8, -10, -8, -8,  -8, -9, -8, -8, -8, -9,
                                                                -8, -8, -8,  -8, -8,  -8, -8, -9, -9, -8, -9};
