// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t edge_equal_k_1d_valid_33ch_3w_output[33] = {26,  102, 49,  67,  47, -41, 71, -34, -42, 13,  -54,
                                                         -6,  5,   -16, -22, 63, 111, 93, 95,  -88, -9,  126,
                                                         -40, -6,  -62, -19, 51, -70, 20, -62, -19, -97, -24};

const int8_t *const edge_equal_k_1d_valid_33ch_3w_output_ref = edge_equal_k_1d_valid_33ch_3w_output;
