// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once

#define MEAN_AXIS_N_S16_IN_DIM                                                                                         \
    {                                                                                                                  \
        2, 3, 2, 4,                                                                                                    \
    }
#define MEAN_AXIS_N_S16_AXIS                                                                                           \
    {                                                                                                                  \
        0,                                                                                                             \
    }
#define MEAN_AXIS_N_S16_KEEP_DIMS true
#define MEAN_AXIS_N_S16_ASYMMETRIC_QUANTIZE_INPUTS 0
#define MEAN_AXIS_N_S16_OUT_DIM                                                                                        \
    {                                                                                                                  \
        1, 3, 2, 4,                                                                                                    \
    }
#define MEAN_AXIS_N_S16_AXIS_DIM                                                                                       \
    {                                                                                                                  \
        1, 0, 0, 0,                                                                                                    \
    }
#define MEAN_AXIS_N_S16_AXIS_MASK 8
#define MEAN_AXIS_N_S16_INPUT_SIZE 48
#define MEAN_AXIS_N_S16_OUTPUT_SIZE 24
#define MEAN_AXIS_N_S16_INPUT_OFFSET 0
#define MEAN_AXIS_N_S16_OUTPUT_OFFSET 0
#define MEAN_AXIS_N_S16_OUTPUT_MULTIPLIER 1343350124
#define MEAN_AXIS_N_S16_OUTPUT_SHIFT 0
#define MEAN_AXIS_N_S16_REDUCTION_SIZE 2
