// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t mean_axis_n_s16_input_tensor[48] = {
    32165,  -25101, -26724, 32352, 24834, -19963, -20534, -17401, 10150,  -28354, 27068,  -25154,
    -32474, 12470,  23352,  21436, 11941, -26099, 27786,  -32420, -16091, -20466, 8091,   -4979,
    13298,  -12144, 21454,  8570,  -2535, -2336,  20142,  750,    -11209, -951,   -28572, 5627,
    -1935,  -7065,  31334,  25250, 4395,  6625,   10586,  -20624, -7152,  -12133, -12298, 30390};
