// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t mean_axis_n_s16_output[24] = {28439, -23298, -3297, 25599,  13949,  -13949, -245,  -10416,
                                            -662,  -18332, -941,  -12215, -21524, 3381,   32767, 29204,
                                            10219, -12182, 24003, -32768, -14540, -20392, -2632, 15896};
