// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t reduce_min_axis_wc_s16_output[20] = {-27065, -28909, -32658, -32049, -32020, -32326, -30641,
                                                   -30565, -31603, -32547, -31896, -31111, -22981, -31080,
                                                   -27847, -32150, -31420, -31745, -28846, -30829};
