// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once


#define SLICE_CASE2_INPUT_N    2
#define SLICE_CASE2_INPUT_H    3
#define SLICE_CASE2_INPUT_W    2
#define SLICE_CASE2_INPUT_C    1

#define SLICE_CASE2_BEGIN_N    0
#define SLICE_CASE2_BEGIN_H    1
#define SLICE_CASE2_BEGIN_W    0
#define SLICE_CASE2_BEGIN_C    0

#define SLICE_CASE2_END_N      2
#define SLICE_CASE2_END_H      3
#define SLICE_CASE2_END_W      2
#define SLICE_CASE2_END_C      1

#define SLICE_CASE2_STRIDES_N  1
#define SLICE_CASE2_STRIDES_H  1
#define SLICE_CASE2_STRIDES_W  1
#define SLICE_CASE2_STRIDES_C  1

#define SLICE_CASE2_OUTPUT_SIZE 8
#define SLICE_CASE2_OUTPUT_N    2
#define SLICE_CASE2_OUTPUT_H    2
#define SLICE_CASE2_OUTPUT_W    2
#define SLICE_CASE2_OUTPUT_C    1
