// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.13.2).
// Interpreter from tflite_micro runtime version 0.dev20251103221221-gv1.3.0-45-gac157ac1-dirty.
#pragma once
#include <stdint.h>

const int16_t squared_difference_scalar_s16_lhs_input_tensor[24] = {
    10245, 33,    -18544, 8040,   21923,  24193, 18933, -4554,  19373, 17002, -5082, -13378,
    24905, 22511, -17546, -14126, -31579, 12225, 3945,  -29652, 25198, 25133, 18997, -19657};
