// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define GATHER_AXIS_H_MULTI_S8_INPUT_DIM                                                                               \
    {                                                                                                                  \
        1, 3, 2, 2,                                                                                                    \
    }
#define GATHER_AXIS_H_MULTI_S8_INPUT_RANK 4
#define GATHER_AXIS_H_MULTI_S8_INDICES_DIM                                                                             \
    {                                                                                                                  \
        2, 1, 1, 1,                                                                                                    \
    }
#define GATHER_AXIS_H_MULTI_S8_INDICES_RANK 1
#define GATHER_AXIS_H_MULTI_S8_INDICES_VALUES                                                                          \
    {                                                                                                                  \
        0, 2,                                                                                                          \
    }
#define GATHER_AXIS_H_MULTI_S8_AXIS 1
#define GATHER_AXIS_H_MULTI_S8_BATCH_DIMS 0
#define GATHER_AXIS_H_MULTI_S8_INPUT_N 1
#define GATHER_AXIS_H_MULTI_S8_INPUT_H 3
#define GATHER_AXIS_H_MULTI_S8_INPUT_W 2
#define GATHER_AXIS_H_MULTI_S8_INPUT_C 2
#define GATHER_AXIS_H_MULTI_S8_INDICES_N 2
#define GATHER_AXIS_H_MULTI_S8_INDICES_H 1
#define GATHER_AXIS_H_MULTI_S8_INDICES_W 1
#define GATHER_AXIS_H_MULTI_S8_INDICES_C 1
#define GATHER_AXIS_H_MULTI_S8_COORDS_RANK 1
#define GATHER_AXIS_H_MULTI_S8_INDICES_LENGTH 2
#define GATHER_AXIS_H_MULTI_S8_OUTPUT_N 1
#define GATHER_AXIS_H_MULTI_S8_OUTPUT_H 2
#define GATHER_AXIS_H_MULTI_S8_OUTPUT_W 2
#define GATHER_AXIS_H_MULTI_S8_OUTPUT_C 2
#define GATHER_AXIS_H_MULTI_S8_OUTPUT_SIZE 8
