// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.13.2).
// Interpreter from tflite_micro runtime version 0.dev20251103221221-gv1.3.0-45-gac157ac1-dirty.
#pragma once
#include <stdint.h>

const int16_t squared_difference_ident_s16_output[24] = {30067, 47,    8928, 553,   32767, 2779, 8,     32767,
                                                         9665,  32767, 217,  32767, 401,   3750, 32767, 17432,
                                                         15570, 32767, 4538, 32767, 11644, 2756, 3426,  32767};

const int16_t *const squared_difference_ident_s16_output_ref = squared_difference_ident_s16_output;
