// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.13.2).
// Interpreter from tflite_micro runtime version 0.dev20251103221221-gv1.3.0-45-gac157ac1-dirty.
#pragma once
#include <stdint.h>

const int16_t squared_difference_ident_s16_rhs_input_tensor[24] = {
    17912,  -16090, -26729, -6924, -24057, -12798, 19840, 30427, 19042,  13085,  -16314, 18425,
    -11055, -19202, 26571,  30602, 7184,   20842,  3639,  24304, -11751, -13906, 21532,  -24991};
