// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tflite_micro runtime version 0.dev20250802032821-g14638b6.
#pragma once

#define DEPTH_TO_SPACE_BS2_BASIC_S8_IN_DIM                                                                             \
    {                                                                                                                  \
        1, 8, 8, 12,                                                                                                   \
    }
#define DEPTH_TO_SPACE_BS2_BASIC_S8_BLOCK_SIZE 2
#define DEPTH_TO_SPACE_BS2_BASIC_S8_OUT_DIM                                                                            \
    {                                                                                                                  \
        1, 16, 16, 3,                                                                                                  \
    }
#define DEPTH_TO_SPACE_BS2_BASIC_S8_INPUT_SIZE 768
#define DEPTH_TO_SPACE_BS2_BASIC_S8_OUTPUT_SIZE 768
#define DEPTH_TO_SPACE_BS2_BASIC_S8_INPUT_OFFSET 128
#define DEPTH_TO_SPACE_BS2_BASIC_S8_OUTPUT_OFFSET -128
