// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t batch_to_space_nd_both_crops_s16_input_tensor[96] = {
    -101, -78,  -62, 86,  23,  -71,  2,   -61,  -118, -116, 26,  70,  11,  16,  -115, -85, 50,   88,   -2,  14,
    -126, 60,   -47, 26,  77,  38,   -16, -102, 70,   -67,  -97, -10, 72,  -18, 118,  -61, -96,  8,    -66, -111,
    -106, -120, 59,  -50, -42, -118, 90,  70,   96,   -70,  -25, 126, 63,  68,  41,   68,  -124, 86,   26,  77,
    -77,  95,   122, -20, -66, -86,  -88, -106, 97,   -82,  -18, 31,  100, -9,  -30,  41,  -89,  -100, 103, 33,
    -82,  -18,  -84, 68,  76,  69,   7,   -46,  96,   -11,  74,  14,  94,  -23, 94,   3};
