// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t int16xint8_spill_output_mult[9] =
    {1098630016, 1098332800, 1098420608, 1098358912, 1098454272, 1098597120, 1098541440, 1098419840, 1097743232};
