// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t slice_strided_2x3_s16_input_tensor[36] = {12030, 29755, 6227,  17554, 1883,  31957, 26251, 13782, 29205,
                                                        22806, 2620,  31304, 12773, 8006,  4707,  11473, 616,   13247,
                                                        25950, 6219,  10002, 24223, 31863, 11321, 15340, 32032, 5157,
                                                        11903, 27748, 25346, 16935, 5787,  21471, 27631, 2445,  5155};
