// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t slice_strided_2x3_s16_output[6] = {12030, 17554, 12773, 11473, 15340, 11903};
