// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tflite_micro runtime version 0.dev20250802032821-g14638b6.
#pragma once

#define SPACE_TO_DEPTH_BS2_BATCH_S16_IN_DIM                                                                            \
    {                                                                                                                  \
        3, 10, 6, 2,                                                                                                   \
    }
#define SPACE_TO_DEPTH_BS2_BATCH_S16_BLOCK_SIZE 2
#define SPACE_TO_DEPTH_BS2_BATCH_S16_OUT_DIM                                                                           \
    {                                                                                                                  \
        3, 5, 3, 8,                                                                                                    \
    }
#define SPACE_TO_DEPTH_BS2_BATCH_S16_INPUT_SIZE 360
#define SPACE_TO_DEPTH_BS2_BATCH_S16_OUTPUT_SIZE 360
#define SPACE_TO_DEPTH_BS2_BATCH_S16_INPUT_OFFSET 128
#define SPACE_TO_DEPTH_BS2_BATCH_S16_OUTPUT_OFFSET -128
