// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t space_to_batch_nd_nsquare_pad_s8_output[72] = {
    -128, -128, -128, -44,  17,   -9,   115,  117,  -91,  -128, -128, -128, -128, -128, -128, -87,  14,   -128,
    104,  63,   -128, -128, -128, -128, -128, -128, -128, -21,  -116, -128, -27,  -28,  -128, -128, -128, -128,
    -29,  24,   -111, 83,   -124, -62,  70,   68,   -16,  -128, -128, -128, 124,  -98,  -128, 8,    -16,  -128,
    -109, -46,  -128, -128, -128, -128, -113, 98,   -128, 32,   -89,  -128, -70,  -127, -128, -128, -128, -128};
