/*
 * SPDX-FileCopyrightText: 2025 Ambiq
 *
 * SPDX-License-Identifier: LicenseRef-Ambiq-Apollo-SDK
 *
 * Licensed under the Ambiq Apollo SDK License.
 * See LICENSE (root) or LICENSES/LicenseRef-Ambiq-Apollo-SDK.txt for the full text.
 */

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../test_arm_batch_to_space_nd_s16.c"
#include "unity.h"

#ifdef USING_FVP_CORSTONE_300
extern void uart_init(void);
#endif

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void setUp(void)
{ /* This is run before EACH TEST */
#ifdef USING_FVP_CORSTONE_300
    uart_init();
#endif
}

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void tearDown(void) {}

/* Unity-visible test entry points */
/* Unity test entry points (names starting with test_) */
void test_batch_to_space_nd_basic_2x2_s16(void)            { batch_to_space_nd_basic_2x2_s16_arm_batch_to_space_nd_s16(); }
void test_batch_to_space_nd_nsquare_crops_s16(void)        { batch_to_space_nd_nsquare_crops_s16_arm_batch_to_space_nd_s16(); }
void test_batch_to_space_nd_batch_s16(void)                { batch_to_space_nd_batch_s16_arm_batch_to_space_nd_s16(); }
void test_batch_to_space_nd_both_crops_s16(void)           { batch_to_space_nd_both_crops_s16_arm_batch_to_space_nd_s16(); }
void test_batch_to_space_nd_bs1_identity_s16(void)         { batch_to_space_nd_bs1_identity_s16_arm_batch_to_space_nd_s16(); }
