// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mean_axis_h_s8_input_tensor[16] = {34, 5, -98, -45, 33, -66, -51, 73, -82, 77, -24, 19, 92, 97, 115, 116};
