// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define SUB_LHS_N 1
#define SUB_LHS_H 1
#define SUB_LHS_W 1
#define SUB_LHS_C 128
#define SUB_RHS_N 1
#define SUB_RHS_H 1
#define SUB_RHS_W 1
#define SUB_RHS_C 128
#define SUB_ASYMMETRIC_QUANTIZE_INPUTS 0
#define SUB_DST_SIZE 128
#define SUB_OUTPUT_N 1
#define SUB_OUTPUT_H 1
#define SUB_OUTPUT_W 1
#define SUB_OUTPUT_C 128
#define SUB_LHS_OFFSET 128
#define SUB_LHS_MULT 1073741824
#define SUB_LHS_SHIFT 0
#define SUB_RHS_OFFSET 128
#define SUB_RHS_MULT 2147226586
#define SUB_RHS_SHIFT -1
#define SUB_INPUT1_OFFSET 128
#define SUB_INPUT1_MULT 1073741824
#define SUB_INPUT1_SHIFT 0
#define SUB_INPUT2_OFFSET 128
#define SUB_INPUT2_MULT 2147226586
#define SUB_INPUT2_SHIFT -1
#define SUB_OUTPUT_OFFSET 1
#define SUB_OUTPUT_MULT 1089953761
#define SUB_OUTPUT_SHIFT -19
#define SUB_OUTPUT_MULTIPLIER 1089953761
#define SUB_LEFT_SHIFT 20
#define SUB_ACTIVATION_MIN -128
#define SUB_ACTIVATION_MAX 127
