// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t sub_output[128] = {
    1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   34,  -32,
    -22, 62,  1,   1,   1,   1,   1,   1,   1,   1,   17,  1,   1,   1,   1,   1,   1,   1,   -23, 1,   1,   1,
    1,   1,   1,   1,   9,   34,  -18, -20, 8,   -48, 1,   1,   -11, 51,  -16, -20, 8,   -48, 1,   1,   -58, -50,
    -57, -58, -22, -52, -55, -22, -42, -30, -44, -29, -64, 50,  1,   1,   -57, -51, -22, -34, -50, -56, -58, -52,
    17,  1,   1,   1,   1,   1,   1,   1,   -40, 33,  -23, -20, 8,   -48, 1,   1,   -7,  -47, -26, -20, -46, 16,
    -13, -49, 1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1,   1};

const int8_t *const sub_output_ref = sub_output;
