// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t reduce_max_axis_wc_s8_output[20] = {123, 119, 120, 125, 125, 124, 126, 107, 114, 116,
                                                 125, 123, 127, 117, 123, 125, 127, 125, 123, 123};
