// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int64_t int16xint8_group_same_bias[8] = {3676715, 81181, -390908, -2970198, -651034, 2892236, -2248495, 182136};

const int64_t *const int16xint8_group_same_biases = int16xint8_group_same_bias;
