// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t resize_nn_half_pixel_s8_input_tensor[24] = {-66, -52,  -26, -78, -41, 118, 40,  72, -5,  -114, -111, 81,
                                                         -24, -119, 11,  -39, 10,  40,  -45, -7, -23, 110,  -100, -109};
