// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define DYNAMIC_UPDATE_SLICE_START_ZERO_S16_FORCE_NO_QUANTIZE true
#define DYNAMIC_UPDATE_SLICE_START_ZERO_S16_OPERAND_SHAPE                                                              \
    {                                                                                                                  \
        2, 3,                                                                                                          \
    }
#define DYNAMIC_UPDATE_SLICE_START_ZERO_S16_UPDATE_SHAPE                                                               \
    {                                                                                                                  \
        1, 3,                                                                                                          \
    }
#define DYNAMIC_UPDATE_SLICE_START_ZERO_S16_START_INDICES                                                              \
    {                                                                                                                  \
        0, 0,                                                                                                          \
    }
#define DYNAMIC_UPDATE_SLICE_START_ZERO_S16_OPERAND_VALUES                                                             \
    {                                                                                                                  \
        100, 200, 300, 400, 500, 600,                                                                                  \
    }
#define DYNAMIC_UPDATE_SLICE_START_ZERO_S16_UPDATE_VALUES                                                              \
    {                                                                                                                  \
        900, 800, 700,                                                                                                 \
    }
#define DYNAMIC_UPDATE_SLICE_START_ZERO_S16_RANK 2
#define DYNAMIC_UPDATE_SLICE_START_ZERO_S16_OPERAND_SIZE 6
#define DYNAMIC_UPDATE_SLICE_START_ZERO_S16_UPDATE_SIZE 3
#define DYNAMIC_UPDATE_SLICE_START_ZERO_S16_OPERAND_STRIDES                                                            \
    {                                                                                                                  \
        3, 1,                                                                                                          \
    }
