// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t sub_broadcast_c_s16_input_data[24] = {8688,   22856,  30133, 0,     -17216, 20573,  30133,  0,
                                                    4605,   -10938, 27151, -7806, 22192,  22856,  30133,  0,
                                                    -32496, -6106,  30133, 0,     32317,  -23105, -22316, -16202};
