// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t sub_broadcast_c_s16_rhs_input_tensor[6] = {-13927, 17338, -3122, -25608, 22272, 22856};
