// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once
#include <stdint.h>

const int8_t squared_difference_scalar_s8_lhs_input_tensor[24] = {
    46, -29, -96, -30, -27, 74, -58, 88, -9, -93, -92, -36, -71, 47, -42, 18, -65, -103, 38, -13, -97, 107, 101, -48};
