// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t sub_broadcast_h_s16_output[24] = {5679,   -18820, -30646, 0, 5646, -18820, -30646, 0,
                                                -24604, -18821, -30646, 0, 5614, -18820, -30646, 0,
                                                0,      0,      0,      0, -65,  0,      0,      0};

const int16_t *const sub_broadcast_h_s16_output_ref = sub_broadcast_h_s16_output;
