// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t edge_equal_k_1d_valid_8ch_3h_bias[8] = {-89348, -11966, 3183, 17128, 13190, 338, 1671, 44535};

const int32_t *const edge_equal_k_1d_valid_8ch_3h_biases = edge_equal_k_1d_valid_8ch_3h_bias;
