// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t edge_equal_k_1d_valid_8ch_3h_input_tensor[24] = {
    -45, 32, 9, -23, -128, 24, -24, -96, 105, 57, -72, 120, -88, -120, -2, 20, -31, -77, -24, -56, -93, -73, -111, -23};
