// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t edge_equal_k_1d_valid_8ch_3h_output_multiplier[8] =
    {1116297308, 1826210508, 1936169717, 2028290577, 1699283491, 1657395636, 1676258808, 1535002748};

const int32_t *const edge_equal_k_1d_valid_8ch_3h_output_mult = edge_equal_k_1d_valid_8ch_3h_output_multiplier;
