// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define DYNAMIC_UPDATE_SLICE_3D_EDGE_S16_FORCE_NO_QUANTIZE true
#define DYNAMIC_UPDATE_SLICE_3D_EDGE_S16_OPERAND_SHAPE                                                                 \
    {                                                                                                                  \
        2, 3, 2,                                                                                                       \
    }
#define DYNAMIC_UPDATE_SLICE_3D_EDGE_S16_UPDATE_SHAPE                                                                  \
    {                                                                                                                  \
        1, 2, 2,                                                                                                       \
    }
#define DYNAMIC_UPDATE_SLICE_3D_EDGE_S16_START_INDICES                                                                 \
    {                                                                                                                  \
        1, 1, 0,                                                                                                       \
    }
#define DYNAMIC_UPDATE_SLICE_3D_EDGE_S16_OPERAND_VALUES                                                                \
    {                                                                                                                  \
        100, -200, 300, -400, 500, -600, 700, -800, 900, -1000, 1100, -1200,                                           \
    }
#define DYNAMIC_UPDATE_SLICE_3D_EDGE_S16_UPDATE_VALUES                                                                 \
    {                                                                                                                  \
        -100, -200, -300, -400,                                                                                        \
    }
#define DYNAMIC_UPDATE_SLICE_3D_EDGE_S16_RANK 3
#define DYNAMIC_UPDATE_SLICE_3D_EDGE_S16_OPERAND_SIZE 12
#define DYNAMIC_UPDATE_SLICE_3D_EDGE_S16_UPDATE_SIZE 4
#define DYNAMIC_UPDATE_SLICE_3D_EDGE_S16_OPERAND_STRIDES                                                               \
    {                                                                                                                  \
        6, 2, 1,                                                                                                       \
    }
