// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t reduce_min_axis_hw_s16_output[20] = {-32495, -32235, -30314, -31911, -32495, -32485, -31997,
                                                   -32571, -32107, -31069, -31922, -31596, -31708, -32760,
                                                   -32090, -32744, -32687, -32399, -30605, -31483};
