// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t resize_nn_downsample_s8_output[36] = {20,   13,  112, -85, 72,  25,  38,  -123, -21,  124, 33,  -119,
                                                   -116, -55, -19, 69,  -27, -54, 93,  46,   -98,  75,  14,  61,
                                                   125,  55,  -45, -84, -99, -26, -87, 30,   -113, 3,   -22, -115};
