// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t reduce_min_axis_w_s16_input_tensor[16] =
    {4055, -7734, -14503, 7792, 21318, 2658, 26640, 5746, -28844, 21643, 28958, 19258, -15368, 6448, 25049, 7591};
