// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t abs_small_tensor_s16_input_tensor[24] = {9229,   28398,  -11289, -8949, -31287, 23,    -29149, 20906,
                                                       -25751, -28880, -24562, 23724, 2498,   11395, -21664, -24797,
                                                       -27931, -7940,  17257,  4573,  31591,  -1361, 29598,  -24093};
