// Generated by generate_test_data.py using tensorflow version 2.19.0 (Keras version 3.9.2).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int16_t quantize_s16_s16_output[8] = {22395, -5496, 75, -11002, 16200, 6642, 8443, -22573};
