// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tflite_micro runtime version 0.dev20250802032821-g14638b6.
#pragma once

#define DEPTH_TO_SPACE_BS2_CHANNELS_S16_IN_DIM                                                                         \
    {                                                                                                                  \
        1, 6, 10, 20,                                                                                                  \
    }
#define DEPTH_TO_SPACE_BS2_CHANNELS_S16_BLOCK_SIZE 2
#define DEPTH_TO_SPACE_BS2_CHANNELS_S16_OUT_DIM                                                                        \
    {                                                                                                                  \
        1, 12, 20, 5,                                                                                                  \
    }
#define DEPTH_TO_SPACE_BS2_CHANNELS_S16_INPUT_SIZE 1200
#define DEPTH_TO_SPACE_BS2_CHANNELS_S16_OUTPUT_SIZE 1200
