// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t reduce_max_axis_wc_s16_output[20] = {28394, 32005, 30076, 32432, 31712, 29842, 27576,
                                                   32311, 27129, 32717, 30917, 29569, 25644, 27883,
                                                   32056, 28418, 32765, 28876, 32358, 30423};
