// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define MIRROR_PAD_REFLECT_2D_S16_FORCE_NO_QUANTIZE true
#define MIRROR_PAD_REFLECT_2D_S16_INPUT_SHAPE                                                                          \
    {                                                                                                                  \
        2, 3,                                                                                                          \
    }
#define MIRROR_PAD_REFLECT_2D_S16_PAD_BEFORE                                                                           \
    {                                                                                                                  \
        1, 1,                                                                                                          \
    }
#define MIRROR_PAD_REFLECT_2D_S16_MODE 0
#define MIRROR_PAD_REFLECT_2D_S16_INPUT_VALUES                                                                         \
    {                                                                                                                  \
        100, 200, 300, 400, 500, 600,                                                                                  \
    }
#define MIRROR_PAD_REFLECT_2D_S16_RANK 2
#define MIRROR_PAD_REFLECT_2D_S16_INPUT_SIZE 6
#define MIRROR_PAD_REFLECT_2D_S16_OUTPUT_SIZE 20
#define MIRROR_PAD_REFLECT_2D_S16_OUTPUT_SHAPE                                                                         \
    {                                                                                                                  \
        4, 5,                                                                                                          \
    }
