// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t grouped_conv_4_output_mult[6] = {1381728384, 1585376000, 1603612288, 1170515200, 1242764416, 2067708928};
