// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t grouped_conv_4_weights[24] = {19,  -106, 127, 39, -8,   -9,  -127, 103, 34, 87, -127, 1,
                                           -32, -127, 72,  92, -127, -75, 33,   53,  -6, 67, -44,  127};
