// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_4_input[64] = {-22, -115, 50,  -79,  34,   -24,  -100, 67,   -106, 118,  98,   -27, -109,
                                       59,  -101, 89,  -93,  -113, -113, -92,  22,   31,   -114, 12,   6,   -83,
                                       80,  -28,  25,  -104, 60,   28,   36,   95,   50,   112,  10,   45,  -49,
                                       9,   77,   -93, -109, 120,  64,   -60,  -122, 38,   62,   -119, 70,  -4,
                                       93,  34,   -82, -39,  34,   -48,  121,  122,  105,  40,   -61,  -32};
