// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_4_output_ref[32] = {-55, 60,  1,   -7, -59, 86, -61, 11, -25, 77, -11, 9,  -54, 65, -21, 4,
                                            -52, 105, -68, 24, -21, 87, -17, 4,  -35, 91, -21, 17, -84, 88, -27, 17};
