// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#define CONV_1_X_N_3_OUT_CH 1
#define CONV_1_X_N_3_IN_CH 4
#define CONV_1_X_N_3_INPUT_W 296
#define CONV_1_X_N_3_INPUT_H 1
#define CONV_1_X_N_3_DST_SIZE 148
#define CONV_1_X_N_3_INPUT_SIZE 1184
#define CONV_1_X_N_3_OUT_ACTIVATION_MIN -111
#define CONV_1_X_N_3_OUT_ACTIVATION_MAX 127
#define CONV_1_X_N_3_INPUT_BATCHES 1
#define CONV_1_X_N_3_FILTER_X 48
#define CONV_1_X_N_3_FILTER_Y 1
#define CONV_1_X_N_3_STRIDE_X 2
#define CONV_1_X_N_3_STRIDE_Y 1
#define CONV_1_X_N_3_PAD_X 23
#define CONV_1_X_N_3_PAD_Y 0
#define CONV_1_X_N_3_OUTPUT_W 148
#define CONV_1_X_N_3_OUTPUT_H 1
#define CONV_1_X_N_3_INPUT_OFFSET 128
#define CONV_1_X_N_3_OUTPUT_OFFSET -47
#define CONV_1_X_N_3_DILATION_X 1
#define CONV_1_X_N_3_DILATION_Y 1
