// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define TILE_1D_REPEAT_S16_FORCE_NO_QUANTIZE true
#define TILE_1D_REPEAT_S16_INPUT_SHAPE                                                                                 \
    {                                                                                                                  \
        4,                                                                                                             \
    }
#define TILE_1D_REPEAT_S16_MULTIPLES                                                                                   \
    {                                                                                                                  \
        3,                                                                                                             \
    }
#define TILE_1D_REPEAT_S16_INPUT_VALUES                                                                                \
    {                                                                                                                  \
        100, -100, 200, -200,                                                                                          \
    }
#define TILE_1D_REPEAT_S16_RANK 1
#define TILE_1D_REPEAT_S16_INPUT_SIZE 4
#define TILE_1D_REPEAT_S16_OUTPUT_SIZE 12
