// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t tile_1d_repeat_s16_output[12] = {100, -100, 200, -200, 100, -100, 200, -200, 100, -100, 200, -200};
