// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t space_to_batch_nd_nsquare_pad_s16_input_tensor[35] = {
    -116, -98,  -4, -104, -4,  37, 68, -45, 43,   24, -34, -90, -32, 55,  -7,  14,   -71, 11,
    -4,   -127, 13, -14,  -33, 61, 70, -69, -102, 67, 62,  54,  18,  -27, -76, -112, 62};
