// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t space_to_batch_nd_nsquare_pad_s16_output[72] = {
    0, 0, 0, -45,  -34,  55,   -14,  70,   67,   0, 0, 0, 0, 0, 0, 43,   -90,  0,
    -33,  -69,  0, 0, 0, 0, 0, 0, 0, 24,   -32,  0, 61,   -102, 0, 0, 0, 0,
    -116, -104, 68,   -7,   11,   13,   62,   -27,  62,   0, 0, 0, -98,  -4,   0, 14,   -4,   0,
    54,   -76,  0, 0, 0, 0, -4,   37,   0, -71,  -127, 0, 18,   -112, 0, 0, 0, 0};
