// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mul_broadcast_c_s8_lhs_input_tensor[24] = {0, 0, 0, 0, 0,   0,   0,  0,  0,   0,  0, 0,
                                                        0, 0, 0, 0, 112, -20, 45, 43, -70, 90, 0, 0};
