// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mul_broadcast_c_s8_output[24] = {-53, -53, -53, -53, -80, -80,  -80, -80, -29, -29, -29, -29,
                                              -42, -42, -42, -42, -73, -103, -88, -89, -78, 59,  -18, -18};

const int8_t *const mul_broadcast_c_s8_output_ref = mul_broadcast_c_s8_output;
