// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once

#define SLICE_STRIDED_2X3_BATCH_SIZE 1
#define SLICE_STRIDED_2X3_INPUT_N 1
#define SLICE_STRIDED_2X3_INPUT_H 6
#define SLICE_STRIDED_2X3_INPUT_W 6
#define SLICE_STRIDED_2X3_INPUT_C 1
#define SLICE_STRIDED_2X3_BEGIN                                                                                        \
    {                                                                                                                  \
        0, 0, 0, 0,                                                                                                    \
    }
#define SLICE_STRIDED_2X3_END                                                                                          \
    {                                                                                                                  \
        1, 6, 6, 1,                                                                                                    \
    }
#define SLICE_STRIDED_2X3_STRIDES                                                                                      \
    {                                                                                                                  \
        1, 2, 3, 1,                                                                                                    \
    }
#define SLICE_STRIDED_2X3_INPUT_BATCHES 1
#define SLICE_STRIDED_2X3_BEGIN_N 0
#define SLICE_STRIDED_2X3_BEGIN_H 0
#define SLICE_STRIDED_2X3_BEGIN_W 0
#define SLICE_STRIDED_2X3_BEGIN_C 0
#define SLICE_STRIDED_2X3_END_N 1
#define SLICE_STRIDED_2X3_END_H 6
#define SLICE_STRIDED_2X3_END_W 6
#define SLICE_STRIDED_2X3_END_C 1
#define SLICE_STRIDED_2X3_STRIDES_N 1
#define SLICE_STRIDED_2X3_STRIDES_H 2
#define SLICE_STRIDED_2X3_STRIDES_W 3
#define SLICE_STRIDED_2X3_STRIDES_C 1
#define SLICE_STRIDED_2X3_OUTPUT_SIZE 6
#define SLICE_STRIDED_2X3_OUTPUT_N 1
#define SLICE_STRIDED_2X3_OUTPUT_H 3
#define SLICE_STRIDED_2X3_OUTPUT_W 2
#define SLICE_STRIDED_2X3_OUTPUT_C 1
