// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t slice_strided_2x3_input_tensor[36] = {76, 87, 73, 52, 64, 49,  1,  112, 107, 50,  91,  122,
                                                   84, 70, 81, 5,  84, 125, 17, 86,  104, 119, 18,  85,
                                                   24, 72, 44, 9,  85, 41,  29, 20,  123, 79,  107, 47};
