// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define RESIZE_NN_BASIC_S16_INPUT_N 1
#define RESIZE_NN_BASIC_S16_INPUT_H 2
#define RESIZE_NN_BASIC_S16_INPUT_W 3
#define RESIZE_NN_BASIC_S16_INPUT_C 1
#define RESIZE_NN_BASIC_S16_OUTPUT_H 4
#define RESIZE_NN_BASIC_S16_OUTPUT_W 5
#define RESIZE_NN_BASIC_S16_ALIGN_CORNERS false
#define RESIZE_NN_BASIC_S16_HALF_PIXEL_CENTERS false
#define RESIZE_NN_BASIC_S16_ASYMMETRIC_QUANTIZE_INPUTS 0
#define RESIZE_NN_BASIC_S16_OUTPUT_N 1
#define RESIZE_NN_BASIC_S16_OUTPUT_C 1
#define RESIZE_NN_BASIC_S16_OUTPUT_SIZE 20
#define RESIZE_NN_BASIC_S16_OUTPUT_SIZE_N 1
#define RESIZE_NN_BASIC_S16_OUTPUT_SIZE_H 1
#define RESIZE_NN_BASIC_S16_OUTPUT_SIZE_W 1
#define RESIZE_NN_BASIC_S16_OUTPUT_SIZE_C 2
#define RESIZE_NN_BASIC_S16_OUTPUT_SIZE_DATA                                                                           \
    {                                                                                                                  \
        4, 5,                                                                                                          \
    }
