// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t resize_nn_basic_s16_output[20] = {20271,  20271,  30833,  30833,  19900,  20271,  20271,
                                                30833,  30833,  19900,  -13205, -13205, -20045, -20045,
                                                -10244, -13205, -13205, -20045, -20045, -10244};
