// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_2x2_dilation_5x5_input_output_ref[50] = {
    -61, -61, -61, -61, -49, -58, -47, -56, -61, -61, -61, -59, -61, -61, -61, -61, -61,
    -61, -56, -61, 17,  -56, -36, -61, 38,  -51, -10, -61, -28, -61, -53, -61, -50, -61,
    -29, -61, -38, -61, -46, -61, -54, -61, -55, -61, -28, -61, -37, -61, -42, -61};
