// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_2x2_dilation_5x5_input_weights[36] = {117, 115, 92,   78,  124,  44,   56,  -56, 100, -92,  60,   -96,
                                                        110, 107, -127, 68,  126,  40,   116, -93, 33,  -127, -114, 125,
                                                        -75, 110, 65,   -23, -120, -106, -7,  67,  -78, 69,   127,  64};
