// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_3x3_dilation_5x5_input_weights[36] = {-14, -90, -6,  34,  34, -80,  58, -8,  -95, 110, 124, 79,
                                                        119, 68,  -14, 127, 28, -42,  64, 101, -97, -27, 34,  103,
                                                        -34, -57, -43, -9,  89, -127, 92, -77, -32, -37, 85,  -106};
