// Generated by generate_comparison_data.py
#pragma once
#include <stdint.h>

const int16_t comparison_less_equal_broadcast_hw_s16_input_1_input_tensor[8] = {
    -1600, -1120, -640, -160, 320, 800, 1280, 1760
};
