// Generated by generate_comparison_data.py
#pragma once
#include <stdint.h>

const int16_t comparison_greater_broadcast_h_s16_input_2_input_tensor[24] = {
    -1270, -720, -360, 0, 170, 720, 1080, 1440, 

    1610, 2160, 2520, 2880, 3050, 3600, 3960, 4320, 

    4490, 5040, 5400, 5760, 5930, 6480, 6840, 7200
};
