// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t add_scalar_s8_output[24] = {2,  -55, 37, 12, 14, 65, 2, 2, -55, -53, 37, 12,
                                         14, 65,  2,  2,  2,  2,  2, 2, 2,   2,   2,  2};

const int8_t *const add_scalar_s8_output_ref = add_scalar_s8_output;
