// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once
#include <stdint.h>

const int8_t squared_difference_ident_s8_rhs_input_tensor[24] = {
    -45, 18, 14, 37, 40, 94, -68, -13, -30, 0, 101, 6, -91, -105, -55, 87, 109, -91, 81, -43, -69, -62, 124, 121};
