// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define ABS_LONG_ROW_S8_BATCH_SIZE 1
#define ABS_LONG_ROW_S8_HEIGHT_1 1
#define ABS_LONG_ROW_S8_WIDTH_1 64
#define ABS_LONG_ROW_S8_CHANNEL_1 1
#define ABS_LONG_ROW_S8_INPUT_OFFSET -128
#define ABS_LONG_ROW_S8_OUTPUT_OFFSET -128
#define ABS_LONG_ROW_S8_NEEDS_RESCALE false
#define ABS_LONG_ROW_S8_OUTPUT_MULTIPLIER 1
#define ABS_LONG_ROW_S8_OUTPUT_SHIFT 0
#define ABS_LONG_ROW_S8_OUT_ACTIVATION_MIN -128
#define ABS_LONG_ROW_S8_OUT_ACTIVATION_MAX 127
#define ABS_LONG_ROW_S8_OUTPUT_LEN 64
#define ABS_LONG_ROW_S8_BLOCK_SIZE 64
