// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t abs_long_row_s8_input_tensor[64] = {
    64,  109,  -15, -59, -13, -41,  112,  109, -28,  27,   -109, 50,   -112, 80,  9,   45, -77, -52, 16,  -46, 42,  -70,
    -26, 111,  -67, 117, 4,   -95,  -4,   52,  -116, -103, -107, -118, 53,   121, -1,  89, 105, 74,  89,  36,  117, 122,
    55,  -101, -36, 3,   20,  -128, -125, 28,  -4,   -99,  40,   106,  -16,  -64, -79, 68, -54, 82,  -73, 86};
