// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.13.2).
// Interpreter from tflite_micro runtime version 0.dev20251103221221-gv1.3.0-45-gac157ac1-dirty.
#pragma once
#include <stdint.h>

const int16_t squared_difference_broadcast_hc_s16_output[24] = {10410, 1719,  5899,  26670, 3349,  7134,  7032,  4393,
                                                                32767, 20,    2687,  20421, 32767, 16119, 26343, 6054,
                                                                198,   16453, 16297, 12119, 16964, 32767, 32767, 32767};

const int16_t *const squared_difference_broadcast_hc_s16_output_ref = squared_difference_broadcast_hc_s16_output;
