// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.13.2).
// Interpreter from tflite_micro runtime version 0.dev20251103221221-gv1.3.0-45-gac157ac1-dirty.
#pragma once
#include <stdint.h>

const int16_t squared_difference_broadcast_hc_s16_rhs_input_tensor[12] =
    {14314, 3576, 9841, -32727, -26694, -1460, -1568, -4685, 8215, -26931, -16957, -813};
