// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t hard_swish_basic_s16_output[24] = {-83, -94, 28, -116, 30,   92,  -75, 11, -103, -24, -13, 38,
                                                21,  100, 8,  118,  -113, 126, 72,  29, 46,   58,  3,   -3};
