function(_ns_cmsis_nn_fail message_text)
  message(FATAL_ERROR "ns-cmsis-nn package error: ${message_text}")
endfunction()

function(_ns_cmsis_nn_manifest_contains manifest_path needle result_var)
  file(READ "${manifest_path}" _ns_cmsis_nn_manifest_text)
  string(FIND "${_ns_cmsis_nn_manifest_text}" "${needle}" _ns_cmsis_nn_match)
  if(_ns_cmsis_nn_match EQUAL -1)
    set(${result_var} FALSE PARENT_SCOPE)
  else()
    set(${result_var} TRUE PARENT_SCOPE)
  endif()
endfunction()

function(ns_cmsis_nn_resolve_variant)
  set(options REQUIRE_ZEPHYR_CONTEXT)
  set(oneValueArgs PACKAGE_ROOT OUT_VAR TOOLCHAIN_OUT TARGET_CPU_OUT ARCH_OUT)
  cmake_parse_arguments(NS "${options}" "${oneValueArgs}" "" ${ARGN})

  if(NOT NS_PACKAGE_ROOT)
    _ns_cmsis_nn_fail("PACKAGE_ROOT is required")
  endif()

  set(_ns_manifest "${NS_PACKAGE_ROOT}/manifest.json")
  if(NOT EXISTS "${_ns_manifest}")
    _ns_cmsis_nn_fail("manifest.json not found at ${_ns_manifest}")
  endif()

  if(DEFINED ZEPHYR_TOOLCHAIN_VARIANT AND NOT "${ZEPHYR_TOOLCHAIN_VARIANT}" STREQUAL "")
    if(ZEPHYR_TOOLCHAIN_VARIANT STREQUAL "gnuarmemb" OR ZEPHYR_TOOLCHAIN_VARIANT STREQUAL "cross-compile")
      set(_ns_toolchain "gcc")
    elseif(ZEPHYR_TOOLCHAIN_VARIANT STREQUAL "armclang")
      set(_ns_toolchain "armclang")
    elseif(ZEPHYR_TOOLCHAIN_VARIANT STREQUAL "atfe")
      set(_ns_toolchain "atfe")
    else()
      _ns_cmsis_nn_fail(
        "unsupported Zephyr toolchain '${ZEPHYR_TOOLCHAIN_VARIANT}'. Supported toolchains: gnuarmemb, armclang, atfe"
      )
    endif()
  elseif(CMAKE_C_COMPILER_ID STREQUAL "GNU")
    set(_ns_toolchain "gcc")
  elseif(CMAKE_C_COMPILER_ID STREQUAL "ARMClang")
    set(_ns_toolchain "armclang")
  elseif(CMAKE_C_COMPILER_ID STREQUAL "Clang")
    set(_ns_toolchain "atfe")
  else()
    _ns_cmsis_nn_fail(
      "unable to map compiler '${CMAKE_C_COMPILER_ID}' to a supported toolchain. Supported compiler families: GNU, ARMClang, Clang"
    )
  endif()

  if(DEFINED NS_CMSIS_NN_TARGET_CPU AND NOT "${NS_CMSIS_NN_TARGET_CPU}" STREQUAL "")
    set(_ns_target_cpu "${NS_CMSIS_NN_TARGET_CPU}")
  elseif(DEFINED CONFIG_CPU_CORTEX_M0 AND CONFIG_CPU_CORTEX_M0)
    set(_ns_target_cpu "cortex-m0")
    set(_ns_public_arch "cortex-m0")
    set(_ns_arch_label "cm0")
    set(_ns_requires_fpu FALSE)
  elseif(DEFINED CONFIG_CPU_CORTEX_M0PLUS AND CONFIG_CPU_CORTEX_M0PLUS)
    set(_ns_target_cpu "cortex-m0")
    set(_ns_public_arch "cortex-m0")
    set(_ns_arch_label "cm0")
    set(_ns_requires_fpu FALSE)
  elseif(DEFINED CONFIG_CPU_CORTEX_M4 AND CONFIG_CPU_CORTEX_M4)
    set(_ns_target_cpu "cortex-m4")
    set(_ns_public_arch "cortex-m4+fp")
    set(_ns_arch_label "cm4")
    set(_ns_requires_fpu TRUE)
  elseif(DEFINED CONFIG_CPU_CORTEX_M55 AND CONFIG_CPU_CORTEX_M55)
    set(_ns_target_cpu "cortex-m55")
    set(_ns_public_arch "cortex-m55")
    set(_ns_arch_label "cm55")
    set(_ns_requires_fpu TRUE)
  elseif(DEFINED CMAKE_SYSTEM_PROCESSOR AND "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "cortex-m0")
    set(_ns_target_cpu "cortex-m0")
    set(_ns_public_arch "cortex-m0")
    set(_ns_arch_label "cm0")
    set(_ns_requires_fpu FALSE)
  elseif(DEFINED CMAKE_SYSTEM_PROCESSOR AND "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "cortex-m4")
    set(_ns_target_cpu "cortex-m4")
    set(_ns_public_arch "cortex-m4+fp")
    set(_ns_arch_label "cm4")
    set(_ns_requires_fpu TRUE)
  elseif(DEFINED CMAKE_SYSTEM_PROCESSOR AND "${CMAKE_SYSTEM_PROCESSOR}" STREQUAL "cortex-m55")
    set(_ns_target_cpu "cortex-m55")
    set(_ns_public_arch "cortex-m55")
    set(_ns_arch_label "cm55")
    set(_ns_requires_fpu TRUE)
  else()
    _ns_cmsis_nn_fail(
      "unable to infer supported Cortex-M target. Supported targets: cortex-m0, cortex-m4+fp, cortex-m55"
    )
  endif()

  if(DEFINED NS_CMSIS_NN_TARGET_CPU AND NOT "${NS_CMSIS_NN_TARGET_CPU}" STREQUAL "")
    if(NS_CMSIS_NN_TARGET_CPU STREQUAL "cortex-m0")
      set(_ns_public_arch "cortex-m0")
      set(_ns_arch_label "cm0")
      set(_ns_requires_fpu FALSE)
    elseif(NS_CMSIS_NN_TARGET_CPU STREQUAL "cortex-m4")
      set(_ns_public_arch "cortex-m4+fp")
      set(_ns_arch_label "cm4")
      set(_ns_requires_fpu TRUE)
    elseif(NS_CMSIS_NN_TARGET_CPU STREQUAL "cortex-m55")
      set(_ns_public_arch "cortex-m55")
      set(_ns_arch_label "cm55")
      set(_ns_requires_fpu TRUE)
    else()
      _ns_cmsis_nn_fail("unsupported NS_CMSIS_NN_TARGET_CPU '${NS_CMSIS_NN_TARGET_CPU}'")
    endif()
  endif()

  if(_ns_requires_fpu)
    if(DEFINED CONFIG_FPU AND NOT CONFIG_FPU)
      _ns_cmsis_nn_fail(
        "selected target '${_ns_public_arch}' requires CONFIG_FPU=y for the shipped hard-float binary package"
      )
    endif()
  endif()

  if(_ns_toolchain STREQUAL "gcc" OR _ns_toolchain STREQUAL "armclang")
    if(_ns_target_cpu STREQUAL "cortex-m0")
      set(_ns_float_abi "soft")
      set(_ns_feature_level "none")
    elseif(_ns_target_cpu STREQUAL "cortex-m4")
      set(_ns_float_abi "hard")
      set(_ns_feature_level "fpv4-sp-d16")
    else()
      set(_ns_float_abi "hard")
      set(_ns_feature_level "mve-fp")
    endif()
  else()
    if(_ns_target_cpu STREQUAL "cortex-m0")
      set(_ns_float_abi "soft")
      set(_ns_feature_level "none")
    elseif(_ns_target_cpu STREQUAL "cortex-m4")
      set(_ns_float_abi "hard")
      set(_ns_feature_level "fpv4-sp-d16")
    else()
      set(_ns_float_abi "hard")
      set(_ns_feature_level "mve-fp")
    endif()
  endif()

  set(_ns_library_name
    "libns-cmsis-nn-${_ns_arch_label}-${_ns_target_cpu}-${_ns_toolchain}-${_ns_float_abi}-${_ns_feature_level}-ofast.a"
  )
  set(_ns_library_path "${NS_PACKAGE_ROOT}/lib/${_ns_library_name}")
  if(NOT EXISTS "${_ns_library_path}")
    _ns_cmsis_nn_fail(
      "resolved variant '${_ns_library_name}' is not present in the package. Detected toolchain=${_ns_toolchain}, target=${_ns_target_cpu}"
    )
  endif()

  _ns_cmsis_nn_manifest_contains("${_ns_manifest}" "\"file\": \"${_ns_library_name}\"" _ns_manifest_has_file)
  if(NOT _ns_manifest_has_file)
    _ns_cmsis_nn_fail("resolved variant '${_ns_library_name}' is not declared in manifest.json")
  endif()

  set(${NS_OUT_VAR} "${_ns_library_path}" PARENT_SCOPE)
  if(NS_TOOLCHAIN_OUT)
    set(${NS_TOOLCHAIN_OUT} "${_ns_toolchain}" PARENT_SCOPE)
  endif()
  if(NS_TARGET_CPU_OUT)
    set(${NS_TARGET_CPU_OUT} "${_ns_target_cpu}" PARENT_SCOPE)
  endif()
  if(NS_ARCH_OUT)
    set(${NS_ARCH_OUT} "${_ns_public_arch}" PARENT_SCOPE)
  endif()
endfunction()
