#!/usr/bin/env bash
# Version: 3.0
# Date: 2024-01-09
# This bash script generates a CMSIS-NN Software Pack:
#

set -o pipefail

# Set version of gen pack library
# For available versions see https://github.com/Open-CMSIS-Pack/gen-pack/tags.
# Use the tag name without the prefix "v", e.g., 0.7.0
REQUIRED_GEN_PACK_LIB="0.11.3"

# Set default command line arguments
DEFAULT_ARGS=(-c "v")

# Pack warehouse directory - destination
# Default: ./output
#
# PACK_OUTPUT=./output

# Temporary pack build directory,
# Default: ./build
#
# PACK_BUILD=./build

# Specify directory names to be added to pack base directory
# An empty list defaults to all folders next to this script.
# Default: empty (all folders)
#
PACK_DIRS="
  Documentation
  Include
  Source
"

# When the release pipeline has staged the per-arch prebuilt archives at
# ./lib/<cpu>/libns-cmsis-nn.a (see .github/workflows/release.yml's
# publish-pack job), pull them into the pack so the Cvariant="Prebuilt"
# component's <file category="library"> entries resolve. packchk fails
# if a declared file is missing, so we never emit a pack with a half-
# vendored prebuilt variant — either all archs are staged or none.
if [[ -d "$(dirname "${BASH_SOURCE[0]}")/lib" \
      || "${NS_CMSIS_NN_PREBUILT_LIBS_STAGED:-0}" == "1" ]]; then
  PACK_DIRS="${PACK_DIRS}
  lib
"
fi

# Specify file names to be added to pack base directory
# Default: empty
#
PACK_BASE_FILES="
  LICENSE
  README.md
"

# Specify file names to be deleted from pack build directory
# Default: empty
#
PACK_DELETE_FILES="
  Documentation/Doxygen
  Documentation/README.md
"

# Specify patches to be applied
# Default: empty
#
# PACK_PATCH_FILES=""

# Specify addition argument to packchk
# Default: empty
#
# PACKCHK_ARGS=()

# Specify additional dependencies for packchk
# Default: empty
#
PACKCHK_DEPS="
  ARM.CMSIS.pdsc
"

# Optional: restrict fallback modes for changelog generation
# Default: full
# Values:
# - full      Tag annotations, release descriptions, or commit messages (in order)
# - release   Tag annotations, or release descriptions (in order)
# - tag       Tag annotations only
#
# NOTE: Use "tag" mode to avoid XML schema failures when GitHub release notes
# (auto-generated by release-please from conventional-commit PR titles) contain
# characters that are reserved in XML, such as '&', '<', or '>'. These appear
# unescaped in the pdsc <release> body in "release"/"full" modes and break the
# packchk schema validation against PACK.xsd. With "tag" mode only the version
# and date are emitted; full release notes still live on the GitHub Release page.
: "${PACK_CHANGELOG_MODE:=tag}"
# custom pre-processing steps
#
# usage: preprocess <build>
#   <build>  The build folder
#
function preprocess() {
  # add custom steps here to be executed
  # before populating the pack build folder
  ./Documentation/Doxygen/gen_doc.sh
  return 0
}
# custom post-processing steps
#
# usage: postprocess <build>
#   <build>  The build folder
#
function postprocess() {
  # Set component version to match pack version
  VERSION=$(git_describe "${CHANGELOG}" | sed -e "s/+g.*$//")
  sed -i -e "s/Cgroup=\"NN Lib\" Cversion=\"[^\"]*\"/Cgroup=\"NN Lib\" Cversion=\"${VERSION}\"/" ${PACK_BUILD}/Ambiq.NS-CMSIS-NN.pdsc
}

############ DO NOT EDIT BELOW ###########

# Set GEN_PACK_LIB_PATH to use a specific gen-pack library root
# ... instead of bootstrap based on REQUIRED_GEN_PACK_LIB
if [[ -f "${GEN_PACK_LIB_PATH}/gen-pack" ]]; then
  . "${GEN_PACK_LIB}/gen-pack"
else
  . <(curl -sL "https://raw.githubusercontent.com/Open-CMSIS-Pack/gen-pack/main/bootstrap")
fi

gen_pack "${DEFAULT_ARGS[@]}" "$@"

exit 0
