// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t add_broadcast_c_s8_output[24] = {-30, -30, -30, -30, -47, -47, -47, -47, 38, 38, 38, 38,
                                              13,  13,  13,  13,  14,  14,  14,  14,  66, 66, 66, 66};

const int8_t *const add_broadcast_c_s8_output_ref = add_broadcast_c_s8_output;
