// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.13.2).
// Interpreter from tflite_micro runtime version 0.dev20251103221221-gv1.3.0-45-gac157ac1-dirty.
#pragma once
#include <stdint.h>

const int16_t squared_difference_broadcast_w_s16_lhs_input_tensor[24] = {
    18484, -30140, -26860, -7454, 9511,   -16489, 4539, 18372,  -27852, -21773, 28919, -23539,
    23637, 27733,  21959,  25002, -29406, 31742,  3377, -21765, 18944,  -18754, 17416, -31141};
