// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.13.2).
// Interpreter from tflite_micro runtime version 0.dev20251103221221-gv1.3.0-45-gac157ac1-dirty.
#include "config_data.h"
#include "lhs_input_tensor.h"
#include "output.h"
#include "rhs_input_tensor.h"
