// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mean_axis_nhwc_s8_input_tensor[48] = {120, -58, 55,  -49,  -107, -80,  32,   -22, -40, -40, -97, 68,
                                                   -94, 95,  36,  -6,   -95,  77,   -121, 112, 64,  63,  125, -112,
                                                   -1,  -79, 94,  -121, 118,  -112, 37,   -72, -39, -89, 59,  127,
                                                   -45, -29, -84, -18,  -6,   -9,   67,   111, 124, 8,   -14, 118};
