// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t k7_1d_valid_37ch_127w_bias[37] = {
    -13548, -31095, -24094, 26436,  -10539, 13772, 15981,  5999,  24909, 17922, 3095,  7092,  1928,
    10768,  -2074,  -5243,  9082,   3379,   21929, -31072, 10027, 18390, 3172,  44007, 38014, 7807,
    30717,  1363,   -14712, -21520, -26439, 11909, 17904,  31234, 0,     25337, 21023};

const int32_t *const k7_1d_valid_37ch_127w_biases = k7_1d_valid_37ch_127w_bias;
