// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t add_ident_s8_lhs_input_tensor[24] = {32, -35, -60, -89, 40, 88, 0, 0, 4, 0, 0, 0,
                                                  7,  0,   0,   0,   0,  0,  0, 0, 0, 0, 0, 0};
