// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t resize_nn_half_pixel_s16_input_tensor[24] = {
    -10564, -29722, -11547, 6264, 23374, -26839, -26427, 19799,  12616, 23555, 6526,   -23223,
    27720,  22473,  -28754, 3191, -1580, 25449,  15072,  -25009, 15121, 7097,  -16851, 29559};
