// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int16_t maxpool_int16_output_ref[12] =
    {22375, 29401, 27919, 29772, 13719, 26309, 30359, 29291, 15066, 28654, 12790, 13091};
