// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t fc_conv_int8_1x1_kernel_input_tensor[20] = {99, 52,  33, 4,  13, -104, 43,  -86, -128, 22,
                                                         12, 106, 9,  89, 21, 127,  -22, 89,  27,   -39};
