// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t fc_conv_int8_1x1_kernel_output_multiplier[20] = {
    1148824649, 1133292476, 1109755474, 1117445585, 1077805560, 1109809367, 1125057714,
    1083243096, 2020087943, 1148811583, 2095501672, 1089464675, 1124095046, 2135514665,
    1145582051, 2069886705, 1123151908, 2125314488, 2084837547, 1125116030};

const int32_t *const fc_conv_int8_1x1_kernel_output_mult = fc_conv_int8_1x1_kernel_output_multiplier;
