// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t fc_conv_int8_1x1_kernel_output_shift[20] = {-9,  -9, -9, -9,  -9, -9,  -9, -9,  -10, -9,
                                                          -10, -9, -9, -10, -9, -10, -9, -10, -10, -9};
