// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t mean_axis_hw_s16_output[20] = {-708, 1416, 290,  -176, -777,  -95,   3977, 2740, 6891,  -88,
                                             4372, 725,  7960, 5004, -3315, -1295, 2318, 130,  -1018, 1877};
