// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.4).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t int16xint8xint32_1x1_ch32_bias[16] = {1005770,
                                                    2990466,
                                                    3165299,
                                                    3667342,
                                                    681588,
                                                    144829,
                                                    240222,
                                                    2096036,
                                                    2913007,
                                                    2208559,
                                                    1460043,
                                                    4295246,
                                                    3148685,
                                                    958399,
                                                    2014968,
                                                    1103194};

const int32_t *const int16xint8xint32_1x1_ch32_biases = int16xint8xint32_1x1_ch32_bias;
