// Generated by generate_test_data.py using tensorflow version 2.19.0 (Keras version 3.9.2).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once

#define DEQUANTIZE_S16_F32_BATCH_1 1
#define DEQUANTIZE_S16_F32_HEIGHT_1 1
#define DEQUANTIZE_S16_F32_WIDTH_1 8
#define DEQUANTIZE_S16_F32_CHANNEL_1 1
#define DEQUANTIZE_S16_F32_PAD SAME
#define DEQUANTIZE_S16_F32_INPUT_MIN -32768
#define DEQUANTIZE_S16_F32_INPUT_MAX 32767
#define DEQUANTIZE_S16_F32_QUANT_INPUT_SCALE_FLOAT32 2.8430791644495912e-05
#define DEQUANTIZE_S16_F32_QUANT_INPUT_ZERO_POINT_FLOAT32 0
#define DEQUANTIZE_S16_F32_QUANT_OUTPUT_SCALE_FLOAT32 0.0
#define DEQUANTIZE_S16_F32_QUANT_OUTPUT_ZERO_POINT_FLOAT32 0
#define DEQUANTIZE_S16_F32_OUTPUT_SHAPE                                                                                \
    {                                                                                                                  \
        1, 8,                                                                                                          \
    }
