// Generated by generate_test_data.py using tensorflow version 2.19.0 (Keras version 3.9.2).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const float dequantize_s16_f32_output[8] =
    {-0.63395, -0.655358, -0.199698, 0.770816, -0.524747, 0.541749, -0.146845, -0.789921};
