// Generated by generate_test_data.py using tensorflow version 2.19.0 (Keras version 3.9.2).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const float dequantize_s16_f32_output[8] =
    {0.653163, -0.0337231, -0.0701381, 0.649909, -0.917918, -0.690791, 0.359802, -0.0814087};
