// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t sub_scalar_neg_offset_s8_lhs_input_tensor[24] = {
    72, 35, 38, 63, -93, -106, -66, -92, 108, -38, 20, 115, -94, 92, -110, -115, -76, -89, 33, 39, 53, 90, -59, 102};
