// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define TILE_3D_S8_FORCE_NO_QUANTIZE true
#define TILE_3D_S8_INPUT_SHAPE                                                                                         \
    {                                                                                                                  \
        1, 2, 2,                                                                                                       \
    }
#define TILE_3D_S8_MULTIPLES                                                                                           \
    {                                                                                                                  \
        2, 1, 3,                                                                                                       \
    }
#define TILE_3D_S8_INPUT_VALUES                                                                                        \
    {                                                                                                                  \
        1, 2, 3, 4,                                                                                                    \
    }
#define TILE_3D_S8_RANK 3
#define TILE_3D_S8_INPUT_SIZE 4
#define TILE_3D_S8_OUTPUT_SIZE 24
