/*
 * SPDX-FileCopyrightText: Copyright 2010-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by conv_settings_flt.py using PyTorch version 2.13.0+cpu.
const float16_t conv_grouped_dilation_nhwc_f16_biases_data[12] = {(float16_t)0.0770874023f,
                                                                  (float16_t)-0.143066406f,
                                                                  (float16_t)0.334716797f,
                                                                  (float16_t)0.465087891f,
                                                                  (float16_t)-0.486572266f,
                                                                  (float16_t)0.0582580566f,
                                                                  (float16_t)-0.0639038086f,
                                                                  (float16_t)0.21875f,
                                                                  (float16_t)0.220703125f,
                                                                  (float16_t)-0.383056641f,
                                                                  (float16_t)0.00540161133f,
                                                                  (float16_t)-0.447998047f};
