// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t small_k3_1d_valid_12ch_16h_output_multiplier[12] = {1339850476,
                                                                  1645303531,
                                                                  2064282206,
                                                                  1153616171,
                                                                  1301804681,
                                                                  1240450509,
                                                                  1128600145,
                                                                  1217527949,
                                                                  1171389919,
                                                                  1582698598,
                                                                  2135992183,
                                                                  1142205173};

const int32_t *const small_k3_1d_valid_12ch_16h_output_mult = small_k3_1d_valid_12ch_16h_output_multiplier;
