// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t small_k3_1d_valid_12ch_16h_output_shift[12] = {-8, -9, -9, -8, -9, -8, -8, -8, -8, -9, -9, -8};
