// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t small_k3_1d_valid_12ch_16h_weights[36] = {125,  64,   -127, 3,   83,  -72,  127, -37, 127,  127, 106, -127,
                                                       -27,  -127, 124,  127, 127, -127, 127, 127, -100, -97, -50, 21,
                                                       -127, 115,  8,    72,  -51, 7,    90,  102, -73,  123, 127, -69};
