// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mean_axis_n_s8_input_tensor[48] = {91,   -10, 114, -119, -105, -81,  -113, -83, 20,  24,  59,  -54,
                                                -112, -29, 22,  81,   25,   117,  -102, 5,   96,  -70, 36,  30,
                                                -4,   -36, 85,  -25,  -117, 82,   -66,  -65, 37,  -72, -54, 110,
                                                -66,  -26, -43, -27,  -37,  -118, -34,  41,  -25, -51, 22,  24};
