// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mean_axis_n_s8_input_tensor[48] = {-91, -68, 111, 84,   90,  16,  -79,  -55, 104, -90, 31,  -22,
                                                -61, -19, 95,  -21,  -55, 69,  85,   21,  66,  -29, -21, -50,
                                                1,   -18, 103, -9,   -39, -87, 15,   51,  62,  -88, 40,  -68,
                                                40,  -21, -84, -117, -44, -25, -104, -31, 32,  12,  -32, 6};
