// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mean_axis_n_s8_output[24] = {64,  -11, 126, -65, -109, 16, -85, -68, 47, -12, 18, 46,
                                          -84, -16, 3,   45,  8,    15, -61, 41,  55, -53, 47, 45};
