// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mean_axis_n_s8_output[24] = {-42, -39, 117, 44,  32,  -32, -28, 3, 92, -87, 42,  -42,
                                          -6,  -16, 11,  -67, -46, 28,  -5,  0, 56, -4,  -22, -18};
