// Generated by generate_test_data.py using tensorflow version 2.19.0 (Keras version 3.9.2).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const float quantize_f32_s8_input_tensor_1[8] =
    {-0.0792583, 0.346861, -0.959532, 0.679566, 0.439768, 0.939518, 0.92541, -0.915522};
