// Generated by generate_test_data.py using tensorflow version 2.19.0 (Keras version 3.9.2).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const float quantize_f32_s8_input_tensor_1[8] =
    {-0.208953, -0.973803, -0.240544, -0.128609, 0.185889, 0.669712, 0.525757, 0.853965};
