// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t space_to_batch_nd_small_pad_s16_input_tensor[6] = {48, -77, -10, 67, 90, -55};
