// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t int16xint8xint32_2_output_mult[9] =
    {1101453312, 1099128192, 1100749440, 1101393664, 1101453568, 1100809216, 1101164288, 1101343360, 1101227136};
