// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_input_tensor[82] = {
    32, -92, -108, -98,  -40, 83,  68,   -53, 126, 73,  12,  45,  -43, 3,    -103, -63, 77,  105, 103, 116, 87,
    38, 23,  -75,  -107, 126, 51,  78,   57,  -22, -61, 86,  -14, 32,  112,  -88,  -74, 89,  -84, 116, 122, 112,
    -1, -90, 70,   93,   -39, -81, -100, -96, -30, -17, -91, -72, 46,  79,   -35,  -72, -78, 82,  98,  6,   72,
    18, -17, 67,   -3,   10,  -87, 72,   124, -29, -65, 54,  42,  42,  -118, -44,  33,  122, 0,   13};
