// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t maxpooling_6_output_ref[34] = {67, 88, 26,  91, 32, 35, 124, 70, 76, 5,  106, -27, -5, 60, 95, -24, 123,
                                            91, 83, 120, 26, 64, 61, 124, 61, 76, 57, 85,  12,  -5, 55, 95, 26,  22};
