// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t space_to_batch_nd_basic_2x2_s8_input_tensor[72] = {
    122, -109, -45, 90,   92,  51,  88, -82,  31,  103,  82,  49,  -74, 7,   95,  -43,  -3,  79,
    88,  27,   79,  -110, -30, 101, 33, 125,  58,  26,   -96, 93,  18,  7,   2,   -108, 72,  54,
    -46, -48,  -98, -4,   75,  4,   51, -125, 32,  -115, -23, -37, -15, -80, 110, -32,  -55, -30,
    -92, -78,  22,  127,  6,   34,  71, 73,   -74, 75,   -44, 26,  -1,  -8,  65,  -40,  33,  47};
