// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t space_to_batch_nd_basic_2x2_s8_output[72] = {
    122, -109, -45, 88,   -82, 31,  33,  125, 58,  18,   7,    2,   -15, -80, 110, -92, -78, 22,
    90,  92,   51,  103,  82,  49,  26,  -96, 93,  -108, 72,   54,  -32, -55, -30, 127, 6,   34,
    -74, 7,    95,  88,   27,  79,  -46, -48, -98, 51,   -125, 32,  71,  73,  -74, -1,  -8,  65,
    -43, -3,   79,  -110, -30, 101, -4,  75,  4,   -115, -23,  -37, 75,  -44, 26,  -40, 33,  47};
