// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define BATCH_TO_SPACE_ND_NSQUARE_CROPS_S8_IN_DIM                                                                      \
    {                                                                                                                  \
        6, 3, 3, 1,                                                                                                    \
    }
#define BATCH_TO_SPACE_ND_NSQUARE_CROPS_S8_BLOCK_SHAPE                                                                 \
    {                                                                                                                  \
        2, 3,                                                                                                          \
    }
#define BATCH_TO_SPACE_ND_NSQUARE_CROPS_S8_CROPS                                                                       \
    {                                                                                                                  \
        1, 0, 2, 0,                                                                                                    \
    }
#define BATCH_TO_SPACE_ND_NSQUARE_CROPS_S8_OUT_DIM                                                                     \
    {                                                                                                                  \
        1, 3, 9, 1,                                                                                                    \
    }
#define BATCH_TO_SPACE_ND_NSQUARE_CROPS_S8_CROP_NHWC4                                                                  \
    {                                                                                                                  \
        1, 0, 2, 0,                                                                                                    \
    }
#define BATCH_TO_SPACE_ND_NSQUARE_CROPS_S8_INPUT_SIZE 54
#define BATCH_TO_SPACE_ND_NSQUARE_CROPS_S8_OUTPUT_SIZE 27
#define BATCH_TO_SPACE_ND_NSQUARE_CROPS_S8_INPUT_OFFSET 128
#define BATCH_TO_SPACE_ND_NSQUARE_CROPS_S8_OUTPUT_OFFSET -128
