// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t batch_to_space_nd_nsquare_crops_s8_input_tensor[54] = {
    -128, -67, -16, -74, -29,  83,  104, -81, -45, -117, 86,  33, 9,   62,  74,   -14, -97, -13,
    19,   -65, -47, 101, -31,  -70, -57, 91,  37,  118,  109, 86, 7,   -57, -122, -10, 96,  100,
    0,    37,  -97, 76,  -126, 106, 106, -37, 49,  -32,  -16, 60, -33, 53,  123,  -26, -57, 0};
