// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t batch_to_space_nd_nsquare_crops_s8_output[27] = {118, 0,  -32, 109, 37,   -16, 86,   -97, 60,
                                                              -74, 9,  101, -29, 62,   -31, 83,   74,  -70,
                                                              7,   76, -33, -57, -126, 53,  -122, 106, 123};
