// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t add_broadcast_c_s16_lhs_input_tensor[24] = {13040, -27878, 29609, 0,     -27008, -29754, 29609,  0,
                                                          8179,  26372,  8072,  18403, 27712,  -27878, 29609,  0,
                                                          272,   8649,   29610, 0,     29188,  -7614,  -13986, 24325};
