// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t add_broadcast_c_s16_output[24] = {-2999, -23526, 5313,  -9541, -12383, -13760, 16020,  1166,
                                                3093,  12220,  3039,  8222,  20714,  -7174,  21666,  6812,
                                                14085, 18288,  28803, 13949, 651,    -17812, -21008, -1789};

const int16_t *const add_broadcast_c_s16_output_ref = add_broadcast_c_s16_output;
