// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t mean_axis_c_s16_input_tensor[16] =
    {3428, -18062, -28601, 427, 24560, -19954, 4045, -5181, 9012, -17971, -1689, 13118, 15287, 9615, -7064, -9350};
