// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t reduce_min_axis_n_s8_input_tensor[48] = {39,   -12, -22,  64,   -26, -11, -7,  91,   56,  -15, -91,  -15,
                                                      -127, -63, -59,  -127, 125, 5,   98,  -104, 83,  123, -112, 51,
                                                      -87,  32,  7,    -100, 52,  103, -12, -52,  -96, -49, 97,   -98,
                                                      -52,  56,  -110, 108,  84,  112, -34, 35,   -4,  28,  101,  18};
