// Generated by test_settings.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t int16xint8_group2_output_mult[8] =
    {1546077795, 1619252107, 1767102021, 1788127235, 1799166015, 1500426944, 1779287959, 1804936225};
