// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t int16xint8_group2_output_mult[8] =
    {1915229440, 1920774400, 2039487360, 1933416576, 2038606080, 1952954624, 1854388480, 2003545344};
