// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define REVERSE_SEQUENCE_FULL_AND_SINGLE_S16_FORCE_NO_QUANTIZE true
#define REVERSE_SEQUENCE_FULL_AND_SINGLE_S16_SHAPE                                                                     \
    {                                                                                                                  \
        3, 4,                                                                                                          \
    }
#define REVERSE_SEQUENCE_FULL_AND_SINGLE_S16_SEQ_LENGTHS                                                               \
    {                                                                                                                  \
        4, 1, 2,                                                                                                       \
    }
#define REVERSE_SEQUENCE_FULL_AND_SINGLE_S16_SEQ_DIM 1
#define REVERSE_SEQUENCE_FULL_AND_SINGLE_S16_BATCH_DIM 0
#define REVERSE_SEQUENCE_FULL_AND_SINGLE_S16_INPUT_VALUES                                                              \
    {                                                                                                                  \
        100, 200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100, 1200,                                                 \
    }
#define REVERSE_SEQUENCE_FULL_AND_SINGLE_S16_RANK 2
#define REVERSE_SEQUENCE_FULL_AND_SINGLE_S16_SIZE 12
