// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t reverse_sequence_full_and_single_s16_output[12] =
    {400, 300, 200, 100, 500, 600, 700, 800, 1000, 900, 1100, 1200};
