// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t sub_broadcast_hc_s8_output[24] = {-43, -43, -43, -43, 11, -34, 13, 13, 7,  16, 8,  8,
                                               24,  24,  24,  24,  55, 9,   56, 56, 60, 68, 60, 60};

const int8_t *const sub_broadcast_hc_s8_output_ref = sub_broadcast_hc_s8_output;
