// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t add_broadcast_w_s16_output[24] = {27131, 17283, 27379, 13556, 27131, 17283, 27379, 13556,
                                                13082, 12905, 12513, 13556, 12680, 13039, 14438, 0,
                                                12816, 28591, 26427, 0,     26200, 25683, 27473, 14434};

const int16_t *const add_broadcast_w_s16_output_ref = add_broadcast_w_s16_output;
