// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t add_broadcast_w_s16_rhs_input_tensor[8] = {25938, 25697, 24918, 26994, 25185, 25964, 28751, 0};
