// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define ARGMAX_H_S8_AXIS 1
#define ARGMAX_H_S8_LHS_N 1
#define ARGMAX_H_S8_LHS_H 3
#define ARGMAX_H_S8_LHS_W 2
#define ARGMAX_H_S8_LHS_C 1
#define ARGMAX_H_S8_MODE argmax
#define ARGMAX_H_S8_DST_SIZE 2
#define ARGMAX_H_S8_OUTPUT_DIMS                                                                                        \
    {                                                                                                                  \
        1, 2, 1,                                                                                                       \
    }
