// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t reverse_sequence_axis0_s8_output[12] = {10, 5, 3, 7, 2, 6, 4, 8, 9, 1, 11, 12};
