// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define GATHER_BATCH_DIMS_S8_INPUT_DIM                                                                                 \
    {                                                                                                                  \
        2, 1, 1, 4,                                                                                                    \
    }
#define GATHER_BATCH_DIMS_S8_INPUT_RANK 4
#define GATHER_BATCH_DIMS_S8_INDICES_DIM                                                                               \
    {                                                                                                                  \
        2, 2, 1, 1,                                                                                                    \
    }
#define GATHER_BATCH_DIMS_S8_INDICES_RANK 2
#define GATHER_BATCH_DIMS_S8_INDICES_VALUES                                                                            \
    {                                                                                                                  \
        3, 1, 2, 0,                                                                                                    \
    }
#define GATHER_BATCH_DIMS_S8_AXIS 3
#define GATHER_BATCH_DIMS_S8_BATCH_DIMS 1
#define GATHER_BATCH_DIMS_S8_INPUT_N 2
#define GATHER_BATCH_DIMS_S8_INPUT_H 1
#define GATHER_BATCH_DIMS_S8_INPUT_W 1
#define GATHER_BATCH_DIMS_S8_INPUT_C 4
#define GATHER_BATCH_DIMS_S8_INDICES_N 2
#define GATHER_BATCH_DIMS_S8_INDICES_H 2
#define GATHER_BATCH_DIMS_S8_INDICES_W 1
#define GATHER_BATCH_DIMS_S8_INDICES_C 1
#define GATHER_BATCH_DIMS_S8_COORDS_RANK 2
#define GATHER_BATCH_DIMS_S8_INDICES_LENGTH 4
#define GATHER_BATCH_DIMS_S8_OUTPUT_N 2
#define GATHER_BATCH_DIMS_S8_OUTPUT_H 1
#define GATHER_BATCH_DIMS_S8_OUTPUT_W 1
#define GATHER_BATCH_DIMS_S8_OUTPUT_C 2
#define GATHER_BATCH_DIMS_S8_OUTPUT_SIZE 4
