// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t gather_batch_dims_s8_input_tensor[8] = {111, 43, -7, -80, -22, 51, -85, -23};
