// Generated by generate_test_data.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int64_t int16xint8_bias[4] = {920235, -134899, 2938918, 2179906};

const int64_t *const int16xint8_biases = int16xint8_bias;
