// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int16_t int16xint8_output_ref[40] = {-1191, -1278,  -22241, 3362,   4269,   13438,  15222, -3305, -4277,  -4016,
                                           1912,  -32768, 8443,   7180,   19026,  -7440,  31279, 1566,  1736,   -18946,
                                           10024, -2777,  26495,  -14470, -14463, -21730, 5247,  -7010, -566,   -2269,
                                           -3553, -18947, -16849, 3274,   -12286, -19608, -838,  1807,  -14516, 14054};
