// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t sub_broadcast_w_s8_lhs_input_tensor[24] = {64, 30, 18, 50, 113, 120, 0, 0, 112, 64, 54, 33,
                                                        3,  91, 0,  0,  0,   0,   0, 0, 0,   0,  0,  0};
