// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once

#define MEAN_AXIS_WC_S8_IN_DIM                                                                                         \
    {                                                                                                                  \
        4, 5, 7, 4,                                                                                                    \
    }
#define MEAN_AXIS_WC_S8_AXIS                                                                                           \
    {                                                                                                                  \
        2, 3,                                                                                                          \
    }
#define MEAN_AXIS_WC_S8_KEEP_DIMS true
#define MEAN_AXIS_WC_S8_ASYMMETRIC_QUANTIZE_INPUTS 0
#define MEAN_AXIS_WC_S8_OUT_DIM                                                                                        \
    {                                                                                                                  \
        4, 5, 1, 1,                                                                                                    \
    }
#define MEAN_AXIS_WC_S8_AXIS_DIM                                                                                       \
    {                                                                                                                  \
        0, 0, 1, 1,                                                                                                    \
    }
#define MEAN_AXIS_WC_S8_AXIS_MASK 3
#define MEAN_AXIS_WC_S8_INPUT_SIZE 560
#define MEAN_AXIS_WC_S8_OUTPUT_SIZE 20
#define MEAN_AXIS_WC_S8_INPUT_OFFSET 128
#define MEAN_AXIS_WC_S8_OUTPUT_OFFSET -128
#define MEAN_AXIS_WC_S8_OUTPUT_MULTIPLIER 1912478909
#define MEAN_AXIS_WC_S8_OUTPUT_SHIFT -4
#define MEAN_AXIS_WC_S8_REDUCTION_SIZE 28
