// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t k3_1d_valid_40ch_29w_bias[40] = {
    -43763, 7571,  31754, 14248, 58598,  -32989, -22025, -15628, -63701,  2755,   20005,  5994,   -25683, -3216,
    -30588, -3814, 11790, 44954, 8418,   -24197, 9812,   7776,   -16677,  -45912, -13185, -29895, 32226,  -28584,
    27010,  14783, 13084, -9834, -26805, -35130, 24109,  -30140, -176096, 29847,  725,    -26811};

const int32_t *const k3_1d_valid_40ch_29w_biases = k3_1d_valid_40ch_29w_bias;
