// Generated by test data script for arm_sqrt_s16 unit tests.
#pragma once
#include <stdint.h>

const int16_t sqrt_tail_odd_s16_input_tensor[19] = {
    2924, 25360, 21448, 14381, 14189, 28134, 2816, 22851,
    11408, 3086, 17251, 31969, 24109, 24941, 23510, 25757,
    118, 112, 127};
