// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t reduce_max_axis_n_s8_output[24] = {-23, 47, 90,  -38, 93, 48, 78, 62,  -28, 72,  91,  -24,
                                                -32, 28, -34, 85,  52, 69, 11, -37, 98,  105, 126, 118};
