// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t reduce_max_axis_c_s8_input_tensor[16] =
    {-23, -1, -48, 75, -6, 84, 78, -98, -73, -68, 63, 83, -59, 45, 81, -113};
