// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t concat_axis_w_two_inputs_s32_output[18] = {1776700558,
                                                         -1605884950,
                                                         -317270138,
                                                         -2006564342,
                                                         -118540125,
                                                         -344130842,
                                                         -475627282,
                                                         -1261351687,
                                                         -1865387402,
                                                         52912362,
                                                         -5469455,
                                                         -1073563876,
                                                         1935934544,
                                                         1591655421,
                                                         190646814,
                                                         -941661183,
                                                         -1266101080,
                                                         2070086115};
