// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#include "config_data.h"
#include "input_tensor_1.h"
#include "input_tensor_2.h"
#include "output.h"
