/*
 * SPDX-FileCopyrightText: 2025 Ambiq
 *
 * SPDX-License-Identifier: LicenseRef-Ambiq-Apollo-SDK
 *
 * Licensed under the Ambiq Apollo SDK License.
 * See LICENSE (root) or LICENSES/LicenseRef-Ambiq-Apollo-SDK.txt for the full text.
 */

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../test_arm_hard_swish_s8.c"
#include "unity.h"

#ifdef USING_FVP_CORSTONE_300
extern void uart_init(void);
#endif

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void setUp(void)
{ /* This is run before EACH TEST */
#ifdef USING_FVP_CORSTONE_300
    uart_init();
#endif
}

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void tearDown(void) {}

/* Unity-visible test entry points */
/* Unity test entry points (names starting with test_) */
void test_hard_swish_basic(void)            { hard_swish_basic_arm_hard_swish_s8(); }
void test_hard_swish_sweep_edges(void)      { hard_swish_sweep_edges_arm_hard_swish_s8(); }
void test_hard_swish_plateau_edges(void)    { hard_swish_plateau_edges_arm_hard_swish_s8(); }
void test_hard_swish_dense_mixture(void)    { hard_swish_dense_mixture_arm_hard_swish_s8(); }
void test_hard_swish_adversarial_step(void) { hard_swish_adversarial_step_arm_hard_swish_s8(); }
void test_hard_swish_batched_wide(void)     { hard_swish_batched_wide_arm_hard_swish_s8(); }
