// Generated by test data script for arm_sqrt_s16 unit tests.
#pragma once

#define SQRT_SMALL_TENSOR_S16_BATCH_SIZE 1
#define SQRT_SMALL_TENSOR_S16_HEIGHT_1 2
#define SQRT_SMALL_TENSOR_S16_WIDTH_1 3
#define SQRT_SMALL_TENSOR_S16_CHANNEL_1 4
#define SQRT_SMALL_TENSOR_S16_IN_DIM                                                                                   \
    {                                                                                                                  \
        1, 2, 3, 4,                                                                                                    \
    }
#define SQRT_SMALL_TENSOR_S16_OUTPUT_LEN 24
#define SQRT_SMALL_TENSOR_S16_INPUT_SCALE 0.00028f
#define SQRT_SMALL_TENSOR_S16_INPUT_ZERO_POINT 0
#define SQRT_SMALL_TENSOR_S16_OUTPUT_SCALE 0.00029f
#define SQRT_SMALL_TENSOR_S16_OUTPUT_ZERO_POINT 0
