// Generated by test data script for arm_sqrt_s16 unit tests.
#pragma once
#include <stdint.h>

const int16_t sqrt_small_tensor_s16_output[24] = {
    3120, 9189, 8450, 6920, 6873, 9679, 3062, 8723,
    4688, 3205, 7579, 10317, 8959, 9113, 8847, 9260,
    7483, 3738, 9571, 7010, 7388, 6360, 4462, 10055};
