// Generated by generate_rsqrt_s16_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
static const int16_t rsqrt_s16_negative_input[4] = {
    -1, 1, 2, 3,
};
