// Generated by generate_rsqrt_s16_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#include "config_data.h"
#include "input_tensor.h"
#include "offset_input_tensor.h"
#include "negative_input_tensor.h"
#include "rescale_input_tensor.h"
#include "universal_lut_data.h"
#include "per_op_lut_data.h"
#include "universal_output.h"
#include "per_op_output.h"
#include "offset_per_op_output.h"
#include "rescaled_universal_output.h"
