// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t add_scalar_neg_offset_s8_lhs_input_tensor[24] = {
    120, -4, 63, -105, -98, 7, 7, -15, -14, -44, -97, 57, -95, 42, -29, 58, -70, 49, -117, 4, -56, -82, -70, -95};
