// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t add_scalar_neg_offset_s8_output[24] = {62,  -1, 33,  -53, -50, 4,  4,   -7, -7,  -22, -49, 30,
                                                    -48, 22, -14, 30,  -35, 26, -60, 3,  -28, -42, -35, -48};

const int8_t *const add_scalar_neg_offset_s8_output_ref = add_scalar_neg_offset_s8_output;
