// Generated by test_settings.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t int16xint8_group_depthwise_3x3_output_mult[16] = {1296305371,
                                                                1291417365,
                                                                1203680396,
                                                                1289614162,
                                                                2117226884,
                                                                1179890753,
                                                                1205837212,
                                                                1158072912,
                                                                1278971526,
                                                                1282903624,
                                                                1259975158,
                                                                2022140110,
                                                                1191934652,
                                                                1259262637,
                                                                1098279594,
                                                                1192036671};
