// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t reduce_max_axis_h_s8_input_tensor[16] =
    {54, 37, -55, 31, -35, -33, -90, 17, -33, -46, -50, 39, 121, -24, -9, 69};
