// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define DYNAMIC_UPDATE_SLICE_2D_S8_FORCE_NO_QUANTIZE true
#define DYNAMIC_UPDATE_SLICE_2D_S8_OPERAND_SHAPE                                                                       \
    {                                                                                                                  \
        3, 4,                                                                                                          \
    }
#define DYNAMIC_UPDATE_SLICE_2D_S8_UPDATE_SHAPE                                                                        \
    {                                                                                                                  \
        2, 2,                                                                                                          \
    }
#define DYNAMIC_UPDATE_SLICE_2D_S8_START_INDICES                                                                       \
    {                                                                                                                  \
        1, 1,                                                                                                          \
    }
#define DYNAMIC_UPDATE_SLICE_2D_S8_OPERAND_VALUES                                                                      \
    {                                                                                                                  \
        1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,                                                                         \
    }
#define DYNAMIC_UPDATE_SLICE_2D_S8_UPDATE_VALUES                                                                       \
    {                                                                                                                  \
        20, 21, 22, 23,                                                                                                \
    }
#define DYNAMIC_UPDATE_SLICE_2D_S8_RANK 2
#define DYNAMIC_UPDATE_SLICE_2D_S8_OPERAND_SIZE 12
#define DYNAMIC_UPDATE_SLICE_2D_S8_UPDATE_SIZE 4
#define DYNAMIC_UPDATE_SLICE_2D_S8_OPERAND_STRIDES                                                                     \
    {                                                                                                                  \
        4, 1,                                                                                                          \
    }
