/*
 * SPDX-FileCopyrightText: Copyright 2010-2024 Arm Limited and/or its affiliates <open-source-office@arm.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../test_arm_depthwise_conv_s8_1d_valid.c"
#include "unity.h"

#ifdef USING_FVP_CORSTONE_300
extern void uart_init(void);
#endif

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void setUp(void)
{ /* This is run before EACH TEST */
#ifdef USING_FVP_CORSTONE_300
    uart_init();
#endif
}

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void tearDown(void) {}

void test_basic_arm_depthwise_conv_s8_1d_valid_opt(void) { 
    basic_arm_depthwise_conv_s8_1d_valid_opt(); 
}
void test_k1_1d_valid_40ch_31w_arm_depthwise_conv_s8_opt_1d_valid_wrapper(void) 
{ 
    k1_1d_valid_40ch_31w_arm_depthwise_conv_s8_opt_1d_valid_wrapper(); 
}

void test_k3_1d_valid_40ch_29w_arm_depthwise_conv_s8_opt_1d_valid_wrapper(void) 
{ 
    k3_1d_valid_40ch_29w_arm_depthwise_conv_s8_opt_1d_valid_wrapper(); 
}

void test_k5_1d_valid_40ch_64w_arm_depthwise_conv_s8_opt_1d_valid_wrapper(void) 
{ 
    k5_1d_valid_40ch_64w_arm_depthwise_conv_s8_opt_1d_valid_wrapper(); 
}

void test_k7_1d_valid_37ch_127w_arm_depthwise_conv_s8_opt_1d_valid_wrapper(void) 
{ 
    k7_1d_valid_37ch_127w_arm_depthwise_conv_s8_opt_1d_valid_wrapper(); 
}

void test_edge_equal_k_1d_valid_33ch_3w_arm_depthwise_conv_s8_opt_1d_valid_wrapper(void) 
{ 
    edge_equal_k_1d_valid_33ch_3w_arm_depthwise_conv_s8_opt_1d_valid_wrapper(); 
}

void test_wide_k3_1d_valid_35ch_255w_arm_depthwise_conv_s8_opt_1d_valid_wrapper(void) 
{ 
    wide_k3_1d_valid_35ch_255w_arm_depthwise_conv_s8_opt_1d_valid_wrapper(); 
}
