// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t maxpooling_4_input[40] = {-86, 77,  -24, -45, 39,  20,  35,  102, 52,  -87, 109, 54, -94, -127,
                                       124, -85, 8,   22,  -27, -17, -63, 21,  -31, 42,  -9,  39, 70,  8,
                                       -12, -33, 92,  -79, -18, 118, 51,  -22, -43, -97, 53,  122};
