// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define GATHER_ND_DEPTH_S8_PARAMS_DIM                                                                                  \
    {                                                                                                                  \
        1, 2, 2, 3,                                                                                                    \
    }
#define GATHER_ND_DEPTH_S8_PARAMS_RANK 4
#define GATHER_ND_DEPTH_S8_INDICES_DIM                                                                                 \
    {                                                                                                                  \
        2, 1, 3, 1,                                                                                                    \
    }
#define GATHER_ND_DEPTH_S8_INDICES_RANK 3
#define GATHER_ND_DEPTH_S8_INDICES_LAST_DIM 3
#define GATHER_ND_DEPTH_S8_INDICES_VALUES                                                                              \
    {                                                                                                                  \
        0, 0, 0, 0, 1, 1,                                                                                              \
    }
#define GATHER_ND_DEPTH_S8_BATCH_DIMS 0
#define GATHER_ND_DEPTH_S8_PARAMS_N 1
#define GATHER_ND_DEPTH_S8_PARAMS_H 2
#define GATHER_ND_DEPTH_S8_PARAMS_W 2
#define GATHER_ND_DEPTH_S8_PARAMS_C 3
#define GATHER_ND_DEPTH_S8_INDICES_N 2
#define GATHER_ND_DEPTH_S8_INDICES_H 1
#define GATHER_ND_DEPTH_S8_INDICES_W 3
#define GATHER_ND_DEPTH_S8_INDICES_C 1
#define GATHER_ND_DEPTH_S8_INDICES_LENGTH 6
#define GATHER_ND_DEPTH_S8_OUTPUT_RANK 3
#define GATHER_ND_DEPTH_S8_OUTPUT_N 2
#define GATHER_ND_DEPTH_S8_OUTPUT_H 1
#define GATHER_ND_DEPTH_S8_OUTPUT_W 3
#define GATHER_ND_DEPTH_S8_OUTPUT_C 1
#define GATHER_ND_DEPTH_S8_OUTPUT_SIZE 6
