// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t hard_swish_plateau_edges_s16_output[64] = {
    -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128,
    127,  127,  127,  127,  127,  127,  127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
    -14,  -16,  -19,  -14,  -17,  -14,  -19,  -19,  -15,  -20,  -17,  -13,  -13,  -17,  -14,  -18,
    -19,  -31,  -26,  -25,  -6,   -29,  -29,  -27,  -7,   -6,   -31,  -29,  -2,   1,    -13,  -19};
