// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t add_scalar_s16_lhs_input_tensor[24] = {0,      0,     0,      0,    0,    0,     0,     0, 0,   0, 0, 0,
                                                     -23576, 15978, -20757, 6198, 4930, 30998, 23879, 0, 289, 0, 0, 0};
