// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t add_scalar_s16_output[24] = {0,      0,    0,      0,    0,    0,     0,     0, 0,   0, 0, 0,
                                           -11879, 8051, -10459, 3123, 2484, 15619, 12032, 0, 146, 0, 0, 0};

const int16_t *const add_scalar_s16_output_ref = add_scalar_s16_output;
