// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t maximum_broadcast_ch_int16_input_tensor_1[16] =
    {-15046, 5380, -23421, -12658, 4287, 12072, -13620, -12256, 27092, -14280, 7773, -13418, 29006, 11415, 3872, 8148};
