// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t sub_scalar_s16_lhs_input_tensor[24] = {0,     0,     0,      0,    0,     0,     0,     0, 0,   0, 0, 0,
                                                     28662, 15979, -20757, 6198, -2200, 20903, 22757, 0, 321, 0, 0, 0};
