// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t sub_scalar_s16_output[24] = {31660, 31660, 31660, 31660, 31660, 31660, 31660, 31660,
                                           31660, 31660, 31660, 31660, 32767, 32767, 10846, 32767,
                                           29454, 32767, 32767, 31660, 31982, 31660, 31660, 31660};

const int16_t *const sub_scalar_s16_output_ref = sub_scalar_s16_output;
