// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#include "config_data.h"
#include "lhs_input_tensor.h"
#include "lhs_transposed_tensor.h"
#include "output.h"
#include "rhs_input_tensor.h"
#include "rhs_transposed_tensor.h"
