// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t k1_1d_valid_40ch_31w_output_shift[40] = {
    -8, -8,  -12, -9,  -8,  -9, -11, -9, -9,  -9, -10, -10, -12, -9,  -9,  -8,  -8, -9, -16, -11,
    -9, -12, -9,  -10, -10, -8, -11, -8, -12, -8, -8,  -13, -9,  -10, -10, -10, -9, -9, -8,  -11};
