// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t hard_swish_adversarial_step_input_tensor[128] = {
    -3, 0,  3,  -4, -5, -5, -3, -4, -5, -3, -5, -6, -6, -6, -3, -3, -6, -3, -3, -6, -6, -3, -3, -6, -4, -4,
    -3, -4, -4, -4, -3, -4, -4, -6, -5, -3, -5, -3, -6, -4, -3, -4, -6, -3, -5, -5, -6, -5, -4, -3, -3, -5,
    -4, -5, -3, -6, -6, -3, -4, -3, -3, -6, -3, -5, 3,  2,  4,  4,  4,  4,  4,  2,  3,  4,  6,  2,  4,  6,
    5,  6,  3,  3,  3,  2,  5,  6,  6,  2,  4,  5,  6,  2,  3,  4,  5,  4,  4,  2,  2,  3,  4,  5,  2,  3,
    6,  2,  5,  2,  2,  2,  5,  4,  4,  4,  2,  2,  3,  4,  6,  5,  2,  4,  5,  2,  2,  6,  2,  5};
