/*
 * SPDX-FileCopyrightText: 2025 Ambiq
 *
 * SPDX-License-Identifier: LicenseRef-Ambiq-Apollo-SDK
 *
 * Licensed under the Ambiq Apollo SDK License.
 * See LICENSE (root) or LICENSES/LicenseRef-Ambiq-Apollo-SDK.txt for the full text.
 */

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../test_arm_space_to_batch_nd_s8.c"
#include "unity.h"

#ifdef USING_FVP_CORSTONE_300
extern void uart_init(void);
#endif

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void setUp(void)
{ /* This is run before EACH TEST */
#ifdef USING_FVP_CORSTONE_300
    uart_init();
#endif
}

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void tearDown(void) {}

/* Unity-visible test entry points */
/* Unity test entry points (names starting with test_) */
void test_space_to_batch_nd_basic_2x2_s8(void)            { space_to_batch_nd_basic_2x2_s8_arm_space_to_batch_nd_s8(); }
void test_space_to_batch_nd_nsquare_pad_s8(void)          { space_to_batch_nd_nsquare_pad_s8_arm_space_to_batch_nd_s8(); }
void test_space_to_batch_nd_batch_s8(void)                { space_to_batch_nd_batch_s8_arm_space_to_batch_nd_s8(); }
void test_space_to_batch_nd_both_pad_s8(void)             { space_to_batch_nd_both_pad_s8_arm_space_to_batch_nd_s8(); }
void test_space_to_batch_nd_small_pad_s8(void)            { space_to_batch_nd_small_pad_s8_arm_space_to_batch_nd_s8(); }
void test_space_to_batch_nd_bs1_identity_pad_s8(void)     { space_to_batch_nd_bs1_identity_pad_s8_arm_space_to_batch_nd_s8(); }
