// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.4).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define MEAN_AXIS_H_MIXED_S16_IN_DIM                                                                                   \
    {                                                                                                                  \
        2,                                                                                                             \
        2,                                                                                                             \
        3,                                                                                                             \
        4,                                                                                                             \
    }
#define MEAN_AXIS_H_MIXED_S16_AXIS                                                                                     \
    {                                                                                                                  \
        1,                                                                                                             \
    }
#define MEAN_AXIS_H_MIXED_S16_KEEP_DIMS true
#define MEAN_AXIS_H_MIXED_S16_ASYMMETRIC_QUANTIZE_INPUTS 0
#define MEAN_AXIS_H_MIXED_S16_OUT_DIM                                                                                  \
    {                                                                                                                  \
        2,                                                                                                             \
        1,                                                                                                             \
        3,                                                                                                             \
        4,                                                                                                             \
    }
#define MEAN_AXIS_H_MIXED_S16_AXIS_DIM                                                                                 \
    {                                                                                                                  \
        0,                                                                                                             \
        1,                                                                                                             \
        0,                                                                                                             \
        0,                                                                                                             \
    }
#define MEAN_AXIS_H_MIXED_S16_AXIS_MASK 4
#define MEAN_AXIS_H_MIXED_S16_INPUT_SIZE 48
#define MEAN_AXIS_H_MIXED_S16_OUTPUT_SIZE 24
#define MEAN_AXIS_H_MIXED_S16_INPUT_OFFSET 0
#define MEAN_AXIS_H_MIXED_S16_OUTPUT_OFFSET 0
#define MEAN_AXIS_H_MIXED_S16_OUTPUT_MULTIPLIER 1078443696
#define MEAN_AXIS_H_MIXED_S16_OUTPUT_SHIFT 0
#define MEAN_AXIS_H_MIXED_S16_REDUCTION_SIZE 2
