// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.4).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t mean_axis_h_mixed_s16_input_tensor[48] = {
    10560,  -8086,  -14225, 6429,   27158,  24390,  -1789,  -6652,  15493,  -536,   31011,  18370,
    -13564, 28476,  -26679, 24055,  -4969,  -22866, 23144,  -15841, -28093, -24253, 31750,  7947,
    26841,  24972,  1924,   -17071, -25643, -26511, 29583,  3919,   29523,  14847,  -3412,  -28994,
    22955,  -19603, 20168,  -11048, 23231,  -16794, -19149, -7369,  22176,  22475,  -19240, 30337};
