// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t grouped_conv_3_input[24] = {-28, -48, -66, 80,   -70, 118, 16,  26,  -34, -82, -27, 85,
                                         45,  -43, -6,  -114, -59, 42,  -83, -39, -38, 113, 121, 121};
