// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t grouped_conv_3_output_ref[16] = {101, -45, 15, 53, 74, -48, 69, 2, 87, -64, 1, 91, 86, -59, 106, 84};
