// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t grouped_conv_3_output_mult[4] = {1185059072, 1516666368, 2019627392, 2014696320};
