// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t grouped_conv_3_weights[24] = {5,  38, -95, -44, 34, 127,  -58, -127, -108, -114, -20, 11,
                                           -4, -9, -97, 94,  23, -127, -49, -127, -7,   126,  22,  110};
