// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t sub_ident_s8_input_data[24] = {-16, 36, 126, 28, 3,   91, 0,   0,  -32, 85, -23, 32,
                                            3,   91, 0,   0,  -72, 6,  -25, 32, 3,   91, 0,   0};
