// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t sub_ident_s8_output[24] = {-24, 18, 64, 14, 2,  46, 0,   0,  -49, 43, -12, 16,
                                        2,   46, 0,  0,  12, 10, -32, -1, 0,   0,  0,   0};

const int8_t *const sub_ident_s8_output_ref = sub_ident_s8_output;
