// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t reduce_max_axis_h_s16_input_tensor[16] =
    {28447, 23124, -5091, -20927, 28891, 7166, 23866, -23119, -19211, 25648, 4831, 30829, 13288, -16931, 27199, 31573};
