// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t resize_nn_batch_channels_s16_input_tensor[32] = {
    -28305, -2679,  -27669, -6870,  5988,   -31731, 11,     23217,  -24303, -19438, -20222,
    -20765, -10732, 24030,  3607,   -29816, 23189,  -31224, -23453, 10901,  -20193, 4669,
    24143,  -19618, -27956, -25083, -7729,  10710,  9275,   -12385, -16229, 3338};
