// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mul_ident_s8_lhs_input_tensor[24] = {80,  109, 22, 94, 14, 121, 0, 0, 16, 74, -4, 42,
                                                  -70, 90,  0,  0,  1,  0,   0, 0, 2,  0,  0,  0};
