// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mul_ident_s8_output[24] = {53,  105, 23,  -53, -47, 123, -62,  -62, 1,   -23, -64, -40,
                                        -98, -15, -62, -62, -44, -11, -104, -40, -97, -15, -62, -62};

const int8_t *const mul_ident_s8_output_ref = mul_ident_s8_output;
