// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mul_ident_s8_rhs_input_tensor[24] = {87, 115, 121, -44, 13, 121, 0,   0,  93,  0,  0, 0,
                                                  0,  0,   0,   0,   32, 98,  -81, 42, -70, 90, 0, 0};
