// Generated by test_settings.py using tensorflow version 2.20.0 (Keras version 3.13.0).
// Interpreter from tensorflow version 2.20.0 and revision v2.20.0-rc0-4-g72fbba3d20f.
#include "biases_data.h"
#include "config_data.h"
#include "input_data.h"
#include "output_mult_data.h"
#include "output_ref_data.h"
#include "output_shift_data.h"
#include "weights_data.h"
