// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t space_to_depth_min_spatial_s8_input_tensor[20] = {42,  -8, 8,   87, 103, 11,   -60, -121, -38, -90,
                                                               -54, 9,  -79, 2,  -11, -126, 114, 113,  119, 108};
