// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.4).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t int16xint8xint32_1x1_batch_output_multiplier[6] =
    {1112010904, 1121493018, 1112934566, 1972361144, 1106728413, 1128469741};

const int32_t *const int16xint8xint32_1x1_batch_output_mult = int16xint8xint32_1x1_batch_output_multiplier;
