// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.4).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t int16xint8xint32_1x1_batch_output[72] = {
    -16282, 5608,  16703, 3497,  10380, -7913, 15322,  -15090, -16469, -20049, -17064, -3521,  12726,  -2768, 8938,
    -21354, 4651,  5436,  326,   8318,  8435,  4383,   10350,  -14694, 19369,  -474,   -15204, -24985, -5024, -9829,
    9033,   -8159, 5050,  1633,  -397,  6604,  7469,   879,    9100,   17172,  -11637, 11106,  12039,  26277, 4268,
    -758,   20267, -190,  -232,  5521,  -4734, -1662,  4388,   -9126,  27967,  5112,   -9211,  -28250, -8415, 13369,
    -12830, 9798,  14802, 12649, -2,    3896,  -24034, 14687,  8967,   32625,  -1144,  -13719};

const int16_t *const int16xint8xint32_1x1_batch_output_ref = int16xint8xint32_1x1_batch_output;
