// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t maxpooling_3_input[54] = {102, -67, -127, 122, 88,  -114, -32,  -102, 37,  -60,  71,  -100, -84, 111,
                                       26,  40,  -69,  107, -65, 3,    -110, 23,   -50, -33,  42,  47,   25,  -86,
                                       21,  -58, -36,  74,  46,  -112, -66,  -80,  104, -104, -50, 39,   -24, 39,
                                       -73, 44,  54,   -39, 45,  22,   -63,  -124, 97,  -117, -94, 84};
