// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t maxpooling_3_output_ref[30] = {102, -67, 88, -114, 37,  -60, -84,  111, -69, 107, -65, 3,   -50,  -33, 25,
                                            -86, -36, 74, -66,  -80, 104, -104, -24, 39,  54,  -39, -63, -124, -94, 84};
