// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t k7_1d_valid_16ch_32h_output_multiplier[16] = {1643060710,
                                                            1238992562,
                                                            1578927997,
                                                            1653187412,
                                                            1433384321,
                                                            2143694931,
                                                            1665307212,
                                                            1449943106,
                                                            1316418377,
                                                            1687601838,
                                                            1394160873,
                                                            1644920731,
                                                            1255071459,
                                                            1753172017,
                                                            1260205637,
                                                            1457243002};

const int32_t *const k7_1d_valid_16ch_32h_output_mult = k7_1d_valid_16ch_32h_output_multiplier;
