// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#include "bias.h"
#include "config_data.h"
#include "input_tensor.h"
#include "output.h"
#include "output_multiplier.h"
#include "output_shift.h"
#include "weights.h"
