// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t add_broadcast_h_s16_rhs_input_tensor[24] = {33,     0,     0,     0, 353,   0,     0,     0,
                                                          -17920, 30950, 23879, 0, 20272, 31047, 23879, 0,
                                                          15264,  30800, 29609, 0, 15280, 30800, 29609, 0};
