// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t slice_center_3x3_s32_output_tensor[6] =
    {812885766, 113454969, 1779532951, 1810022365, 1650241856, 1692732289};
