// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t hard_swish_sweep_edges_s16_input_tensor[64] = {
    -128, -124, -120, -116, -112, -108, -104, -100, -96, -92, -88, -84, -80, -76, -72, -68,
    -64,  -60,  -56,  -52,  -48,  -43,  -39,  -35,  -31, -27, -23, -19, -15, -11, -7,  -3,
    1,    5,    9,    13,   17,   21,   25,   29,   33,  37,  42,  46,  50,  54,  58,  62,
    66,   70,   74,   78,   82,   86,   90,   94,   98,  102, 106, 110, 114, 118, 122, 127};
