// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t hard_swish_sweep_edges_s16_output[64] = {
    -128, -125, -122, -119, -116, -113, -109, -106, -103, -100, -96, -93, -90, -86, -83, -79,
    -76,  -72,  -69,  -65,  -62,  -57,  -53,  -50,  -46,  -42,  -38, -34, -31, -27, -23, -19,
    -15,  -11,  -7,   -3,   2,    6,    10,   14,   18,   23,   28,  32,  37,  41,  46,  50,
    55,   59,   64,   68,   73,   78,   82,   87,   92,   96,   101, 106, 111, 116, 121, 127};
