// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define SCATTER_ND_POINTS_2D_S16_FORCE_NO_QUANTIZE true
#define SCATTER_ND_POINTS_2D_S16_OUTPUT_SHAPE                                                                          \
    {                                                                                                                  \
        2, 3,                                                                                                          \
    }
#define SCATTER_ND_POINTS_2D_S16_NUM_UPDATES 3
#define SCATTER_ND_POINTS_2D_S16_INDEX_DEPTH 2
#define SCATTER_ND_POINTS_2D_S16_INDICES_VALUES                                                                        \
    {                                                                                                                  \
        0, 0, 1, 2, 0, 2,                                                                                              \
    }
#define SCATTER_ND_POINTS_2D_S16_UPDATES_VALUES                                                                        \
    {                                                                                                                  \
        500, -600, 700,                                                                                                \
    }
#define SCATTER_ND_POINTS_2D_S16_SLICE_SIZE 1
#define SCATTER_ND_POINTS_2D_S16_OUTPUT_SIZE 6
#define SCATTER_ND_POINTS_2D_S16_OUTPUT_STRIDES                                                                        \
    {                                                                                                                  \
        3, 1,                                                                                                          \
    }
