// Generated by generate_sqrt_s16_test_data.py
// Deterministic integer-sqrt reference for arm_sqrt_s16.
#pragma once
#include <stdint.h>

const int16_t sqrt_long_row_s16_input_tensor[32] = {
  -30000, -20000, -10000, -5000, -1000, -100, 0, 50,
  100, 200, 400, 800, 1200, 1600, 2000, 2400,
  2800, 3200, 3600, 4000, 8000, 12000, 16000, 20000,
  22000, 24000, 26000, 28000, 30000, 31000, 32000, 32600
};
