if(NOT DEFINED PACKAGE_DIR)
  message(FATAL_ERROR "PACKAGE_DIR is required")
endif()
if(NOT DEFINED EXPECTED_LIBRARY)
  message(FATAL_ERROR "EXPECTED_LIBRARY is required")
endif()

set(CMAKE_C_COMPILER_ID "${TEST_C_COMPILER_ID}")
set(CMAKE_SYSTEM_PROCESSOR "${TEST_SYSTEM_PROCESSOR}")
set(ZEPHYR_TOOLCHAIN_VARIANT "${TEST_ZEPHYR_TOOLCHAIN_VARIANT}")
set(NS_CMSIS_NN_TARGET_CPU "${TEST_TARGET_CPU}")

foreach(symbol CONFIG_CPU_CORTEX_M0 CONFIG_CPU_CORTEX_M0PLUS CONFIG_CPU_CORTEX_M4 CONFIG_CPU_CORTEX_M55 CONFIG_FPU)
  set(${symbol} FALSE)
endforeach()

foreach(symbol ${TEST_TRUE_SYMBOLS})
  if(NOT "${symbol}" STREQUAL "")
    set(${symbol} TRUE)
  endif()
endforeach()

include("${PACKAGE_DIR}/cmake/ns-cmsis-nn-select-variant.cmake")

ns_cmsis_nn_resolve_variant(
  PACKAGE_ROOT "${PACKAGE_DIR}"
  OUT_VAR RESOLVED_LIBRARY
  TOOLCHAIN_OUT RESOLVED_TOOLCHAIN
  TARGET_CPU_OUT RESOLVED_TARGET_CPU
  ARCH_OUT RESOLVED_ARCH
)

get_filename_component(RESOLVED_NAME "${RESOLVED_LIBRARY}" NAME)
if(NOT RESOLVED_NAME STREQUAL EXPECTED_LIBRARY)
  message(FATAL_ERROR "Expected ${EXPECTED_LIBRARY}, got ${RESOLVED_NAME}")
endif()
