// Generated by generate_comparison_data.py
#pragma once
#include <stdint.h>

const int8_t comparison_less_broadcast_c_s8_input_1_input_tensor[24] = {
    -16, -13, -10, -7, -4, -1, 2, 5, 

    8, 11, 14, 17, 20, 23, 26, 29, 

    32, 35, 38, 41, 44, 47, 50, 53
};
