// Generated by generate_sqrt_s16_test_data.py
// Deterministic integer-sqrt reference for arm_sqrt_s16.
#pragma once
#include <stdint.h>

const int16_t sqrt_small_tensor_s16_input_tensor[24] = {
  -20000, -100, 0, 1, 10, 100, 500, 1000,
  2000, 4000, 8000, 12000, 16000, 20000, 24000, 28000,
  30000, 31000, 32000, 32767, -32768, -1, 12345, 23456
};
