// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t sub_broadcast_w_s16_lhs_input_tensor[24] = {-1856,  20563, 30133,  0,     5931,  -27664, 11648, 20444,
                                                          -32208, 22849, 30133,  0,     1152,  20569,  30133, 0,
                                                          -2063,  -698,  -14060, 32557, 31024, -21057, 30133, 0};
