// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t sub_broadcast_w_s16_output[24] = {11233,  32767,  24,     0,     19083, -4640,  -18612, 20611,
                                                -19368, 32767,  24,     0,     11283, 25,     24,     0,
                                                8042,   -21416, -32768, 32767, 32767, -32768, 24,     0};

const int16_t *const sub_broadcast_w_s16_output_ref = sub_broadcast_w_s16_output;
