// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define SLICE_CENTER_3X3_S16_BATCH_SIZE 1
#define SLICE_CENTER_3X3_S16_INPUT_N 1
#define SLICE_CENTER_3X3_S16_INPUT_H 5
#define SLICE_CENTER_3X3_S16_INPUT_W 5
#define SLICE_CENTER_3X3_S16_INPUT_C 1
#define SLICE_CENTER_3X3_S16_BEGIN                                                                                     \
    {                                                                                                                  \
        0, 1, 2, 0,                                                                                                    \
    }
#define SLICE_CENTER_3X3_S16_END                                                                                       \
    {                                                                                                                  \
        1, 4, 4, 1,                                                                                                    \
    }
#define SLICE_CENTER_3X3_S16_STRIDES                                                                                   \
    {                                                                                                                  \
        1, 1, 1, 1,                                                                                                    \
    }
#define SLICE_CENTER_3X3_S16_INPUT_BATCHES 1
#define SLICE_CENTER_3X3_S16_BEGIN_N 0
#define SLICE_CENTER_3X3_S16_BEGIN_H 1
#define SLICE_CENTER_3X3_S16_BEGIN_W 2
#define SLICE_CENTER_3X3_S16_BEGIN_C 0
#define SLICE_CENTER_3X3_S16_END_N 1
#define SLICE_CENTER_3X3_S16_END_H 4
#define SLICE_CENTER_3X3_S16_END_W 4
#define SLICE_CENTER_3X3_S16_END_C 1
#define SLICE_CENTER_3X3_S16_STRIDES_N 1
#define SLICE_CENTER_3X3_S16_STRIDES_H 1
#define SLICE_CENTER_3X3_S16_STRIDES_W 1
#define SLICE_CENTER_3X3_S16_STRIDES_C 1
#define SLICE_CENTER_3X3_S16_OUTPUT_SIZE 6
#define SLICE_CENTER_3X3_S16_OUTPUT_N 1
#define SLICE_CENTER_3X3_S16_OUTPUT_H 3
#define SLICE_CENTER_3X3_S16_OUTPUT_W 2
#define SLICE_CENTER_3X3_S16_OUTPUT_C 1
