// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t slice_center_3x3_s16_input_tensor[25] = {7926,  23777, 11826, 32483, 10056, 25207, 26356, 12815, 2961,
                                                       22548, 13019, 5918,  11842, 2565,  32240, 26878, 31683, 31881,
                                                       12552, 3082,  5169,  26988, 20582, 11759, 11052};
