// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t slice_center_3x3_s16_output_tensor[6] = {1748, 29647, 27086, 3035, 21554, 25578};
