// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t concat_axis_c_ten_inputs_s32_input_tensor_2[4] = {320059508, -1417380606, -166572085, -293773492};
