// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t concat_axis_c_ten_inputs_s32_output[8] =
    {375752488, 320059508, -1063903118, -1417380606, -2026762776, -166572085, 717885946, -293773492};
