// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t batch_to_space_nd_both_crops_s8_input_tensor[96] = {
    51,  40, 50,  40,  110,  78,  -82, 120, 43,  119, 5,   22,  126,  -120, 109,  -52, -88,  -127, -60,  -54,
    -30, 17, 55,  -17, 71,   -44, -41, -28, -97, -46, -21, -51, 63,   -83,  55,   19,  -119, -56,  -84,  34,
    61,  93, -65, 124, 75,   -3,  97,  -98, 52,  -72, 100, -58, -19,  30,   48,   -73, -49,  116,  -125, 124,
    121, 41, 99,  -62, -15,  68,  54,  -98, 84,  -24, -81, 112, -128, -93,  6,    23,  21,   -71,  0,    -75,
    -76, 63, -83, 120, -119, 105, -41, 124, -35, -1,  96,  124, -39,  43,   -100, 50};
