// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t batch_to_space_nd_both_crops_s8_output[63] = {
    40,  -44, 50,   -41, 40,  -28, 110, -97, 78,  -72, -93, 100, 6,    -58, 23,  -19,  21,  30,  120, -51, 43,
    63,  119, -83,  5,   55,  22,  -73, -75, -49, -76, 116, 63,  -125, -83, 124, -120, -56, 109, -84, -52, 34,
    -88, 61,  -127, 41,  105, 99,  -41, -62, 124, -15, -35, 68,  -54,  124, -30, 75,   17,  -3,  55,  97,  -17};
