// Generated by test_settings.py using tensorflow version 2.20.0 (Keras version 3.13.0).
// Interpreter from tensorflow version 2.20.0 and revision v2.20.0-rc0-4-g72fbba3d20f.
#pragma once
#include <stdint.h>

const int16_t transpose_conv_s16_4_input[36] = {12003,  26907,  -11373, 31539,  20072,  -18685, 7057,  19985,  -31637,
                                                -13054, -29801, -14205, -6608,  16419,  25193,  27342, -7638,  14443,
                                                29680,  5957,   29346,  -20051, -21040, 15829,  5427,  -7914,  2661,
                                                26325,  -15540, 9953,   -834,   -12070, 27882,  6379,  -21226, 24246};
