// Generated by test_settings.py using tensorflow version 2.20.0 (Keras version 3.13.0).
// Interpreter from tensorflow version 2.20.0 and revision v2.20.0-rc0-4-g72fbba3d20f.
#pragma once
#include <stdint.h>

const int32_t transpose_conv_s16_4_output_mult[5] = {1710253519, 1647689289, 1721807983, 1707337277, 1711094238};
