// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t mul_broadcast_c_s16_lhs_input_tensor[24] = {-1936, 11638,  32699, 0,     -11200, 9232,  32699,  0,
                                                          9153,  1172,   18502, 12046, 28112,  11639, 32699,  0,
                                                          272,   -17347, 32699, 0,     1766,   -8178, -20600, 24765};
