// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t mul_broadcast_c_s16_rhs_input_tensor[6] = {8390, 32599, -4981, 11921, 28192, 11639};
