// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t fc_conv_int8_diff_channels_output_multiplier[16] = {1768091679,
                                                                  1764258018,
                                                                  1768268106,
                                                                  1767127718,
                                                                  1768592496,
                                                                  1765831623,
                                                                  1761648877,
                                                                  1765407196,
                                                                  1764083266,
                                                                  1767994781,
                                                                  1754247450,
                                                                  1749568596,
                                                                  1732661393,
                                                                  1768535361,
                                                                  1764128681,
                                                                  1752159530};

const int32_t *const fc_conv_int8_diff_channels_output_mult = fc_conv_int8_diff_channels_output_multiplier;
