// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define MIRROR_PAD_REFLECT_WIDE_S16_FORCE_NO_QUANTIZE true
#define MIRROR_PAD_REFLECT_WIDE_S16_INPUT_SHAPE                                                                        \
    {                                                                                                                  \
        4,                                                                                                             \
    }
#define MIRROR_PAD_REFLECT_WIDE_S16_PAD_BEFORE                                                                         \
    {                                                                                                                  \
        3,                                                                                                             \
    }
#define MIRROR_PAD_REFLECT_WIDE_S16_MODE 0
#define MIRROR_PAD_REFLECT_WIDE_S16_INPUT_VALUES                                                                       \
    {                                                                                                                  \
        -300, 0, 500, 900,                                                                                             \
    }
#define MIRROR_PAD_REFLECT_WIDE_S16_RANK 1
#define MIRROR_PAD_REFLECT_WIDE_S16_INPUT_SIZE 4
#define MIRROR_PAD_REFLECT_WIDE_S16_OUTPUT_SIZE 10
#define MIRROR_PAD_REFLECT_WIDE_S16_OUTPUT_SHAPE                                                                       \
    {                                                                                                                  \
        10,                                                                                                            \
    }
