// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define SPACE_TO_DEPTH_BS2_CHANNELS_S8_IN_DIM                                                                          \
    {                                                                                                                  \
        1, 12, 4, 8,                                                                                                   \
    }
#define SPACE_TO_DEPTH_BS2_CHANNELS_S8_BLOCK_SIZE 2
#define SPACE_TO_DEPTH_BS2_CHANNELS_S8_OUT_DIM                                                                         \
    {                                                                                                                  \
        1, 6, 2, 32,                                                                                                   \
    }
#define SPACE_TO_DEPTH_BS2_CHANNELS_S8_INPUT_SIZE 384
#define SPACE_TO_DEPTH_BS2_CHANNELS_S8_OUTPUT_SIZE 384
#define SPACE_TO_DEPTH_BS2_CHANNELS_S8_INPUT_OFFSET 128
#define SPACE_TO_DEPTH_BS2_CHANNELS_S8_OUTPUT_OFFSET -128
