#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: Copyright 2026 Arm Limited or its affiliates
#
# SPDX-License-Identifier: Apache-2.0
#
"""Generate test data for arm_rsqrt_s16 unit test (float-derived)."""

import os
import math
import random

OUT_ROOT = os.path.join("Tests", "UnitTest", "TestCases", "TestData")


def arm_nn_isqrt_u32(x: int) -> int:
    res = 0
    bit = 1 << 30
    while bit > x:
        bit >>= 2
    while bit != 0:
        if x >= res + bit:
            x -= res + bit
            res = (res >> 1) + bit
        else:
            res >>= 1
        bit >>= 2
    return res


def arm_nn_doubling_high_mult_no_sat(m1: int, m2: int) -> int:
    mult = (1 << 30) + (m1 * m2)
    return int(mult >> 31)


def arm_nn_divide_by_power_of_two(dividend: int, exponent: int) -> int:
    if exponent == 0:
        return dividend
    remainder_mask = (1 << exponent) - 1
    remainder = remainder_mask & dividend
    result = dividend >> exponent
    threshold = remainder_mask >> 1
    if result < 0:
        threshold += 1
    if remainder > threshold:
        result += 1
    return result


def arm_nn_requantize(val: int, multiplier: int, shift: int) -> int:
    left_shift = shift if shift > 0 else 0
    right_shift = -shift if shift < 0 else 0
    shifted = val * (1 << left_shift)
    return arm_nn_divide_by_power_of_two(arm_nn_doubling_high_mult_no_sat(shifted, multiplier), right_shift)


def quantize_scale(scale: float):
    if scale == 0.0:
        return 0, 0
    significand, shift = math.frexp(scale)
    significand_q31 = int(round(significand * (1 << 31)))
    return significand_q31, shift


def compute_output(inputs, input_offset, out_offset, out_mult, out_shift, needs_rescale, act_min, act_max):
    outputs = []
    for x in inputs:
        val = int(x) - int(input_offset)
        if val < 0:
            val = 0
        if val > 0x7FFF:
            val = 0x7FFF

        val_q15 = val << 15
        sqrt_res = arm_nn_isqrt_u32(val_q15)
        if sqrt_res == 0:
            rsqrt_res = 0x7FFF
        else:
            rsqrt_res = int((1 << 30) / sqrt_res)

        if needs_rescale:
            acc = arm_nn_requantize(rsqrt_res, out_mult, out_shift)
        else:
            acc = int(rsqrt_res)

        acc += out_offset
        if acc < act_min:
            acc = act_min
        if acc > act_max:
            acc = act_max
        outputs.append(int(acc))
    return outputs


def write_header(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


def format_array(name: str, arr, ctype: str = "int16_t") -> str:
    lines = [f"const {ctype} {name}[{len(arr)}] = {{"]
    for i in range(0, len(arr), 8):
        chunk = ", ".join(str(v) for v in arr[i:i + 8])
        if i + 8 < len(arr):
            lines.append(f"  {chunk},")
        else:
            lines.append(f"  {chunk}")
    lines.append("};")
    return "\n".join(lines)


def generate():
    random.seed(0xC0FFEE)
    length = 1024

    floats = [abs(random.gauss(0.0, 1.0) * 10.0) for _ in range(length)]
    max_in = max(floats) if floats else 1.0
    si = max_in / 32767.0 if max_in > 0 else 1.0

    qi = [min(32767, max(1, int(round(v / si)))) for v in floats]
    qi[-1] = 32767

    out_f = [1.0 / math.sqrt(si * q) for q in qi]
    max_out = max(out_f) if out_f else 1.0
    so = max_out / 32767.0 if max_out > 0 else 1.0

    # Kernel rsqrt_res ~= 2^22.5 / sqrt(qi). Include 2^-22.5 factor.
    scale = 1.0 / (so * math.sqrt(si) * (2.0 ** 22.5))
    mult, shift = quantize_scale(scale)

    name = "rsqrt_float_tensor_s16"
    inputs = qi
    out = compute_output(inputs, 0, 0, mult, shift, True, -32768, 32767)

    dir_path = os.path.join(OUT_ROOT, name)
    os.makedirs(dir_path, exist_ok=True)

    header = "// Generated by generate_rsqrt_s16_test_data.py\n"
    header += "// Deterministic integer-rsqrt reference for arm_rsqrt_s16.\n"

    prefix = name.upper()
    cfg_lines = [header, "#pragma once", ""]
    cfg_lines.append(f"#define {prefix}_BATCH_SIZE 1")
    cfg_lines.append(f"#define {prefix}_HEIGHT_1 1")
    cfg_lines.append(f"#define {prefix}_WIDTH_1 {length}")
    cfg_lines.append(f"#define {prefix}_CHANNEL_1 1")
    cfg_lines.append(f"#define {prefix}_INPUT_OFFSET 0")
    cfg_lines.append(f"#define {prefix}_OUTPUT_OFFSET 0")
    cfg_lines.append(f"#define {prefix}_NEEDS_RESCALE true")
    cfg_lines.append(f"#define {prefix}_OUTPUT_MULTIPLIER {mult}")
    cfg_lines.append(f"#define {prefix}_OUTPUT_SHIFT {shift}")
    cfg_lines.append(f"#define {prefix}_OUT_ACTIVATION_MIN -32768")
    cfg_lines.append(f"#define {prefix}_OUT_ACTIVATION_MAX 32767")
    cfg_lines.append(f"#define {prefix}_INPUT_SCALE {si}")
    cfg_lines.append(f"#define {prefix}_OUTPUT_SCALE {so}")
    cfg_lines.append(f"#define {prefix}_OUTPUT_LEN {length}")
    cfg_lines.append(f"#define {prefix}_BLOCK_SIZE {length}")
    cfg_content = "\n".join(cfg_lines) + "\n"
    write_header(os.path.join(dir_path, "config_data.h"), cfg_content)

    in_content = header + "#pragma once\n#include <stdint.h>\n\n"
    in_content += format_array(f"{name}_input_tensor", inputs, "int16_t") + "\n"
    write_header(os.path.join(dir_path, "input_tensor.h"), in_content)

    out_content = header + "#pragma once\n#include <stdint.h>\n\n"
    out_content += format_array(f"{name}_output", out, "int16_t") + "\n"
    write_header(os.path.join(dir_path, "output.h"), out_content)

    td_content = header + "#include \"config_data.h\"\n#include \"input_tensor.h\"\n#include \"output.h\"\n"
    write_header(os.path.join(dir_path, "test_data.h"), td_content)

    print("Generated rsqrt dataset:", name)
    print("si =", si)
    print("so =", so)


if __name__ == "__main__":
    generate()
