#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: Copyright 2026 Arm Limited or its affiliates
#
# SPDX-License-Identifier: Apache-2.0
#
"""Generate test data for arm_reduce_sum_s16 unit test."""

import os
import math
import random

OUT_ROOT = os.path.join("Tests", "UnitTest", "TestCases", "TestData")

def quantize_scale(scale):
    """
    Calculates the multiplier and shift for a given scale.

    Args:
        scale (float): The scale to be quantized.

    Returns:
        A tuple containing the quantized multiplier and the shift.
    """
    if scale == 0.0:
        return 0, 0
    
    # Find the shift and significand of the scale
    significand, shift = math.frexp(scale)
    
    # The CMSIS-NN library expects the multiplier to be between 0.5 and 1.
    # We can achieve this by adjusting the shift and significand.
    # If the significand is 0.5, we can double it and decrement the shift.
    if significand == 0.5:
        significand *= 2
        shift -= 1

    # Quantize the significand to a 31-bit integer
    multiplier = int(round(significand * (1 << 31)))
    
    return multiplier, shift

def compute_output(inputs, input_offset, output_offset, output_multiplier, output_shift, act_min, act_max):
    """
    Computes the reference output for the reduce_sum operation.
    """
    outputs = []
    for x in inputs:
        # The reference implementation for reduce_sum is just a simple sum.
        # The quantization is handled by the test framework.
        val = sum(x)
        
        # Requantize the output
        val = arm_nn_requantize(val, output_multiplier, output_shift)
        
        val += output_offset
        
        # Clamp the output to the activation range
        val = max(min(val, act_max), act_min)
        
        outputs.append(val)
        
    return outputs

def arm_nn_doubling_high_mult_no_sat(m1: int, m2: int) -> int:
    mult = (1 << 30) + (m1 * m2)
    return int(mult >> 31)

def arm_nn_divide_by_power_of_two(dividend: int, exponent: int) -> int:
    if exponent == 0:
        return dividend
    remainder_mask = (1 << exponent) - 1
    remainder = remainder_mask & dividend
    result = dividend >> exponent
    threshold = remainder_mask >> 1
    if result < 0:
        threshold += 1
    if remainder > threshold:
        result += 1
    return result

def arm_nn_requantize(val: int, multiplier: int, shift: int) -> int:
    left_shift = shift if shift > 0 else 0
    right_shift = -shift if shift < 0 else 0
    shifted = val * (1 << left_shift)
    return arm_nn_divide_by_power_of_two(arm_nn_doubling_high_mult_no_sat(shifted, multiplier), right_shift)

def write_header(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)

def format_array(name: str, arr, ctype: str = "int16_t") -> str:
    lines = [f"const {ctype} {name}[{len(arr)}] = {{"]
    for i in range(0, len(arr), 8):
        chunk = ", ".join(str(v) for v in arr[i:i + 8])
        if i + 8 < len(arr):
            lines.append(f"  {chunk},")
        else:
            lines.append(f"  {chunk}")
    lines.append("};")
    return "\n".join(lines)

def generate():
    random.seed(0xC0FFEE)
    
    # IN_DIM = {4, 4, 1, 1}. We want to reduce H (the second dim). 
    # OUT_DIM = {4, 1, 1, 1}.
    # This means we have 4 outputs, each summing 4 elements.
    float_inputs = [[random.uniform(-10, 10) for _ in range(4)] for _ in range(4)]
    
    expected_float_output = [sum(row) for row in float_inputs]
    print("Expected float output:", expected_float_output)
    
    max_abs_val = max(abs(x) for row in float_inputs for x in row)
    input_scale = max_abs_val / 32767.0
    output_scale = max(abs(x) for x in expected_float_output) / 32767.0

    inputs = [[int(round(x / input_scale)) for x in row] for row in float_inputs]
    flat_inputs = [item for sublist in inputs for item in sublist]

    # REAL MULTIPLIER FOR A PURE SUM KERNEL (NO N MULTIPLICATION)
    real_multiplier = (input_scale / output_scale)
    output_multiplier, output_shift = quantize_scale(real_multiplier)
    
    outputs = compute_output(inputs, 0, 0, output_multiplier, output_shift, -32768, 32767)
    
    name = "reduce_sum_s16_test"
    dir_path = os.path.join(OUT_ROOT, name)
    os.makedirs(dir_path, exist_ok=True)

    header = "// Generated by generate_reduce_sum_s16_test_data.py\n"
    prefix = name.upper()
    cfg_lines = [header, "#pragma once", ""]
    cfg_lines.append(f"#define {prefix}_IN_DIM {{4, 4, 1, 1}}")
    cfg_lines.append(f"#define {prefix}_AXIS_DIM {{0, 1, 0, 0}}") # CORRECTED: Reduce H
    cfg_lines.append(f"#define {prefix}_OUT_DIM {{4, 1, 1, 1}}")
    cfg_lines.append(f"#define {prefix}_INPUT_OFFSET 0")
    cfg_lines.append(f"#define {prefix}_OUTPUT_OFFSET 0")
    cfg_lines.append(f"#define {prefix}_OUTPUT_MULTIPLIER {output_multiplier}")
    cfg_lines.append(f"#define {prefix}_OUTPUT_SHIFT {output_shift}")
    cfg_lines.append(f"#define {prefix}_OUTPUT_SIZE {len(outputs)}")
    
    write_header(os.path.join(dir_path, "config_data.h"), "\n".join(cfg_lines) + "\n")
    write_header(os.path.join(dir_path, "input_tensor.h"), header + "#pragma once\n#include <stdint.h>\n\n" + format_array(f"{name}_input_tensor", flat_inputs, "int16_t") + "\n")
    write_header(os.path.join(dir_path, "output.h"), header + "#pragma once\n#include <stdint.h>\n\n" + format_array(f"{name}_output", outputs, "int16_t") + "\n")
    write_header(os.path.join(dir_path, "test_data.h"), header + "#include \"config_data.h\"\n#include \"input_tensor.h\"\n#include \"output.h\"\n")
    print("Generated reduce_sum dataset:", name)

def generate_axis_2_3():
    random.seed(0xDEADBEEF)
    
    # IN_DIM = {7, 8, 4, 9}. Reduce W (4) and C (9).
    # OUT_DIM = {7, 8, 1, 1}. 
    # This means we have 56 outputs (from N*H = 7*8). Each output sums 36 elements (W*C = 4*9).
    float_inputs = [[random.uniform(-10, 10) for _ in range(36)] for _ in range(56)]
    
    expected_float_output = [sum(row) for row in float_inputs]
    print("Expected float output for axis [2, 3]:", expected_float_output)
    
    max_abs_val = max(abs(x) for row in float_inputs for x in row)
    input_scale = max_abs_val / 32767.0
    output_scale = max(abs(x) for x in expected_float_output) / 32767.0

    inputs = [[int(round(x / input_scale)) for x in row] for row in float_inputs]
    flat_inputs = [item for sublist in inputs for item in sublist]

    # REAL MULTIPLIER FOR A PURE SUM KERNEL
    real_multiplier = (input_scale / output_scale)
    output_multiplier, output_shift = quantize_scale(real_multiplier)
    
    outputs = compute_output(inputs, 0, 0, output_multiplier, output_shift, -32768, 32767)
    
    name = "reduce_sum_s16_test_axis_2_3"
    dir_path = os.path.join(OUT_ROOT, name)
    os.makedirs(dir_path, exist_ok=True)

    header = "// Generated by generate_reduce_sum_s16_test_data.py\n"
    prefix = name.upper()
    cfg_lines = [header, "#pragma once", ""]
    cfg_lines.append(f"#define {prefix}_IN_DIM {{7, 8, 4, 9}}")
    cfg_lines.append(f"#define {prefix}_AXIS_DIM {{0, 0, 1, 1}}") # Reduce W, C
    cfg_lines.append(f"#define {prefix}_OUT_DIM {{7, 8, 1, 1}}")
    cfg_lines.append(f"#define {prefix}_INPUT_OFFSET 0")
    cfg_lines.append(f"#define {prefix}_OUTPUT_OFFSET 0")
    cfg_lines.append(f"#define {prefix}_OUTPUT_MULTIPLIER {output_multiplier}")
    cfg_lines.append(f"#define {prefix}_OUTPUT_SHIFT {output_shift}")
    cfg_lines.append(f"#define {prefix}_OUTPUT_SIZE {len(outputs)}")
    
    write_header(os.path.join(dir_path, "config_data.h"), "\n".join(cfg_lines) + "\n")
    write_header(os.path.join(dir_path, "input_tensor.h"), header + "#pragma once\n#include <stdint.h>\n\n" + format_array(f"{name}_input_tensor", flat_inputs, "int16_t") + "\n")
    write_header(os.path.join(dir_path, "output.h"), header + "#pragma once\n#include <stdint.h>\n\n" + format_array(f"{name}_output", outputs, "int16_t") + "\n")
    write_header(os.path.join(dir_path, "test_data.h"), header + "#include \"config_data.h\"\n#include \"input_tensor.h\"\n#include \"output.h\"\n")
    print("Generated reduce_sum dataset:", name)


if __name__ == "__main__":
    generate()
    generate_axis_2_3()
