#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the License); you may
# not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an AS IS BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""
Standalone generator for arm_transpose_conv_s16 test data.

Uses TensorFlow Lite with the int16x8 quantization scheme:
  - Input:   int16, zero_point = 0  (symmetric)
  - Weights: int8
  - Bias:    int64
  - Output:  int16, zero_point = 0  (symmetric)

Run from the Tests/UnitTest directory:
  python generate_transpose_conv_s16_data.py

Outputs C header files under TestCases/TestData/<test_name>/
"""

import math
import os
import sys
import numpy as np
import tensorflow as tf
import keras

# -------------------------------------------------------------------
# Test configurations
# -------------------------------------------------------------------
TEST_CONFIGS = [
    {
        "name":      "transpose_conv_s16_1",
        "batches":   1,
        "input_h":   4,
        "input_w":   4,
        "input_ch":  4,
        "output_ch": 2,
        "filter_h":  3,
        "filter_w":  3,
        "stride_y":  2,
        "stride_x":  2,
        "padding":   "SAME",
        "use_bias":  True,
    },
    {
        "name":      "transpose_conv_s16_2",
        "batches":   1,
        "input_h":   3,
        "input_w":   5,
        "input_ch":  8,
        "output_ch": 4,
        "filter_h":  2,
        "filter_w":  2,
        "stride_y":  1,
        "stride_x":  1,
        "padding":   "VALID",
        "use_bias":  False,
    },
    {
        "name":      "transpose_conv_s16_3",
        "batches":   2,
        "input_h":   5,
        "input_w":   3,
        "input_ch":  4,
        "output_ch": 6,
        "filter_h":  3,
        "filter_w":  3,
        "stride_y":  2,
        "stride_x":  2,
        "padding":   "SAME",
        "use_bias":  True,
    },
]

OUTDIR = "TestCases/TestData"
INT16_MIN = -32768
INT16_MAX = 32767


# -------------------------------------------------------------------
# Quantization helpers
# -------------------------------------------------------------------
def quantize_scale(scale):
    """Return (Q31_multiplier, shift) matching test_settings.py quantize_scale()."""
    significand, shift = math.frexp(scale)
    significand_q31 = round(significand * (1 << 31))
    return significand_q31, shift


def reduce_multiplier(mult_q31):
    """REDUCE_MULTIPLIER macro: convert Q31 multiplier to ~Q16 for arm_nn_requantize_s64."""
    if mult_q31 < 0x7FFF0000:
        return (mult_q31 + (1 << 15)) >> 16
    return 0x7FFF


# -------------------------------------------------------------------
# Representative dataset factory
# -------------------------------------------------------------------
def make_representative_dataset(shape):
    def gen():
        rng = np.random.default_rng(42)
        for _ in range(100):
            yield [rng.uniform(-1.0, 1.0, shape).astype(np.float32)]
    return gen


# -------------------------------------------------------------------
# C-array header generation
# -------------------------------------------------------------------
def to_c_array(name, data, dtype="int16_t"):
    flat = np.array(data).flatten()
    if dtype == "int64_t":
        vals = ", ".join(str(int(v)) + "LL" for v in flat)
    elif dtype == "int32_t":
        vals = ", ".join(str(int(v)) for v in flat)
    elif dtype == "int16_t":
        vals = ", ".join(str(int(v)) for v in flat)
    elif dtype == "int8_t":
        vals = ", ".join(str(int(v)) for v in flat)
    else:
        vals = ", ".join(str(v) for v in flat)

    return (
        f"// Auto-generated by generate_transpose_conv_s16_data.py\n"
        f"#pragma once\n"
        f"#include <stdint.h>\n\n"
        f"static const {dtype} {name}[] = {{\n  {vals}\n}};\n"
    )


def write_header(path, content):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"  wrote {path}")


# -------------------------------------------------------------------
# Per-test generation
# -------------------------------------------------------------------
def generate_test(cfg):
    name       = cfg["name"]
    batches    = cfg["batches"]
    input_h    = cfg["input_h"]
    input_w    = cfg["input_w"]
    input_ch   = cfg["input_ch"]
    output_ch  = cfg["output_ch"]
    filter_h   = cfg["filter_h"]
    filter_w   = cfg["filter_w"]
    stride_y   = cfg["stride_y"]
    stride_x   = cfg["stride_x"]
    padding    = cfg["padding"]
    use_bias   = cfg["use_bias"]

    prefix = name.upper()
    out_dir = os.path.join(OUTDIR, name)
    os.makedirs(out_dir, exist_ok=True)

    print(f"\n=== Generating {name} ===")

    # ----------------------------------------------------------------
    # 1. Build Keras model
    # ----------------------------------------------------------------
    rng = np.random.default_rng(0)

    # TFLite Conv2DTranspose kernel shape: [filter_h, filter_w, output_ch, input_ch]
    w_init = rng.uniform(-0.5, 0.5,
                         [filter_h, filter_w, output_ch, input_ch]).astype(np.float32)
    b_init = rng.uniform(-0.1, 0.1, [output_ch]).astype(np.float32) if use_bias else None

    model = keras.Sequential()
    model.add(keras.layers.InputLayer(input_shape=(input_h, input_w, input_ch),
                                       batch_size=batches))
    tconv = keras.layers.Conv2DTranspose(
        output_ch,
        kernel_size=(filter_h, filter_w),
        strides=(stride_y, stride_x),
        padding=padding,
        use_bias=use_bias,
    )
    model.add(tconv)
    if use_bias:
        tconv.set_weights([w_init, b_init])
    else:
        tconv.set_weights([w_init])

    # ----------------------------------------------------------------
    # 2. Convert to TFLite int16x8
    # ----------------------------------------------------------------
    rep_shape = (batches, input_h, input_w, input_ch)
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = make_representative_dataset(rep_shape)
    converter.target_spec.supported_ops = [
        tf.lite.OpsSet.EXPERIMENTAL_TFLITE_BUILTINS_ACTIVATIONS_INT16_WEIGHTS_INT8
    ]
    converter.inference_input_type  = tf.int16
    converter.inference_output_type = tf.int16

    tflite_bytes = converter.convert()

    tflite_path = os.path.join(out_dir, f"{name}.tflite")
    with open(tflite_path, "wb") as f:
        f.write(tflite_bytes)
    print(f"  saved TFLite model → {tflite_path}")

    # ----------------------------------------------------------------
    # 3. Inspect tensors
    # ----------------------------------------------------------------
    interp = tf.lite.Interpreter(model_content=tflite_bytes,
                                  experimental_op_resolver_type=
                                  tf.lite.experimental.OpResolverType.BUILTIN_REF)
    interp.allocate_tensors()

    in_details  = interp.get_input_details()[0]
    out_details = interp.get_output_details()[0]
    all_details = interp.get_tensor_details()

    # Print tensor summary for debugging
    for td in all_details:
        print(f"    tensor[{td['index']}] name={td['name']!r:50s} "
              f"shape={td['shape']} dtype={td['dtype'].__name__}")

    # Find filter and bias tensors by dtype/shape heuristic
    filter_tensor = None
    bias_tensor   = None
    for td in all_details:
        if td['index'] == in_details['index']:
            continue
        if td['index'] == out_details['index']:
            continue
        if td['dtype'] == np.int8:
            if filter_tensor is None:
                filter_tensor = td
        elif td['dtype'] == np.int64 and use_bias:
            if bias_tensor is None:
                bias_tensor = td

    if filter_tensor is None:
        raise RuntimeError("Could not locate int8 filter tensor")

    filter_data_raw = interp.get_tensor(filter_tensor['index'])
    # TFLite int16x8 Conv2DTranspose stores filter as [C_OUT, H, W, C_IN]
    print(f"  filter shape: {filter_data_raw.shape}  "
          f"(expected [{output_ch},{filter_h},{filter_w},{input_ch}] = [C_OUT,H,W,C_IN])")

    # TFLite Conv2DTranspose stores filter as [C_OUT, H, W, C_IN].
    # CMSIS-NN uses the same layout – no permutation needed here.

    bias_data_raw = None
    if use_bias and bias_tensor is not None:
        bias_data_raw = interp.get_tensor(bias_tensor['index'])
        print(f"  bias shape:   {bias_data_raw.shape}")
    elif use_bias:
        print("  WARNING: bias not found among int64 tensors – "
              "trying int32 search")
        for td in all_details:
            if td['dtype'] == np.int32 and td['index'] not in (
                    in_details['index'], out_details['index']):
                if bias_tensor is None:
                    bias_tensor   = td
                    bias_data_raw = interp.get_tensor(td['index'])
                    print(f"  bias (int32) shape: {bias_data_raw.shape}")

    # ----------------------------------------------------------------
    # 4. Quantization parameters
    # ----------------------------------------------------------------
    in_scale  = float(in_details['quantization_parameters']['scales'][0])
    in_zp     = int(in_details['quantization_parameters']['zero_points'][0])

    out_scale = float(out_details['quantization_parameters']['scales'][0])
    out_zp    = int(out_details['quantization_parameters']['zero_points'][0])

    filt_scales = filter_tensor['quantization_parameters']['scales']   # per-channel

    # Compute per-channel multiplier and shift
    per_ch_mult  = []
    per_ch_shift = []
    for i, fs in enumerate(filt_scales):
        eff_scale = in_scale * float(fs) / out_scale
        m, s = quantize_scale(eff_scale)
        per_ch_mult.append(m)
        per_ch_shift.append(s)

    print(f"  in_scale={in_scale:.6f} in_zp={in_zp} "
          f"out_scale={out_scale:.6f} out_zp={out_zp}")
    print(f"  multipliers: {per_ch_mult[:4]}{'...' if len(per_ch_mult) > 4 else ''}")
    print(f"  shifts:      {per_ch_shift[:4]}{'...' if len(per_ch_shift) > 4 else ''}")

    # ----------------------------------------------------------------
    # 5. Run inference to get reference output
    # ----------------------------------------------------------------
    rng2 = np.random.default_rng(7)
    input_float = rng2.uniform(-1.0, 1.0,
                               [batches, input_h, input_w, input_ch]).astype(np.float32)
    # Quantize to int16
    input_int16 = np.round(input_float / in_scale + in_zp).clip(INT16_MIN, INT16_MAX).astype(np.int16)

    interp.set_tensor(in_details['index'],
                      tf.cast(input_int16, tf.int16))
    interp.invoke()
    output_int16 = interp.get_tensor(out_details['index'])

    output_h = output_int16.shape[1]
    output_w = output_int16.shape[2]

    print(f"  output shape: {output_int16.shape}")

    # ----------------------------------------------------------------
    # 6. Compute padding (same logic as TFLite conv_settings.py)
    # ----------------------------------------------------------------
    if padding == "SAME":
        out_h_expected = input_h * stride_y
        out_w_expected = input_w * stride_x
        pad_h = max(0, (input_h - 1) * stride_y + filter_h - out_h_expected)
        pad_w = max(0, (input_w - 1) * stride_x + filter_w - out_w_expected)
        pad_y = pad_h // 2
        pad_x = pad_w // 2
        pad_y_with_offset = pad_y + (pad_h - 2 * pad_y)   # = ceil half
        pad_x_with_offset = pad_x + (pad_w - 2 * pad_x)
    else:  # VALID
        pad_y = 0
        pad_x = 0
        pad_y_with_offset = 0
        pad_x_with_offset = 0

    # ----------------------------------------------------------------
    # 7. Write C headers
    # ----------------------------------------------------------------
    def p(fname, content):
        write_header(os.path.join(out_dir, fname), content)

    # input
    p("input_data.h",       to_c_array(f"{name}_input", input_int16,    "int16_t"))
    # filter (int8)
    p("weights_data.h",     to_c_array(f"{name}_weights", filter_data_raw, "int8_t"))
    # bias
    if use_bias and bias_data_raw is not None:
        bias_dtype = "int64_t" if bias_data_raw.dtype == np.int64 else "int32_t"
        p("biases_data.h",  to_c_array(f"{name}_biases", bias_data_raw,  bias_dtype))
    else:
        p("biases_data.h",
          "// Auto-generated by generate_transpose_conv_s16_data.py\n"
          "#pragma once\n#include <stddef.h>\n#include <stdint.h>\n\n"
          f"// No bias for {name}\n"
          f"static const int64_t *{name}_biases = NULL;\n")
    # quant params
    p("output_mult_data.h", to_c_array(f"{name}_output_mult",  per_ch_mult,  "int32_t"))
    p("output_shift_data.h",to_c_array(f"{name}_output_shift", per_ch_shift, "int32_t"))
    # reference output
    p("output_ref_data.h",  to_c_array(f"{name}_output_ref", output_int16, "int16_t"))

    # config header
    dst_size   = batches * output_h * output_w * output_ch
    input_size = batches * input_h  * input_w  * input_ch
    bias_dtype_name = "int64_t"
    if use_bias and bias_data_raw is not None and bias_data_raw.dtype != np.int64:
        bias_dtype_name = "int32_t"

    config = (
        f"// Auto-generated by generate_transpose_conv_s16_data.py\n"
        f"#pragma once\n\n"
        f"#define {prefix}_OUT_CH           {output_ch}\n"
        f"#define {prefix}_IN_CH            {input_ch}\n"
        f"#define {prefix}_INPUT_W          {input_w}\n"
        f"#define {prefix}_INPUT_H          {input_h}\n"
        f"#define {prefix}_DST_SIZE         {dst_size}\n"
        f"#define {prefix}_INPUT_SIZE       {input_size}\n"
        f"#define {prefix}_OUT_ACTIVATION_MIN  {INT16_MIN}\n"
        f"#define {prefix}_OUT_ACTIVATION_MAX  {INT16_MAX}\n"
        f"#define {prefix}_INPUT_BATCHES    {batches}\n"
        f"#define {prefix}_FILTER_X         {filter_w}\n"
        f"#define {prefix}_FILTER_Y         {filter_h}\n"
        f"#define {prefix}_STRIDE_X         {stride_x}\n"
        f"#define {prefix}_STRIDE_Y         {stride_y}\n"
        f"#define {prefix}_PAD_X            {pad_x}\n"
        f"#define {prefix}_PAD_Y            {pad_y}\n"
        f"#define {prefix}_PAD_X_WITH_OFFSET {pad_x_with_offset}\n"
        f"#define {prefix}_PAD_Y_WITH_OFFSET {pad_y_with_offset}\n"
        f"#define {prefix}_OUTPUT_W         {output_w}\n"
        f"#define {prefix}_OUTPUT_H         {output_h}\n"
        f"#define {prefix}_DILATION_X       1\n"
        f"#define {prefix}_DILATION_Y       1\n"
        + (f"#define {prefix}_BIAS_IS_INT64    {'1' if bias_dtype_name == 'int64_t' else '0'}\n"
           if use_bias and bias_data_raw is not None else "")
    )
    p("config_data.h", config)

    # umbrella test_data.h
    test_data_h = (
        f"// Auto-generated by generate_transpose_conv_s16_data.py\n"
        f"#pragma once\n\n"
        f"#include \"config_data.h\"\n"
        f"#include \"input_data.h\"\n"
        f"#include \"weights_data.h\"\n"
        f"#include \"biases_data.h\"\n"
        f"#include \"output_mult_data.h\"\n"
        f"#include \"output_shift_data.h\"\n"
        f"#include \"output_ref_data.h\"\n"
    )
    p("test_data.h", test_data_h)

    print(f"  => {name} done.  output shape={output_int16.shape}")
    return {
        "name":       name,
        "output_h":   output_h,
        "output_w":   output_w,
        "pad_x":      pad_x,
        "pad_y":      pad_y,
    }


# -------------------------------------------------------------------
# Main
# -------------------------------------------------------------------
def main():
    # Run from Tests/UnitTest directory
    script_dir = os.path.dirname(os.path.abspath(__file__))
    os.chdir(script_dir)

    print(f"TensorFlow version : {tf.__version__}")
    print(f"Keras version      : {keras.__version__}")
    print(f"Output directory   : {os.path.abspath(OUTDIR)}")

    results = []
    for cfg in TEST_CONFIGS:
        r = generate_test(cfg)
        results.append(r)

    print("\n=== Summary ===")
    for r in results:
        print(f"  {r['name']:40s}  output_h={r['output_h']}  "
              f"output_w={r['output_w']}  "
              f"pad=({r['pad_x']},{r['pad_y']})")


if __name__ == "__main__":
    main()
