#!/usr/bin/env python3
#
# SPDX-FileCopyrightText: Copyright 2026 Ambiq
#
# SPDX-License-Identifier: LicenseRef-Ambiq-Apollo-SDK
#
# Licensed under the Ambiq Apollo SDK License.
# See LICENSE (root) or LICENSES/LicenseRef-Ambiq-Apollo-SDK.txt for the full text.
#
# Generates TestCases/Utils/resize_nearest_neighbor_flt_cases.h: the per-axis
# input-index maps TFLite's RESIZE_NEAREST_NEIGHBOR produces for each case, read
# back from a float32 single-op model executed by the TFLite interpreter (the
# op is dtype-independent, so one map set serves the f32 and f16 suites). The
# suites gather the expected output from these maps and compare bit-exact, and
# additionally check that their in-test index formula reproduces every map.
#
# Requires tensorflow (2.20 used for the checked-in header). Run from
# Tests/UnitTest: python3 resize_nearest_neighbor_settings_flt.py

from __future__ import annotations

import argparse
import os
import shutil
import subprocess
from dataclasses import dataclass
from pathlib import Path

import numpy as np
import tensorflow as tf

OUTPUT = Path("TestCases/Utils/resize_nearest_neighbor_flt_cases.h")


@dataclass(frozen=True)
class Case:
    name: str
    shape: tuple[int, int, int, int]
    size: tuple[int, int]
    align_corners: bool
    half_pixel_centers: bool


# Channel counts 9 / 17 / 5 / 3 leave tails on both the 4-lane f32 and 8-lane f16
# copies; 3x3 -> 5x5 with align_corners lands on exact .5 ties (round half away
# from zero); 2x2 -> 1x1 with align_corners is the out == 1 divide-by-zero guard.
CASES = [
    Case("width_double", (1, 2, 3, 2), (2, 6), False, False),
    Case("half_pixel_downsample", (1, 1, 4, 1), (1, 2), False, True),
    Case("align_downscale_b2", (2, 5, 7, 3), (3, 4), True, False),
    Case("half_pixel_upscale", (1, 3, 5, 1), (7, 9), False, True),
    Case("align_downscale_c5", (2, 9, 7, 5), (3, 2), True, False),
    Case("half_pixel_upscale_c9", (1, 4, 4, 9), (7, 7), False, True),
    Case("align_ties_c17", (1, 3, 3, 17), (5, 5), True, False),
    Case("both_flags", (1, 6, 5, 1), (4, 3), True, True),
    Case("upscale_b3", (3, 7, 9, 3), (13, 11), False, False),
    Case("downscale_40_to_7", (1, 40, 40, 1), (7, 7), False, False),
    Case("align_to_1x1", (1, 2, 2, 3), (1, 1), True, False),
    Case("from_1x1", (1, 1, 1, 5), (4, 6), False, False),
    Case("both_flags_downscale", (2, 11, 13, 4), (5, 3), True, True),
]


def tflite_maps(case: Case) -> tuple[list[int], list[int]]:
    n, h, w, c = case.shape
    oh, ow = case.size

    @tf.function(input_signature=[tf.TensorSpec((n, h, w, c), tf.float32)])
    def model(x):
        return tf.compat.v1.image.resize_nearest_neighbor(
            x, (oh, ow), align_corners=case.align_corners, half_pixel_centers=case.half_pixel_centers
        )

    converter = tf.lite.TFLiteConverter.from_concrete_functions([model.get_concrete_function()], model)
    flatbuffer = converter.convert()
    interpreter = tf.lite.Interpreter(
        model_content=flatbuffer, experimental_op_resolver_type=tf.lite.experimental.OpResolverType.BUILTIN_REF
    )
    ops = {op["op_name"] for op in interpreter._get_ops_details()}  # noqa: SLF001
    if ops != {"RESIZE_NEAREST_NEIGHBOR"}:
        raise RuntimeError(f"{case.name}: expected a single RESIZE_NEAREST_NEIGHBOR op, got {ops}")
    interpreter.allocate_tensors()
    inp = interpreter.get_input_details()[0]
    out = interpreter.get_output_details()[0]
    # Encode (y, x) uniquely (values stay exact in float32 below 2^24); c=0 lane only.
    x = np.zeros(case.shape, np.float32)
    x[0, :, :, 0] = (np.arange(h)[:, None] * w + np.arange(w)[None, :]).astype(np.float32)
    interpreter.set_tensor(inp["index"], x)
    interpreter.invoke()
    y = interpreter.get_tensor(out["index"])[0, :, :, 0].astype(np.int64)
    y_map = [int(v) // w for v in y[:, 0]]
    x_map = [int(v) % w for v in y[0, :]]
    # Separability check: every output element must be input[y_map[oy], x_map[ox]].
    expect = np.array(y_map)[:, None] * w + np.array(x_map)[None, :]
    if not np.array_equal(y, expect):
        raise RuntimeError(f"{case.name}: TFLite output is not separable into per-axis maps")
    return y_map, x_map


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", type=Path, default=OUTPUT)
    args = parser.parse_args()

    lines = [
        "/*",
        " * SPDX-FileCopyrightText: Copyright 2026 Ambiq",
        " *",
        " * SPDX-License-Identifier: Apache-2.0",
        " *",
        f" * Generated by resize_nearest_neighbor_settings_flt.py using TensorFlow {tf.__version__}",
        " * (TFLite RESIZE_NEAREST_NEIGHBOR, BUILTIN_REF resolver). Do not edit by hand.",
        " */",
        "#pragma once",
        "",
        "#include <stdbool.h>",
        "#include <stdint.h>",
        "",
        "typedef struct",
        "{",
        "    const char *name;",
        "    int32_t n;",
        "    int32_t h;",
        "    int32_t w;",
        "    int32_t c;",
        "    int32_t out_h;",
        "    int32_t out_w;",
        "    bool align_corners;",
        "    bool half_pixel_centers;",
        "    const int32_t *y_map;",
        "    const int32_t *x_map;",
        "} resize_nn_flt_case;",
        "",
    ]
    max_in = max_out = max_scratch = 0
    for case in CASES:
        y_map, x_map = tflite_maps(case)
        n, h, w, c = case.shape
        oh, ow = case.size
        max_in = max(max_in, n * h * w * c)
        max_out = max(max_out, n * oh * ow * c)
        max_scratch = max(max_scratch, oh + ow)
        lines.append(f"static const int32_t resize_nn_{case.name}_y_map[{oh}] = {{{', '.join(map(str, y_map))}}};")
        lines.append(f"static const int32_t resize_nn_{case.name}_x_map[{ow}] = {{{', '.join(map(str, x_map))}}};")
    lines += [
        "",
        f"#define RESIZE_NN_FLT_CASE_COUNT {len(CASES)}",
        f"#define RESIZE_NN_FLT_MAX_INPUT {max_in}",
        f"#define RESIZE_NN_FLT_MAX_OUTPUT {max_out}",
        f"#define RESIZE_NN_FLT_MAX_SCRATCH_ELEMENTS {max_scratch}",
        "",
        "static const resize_nn_flt_case resize_nn_flt_cases[RESIZE_NN_FLT_CASE_COUNT] = {",
    ]
    for case in CASES:
        n, h, w, c = case.shape
        oh, ow = case.size
        ac = "true" if case.align_corners else "false"
        hp = "true" if case.half_pixel_centers else "false"
        lines.append(
            f'    {{"{case.name}", {n}, {h}, {w}, {c}, {oh}, {ow}, {ac}, {hp}, '
            f"resize_nn_{case.name}_y_map, resize_nn_{case.name}_x_map}},"
        )
    lines += ["};", ""]
    args.output.write_text("\n".join(lines), encoding="utf-8")
    # float_test_gen_utils.format_generated_file drags in torch; this script only needs clang-format.
    formatter = os.getenv("CLANG_FORMAT") or shutil.which("clang-format")
    if formatter is None:
        raise RuntimeError("clang-format not found; set CLANG_FORMAT")
    subprocess.run([formatter, "-i", str(args.output)], check=True)
    print(f"wrote {args.output} ({len(CASES)} cases)")


if __name__ == "__main__":
    main()
