// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_1_output_mult[5] = {1659588864, 1720079232, 1711470720, 1132782848, 1579355136};
