// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_1_weights[25] = {127, -99, 95, -26, 103, 46,  23, -50, -18, 127, -7,  117, 127,
                                                   108, 14,  54, -37, 47,  127, 48, 127, 0,   31,  -93, -10};
