// Generated by test_settings.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t int16xint8_group_depthwise_output_mult[8] =
    {1103835325, 1792651086, 1141049720, 1089611888, 2072106383, 1128090105, 2059807940, 1953091174};
