// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t int16xint8_group_depthwise_output_mult[8] =
    {1363244544, 1260762112, 1353335680, 1334868096, 1173337344, 1365864192, 2031829760, 1253770624};
