// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t basic_1d_valid_40ch_30w_bias[40] = {
    -23785, 37534,  18529,  -17320, 28702, -12534, -9071,  -23636, -322,   -13812, 28909, 21468, -31277, 19999,
    33727,  10005,  -24345, -15902, 33435, -651,   -17369, 81554,  33664,  35315,  36968, 16002, 24844,  -39279,
    24637,  -13108, -26215, -31742, -1220, 32619,  -40722, -26729, -27762, -28363, 10626, 10364};

const int32_t *const basic_1d_valid_40ch_30w_biases = basic_1d_valid_40ch_30w_bias;
