// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t basic_1d_valid_40ch_30w_output_shift[40] = {
    -10, -9,  -9, -9, -9, -9, -9, -9,  -9, -9, -9, -11, -9, -9,  -9,  -9, -9, -10, -10, -9,
    -9,  -10, -9, -9, -9, -9, -9, -10, -9, -9, -9, -9,  -9, -10, -10, -9, -9, -10, -9,  -9};
