// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_1_input[16] = {-78, -21, -123, -111, 31, 115, -11, 47, 46, -81, 92, -105, -41, 71, -6, 36};
