// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_1_weights[36] = {-23,  -127, 22, 14,  -10, -64, 17,  -125, 54,  -119, -42,  -14,
                                         127,  -103, 34, -69, 100, 81,  -63, 60,   65,  104,  15,   64,
                                         -103, 39,   75, 118, -77, -84, 96,  -27,  125, 8,    -127, 50};
