// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t resize_nn_batch_channels_s8_input_tensor[32] = {-127, 37,  17,   -99,  -1,  3,    12, 55,  77,  -7, -124,
                                                             -99,  20,  -117, -119, -87, -122, 73, 125, 54,  85, -4,
                                                             -18,  112, 9,    -125, -85, 107,  26, -79, -41, 57};
