// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_out_activation_input[36] = {42,  -101, -52, -97, -15, 74,   -111, -26,  -107, 119, -77, -44,
                                              45,  -128, -96, -72, 115, -107, 107,  -115, 110,  28,  1,   109,
                                              -64, -41,  59,  104, -42, -19,  80,   53,   -80,  -60, -6,  -23};
