// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_out_activation_output_ref[18] =
    {86, -33, 79, -58, 78, -44, 93, -15, 73, -34, 29, -8, 57, -32, 53, -33, 26, -15};
