// Auto-generated by generate_transpose_conv_s16_data.py
#pragma once
#include <stdint.h>

static const int64_t transpose_conv_s16_3_biases[] = {
  625258LL, -46566LL, 690636LL, 469270LL, 714194LL, -639023LL
};
