// Generated by test_settings.py using tensorflow version 2.20.0 (Keras version 3.13.0).
// Interpreter from tensorflow version 2.20.0 and revision v2.20.0-rc0-4-g72fbba3d20f.
#pragma once
#include <stdint.h>

const int32_t transpose_conv_s16_3_output_mult[7] =
    {2112214335, 2133174571, 2089750688, 2143573668, 1075120157, 2137057873, 2119175430};
