// Auto-generated by generate_transpose_conv_s16_data.py
#pragma once
#include <stdint.h>

static const int32_t transpose_conv_s16_2_output_mult[] = {
  1193420797, 1227458415, 1194743675, 1227331119
};
