// Auto-generated by generate_transpose_conv_s16_data.py
#pragma once

#include "config_data.h"
#include "input_data.h"
#include "weights_data.h"
#include "biases_data.h"
#include "output_mult_data.h"
#include "output_shift_data.h"
#include "output_ref_data.h"
