// SPDX-FileCopyrightText: 2026 Ambiq
// SPDX-License-Identifier: Apache-2.0
// Generated by generate_arg_extrema_data.py; shape [2,3,2,5].
#pragma once
static const AE_BITS ae_golden_input[] = {
0x4710, 0x4c90, 0x3400, 0xccac, 0xc938, 0x4890, 0xcaa8, 0xbe40, 0xcb60, 0xc1c0, 0x49f0, 0xc6c0, 0x4b80, 0xcb30, 0xcc88, 0x47b0, 0xc5d0, 0xc6d0, 0x4b48, 0xb000, 0x4780, 0xc930, 0x4928, 0xc780, 0x4888, 0xc540, 0x3b80, 0x4ab0, 0x3980, 0xcb80, 0x4b28, 0xc948, 0xcab8, 0x49b8, 0x4280, 0x49c8, 0xbec0, 0x4340, 0xc600, 0x4670, 0x4400, 0x4380, 0xb400, 0x44d0, 0x4530, 0xc890, 0x4c64, 0xc2e0, 0xca78, 0xc260, 0xcc68, 0x40c0, 0xc9e8, 0xc080, 0x4c8c, 0x44a0, 0xc838, 0x4980, 0x4b18, 0xc200
};
static const int32_t ae_min_axis0[] = {
0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0
};
static const int32_t ae_min_axis1[] = {
0, 2, 0, 0, 1, 2, 0, 1, 0, 2, 2, 0, 0, 2, 0, 1, 2, 1, 1, 1
};
static const int32_t ae_min_axis2[] = {
0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1
};
static const int32_t ae_min_axis3[] = {
3, 3, 4, 2, 1, 4, 2, 3, 2, 3, 0, 1
};
static const int32_t ae_max_axis0[] = {
1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1
};
static const int32_t ae_max_axis1[] = {
1, 0, 1, 2, 2, 0, 2, 2, 1, 1, 0, 1, 1, 0, 2, 0, 1, 2, 2, 0
};
static const int32_t ae_max_axis2[] = {
1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0
};
static const int32_t ae_max_axis3[] = {
1, 0, 2, 3, 2, 2, 0, 0, 4, 1, 4, 3
};
