// SPDX-FileCopyrightText: 2026 Ambiq
// SPDX-License-Identifier: Apache-2.0
// Generated by generate_arg_extrema_data.py; shape [2,3,2,5].
#pragma once
static const AE_BITS ae_golden_input[] = {
0x40e20000, 0x41920000, 0x3e800000, 0xc1958000, 0xc1270000, 0x41120000, 0xc1550000, 0xbfc80000, 0xc16c0000, 0xc0380000, 0x413e0000, 0xc0d80000, 0x41700000, 0xc1660000, 0xc1910000, 0x40f60000, 0xc0ba0000, 0xc0da0000, 0x41690000, 0xbe000000, 0x40f00000, 0xc1260000, 0x41250000, 0xc0f00000, 0x41110000, 0xc0a80000, 0x3f700000, 0x41560000, 0x3f300000, 0xc1700000, 0x41650000, 0xc1290000, 0xc1570000, 0x41370000, 0x40500000, 0x41390000, 0xbfd80000, 0x40680000, 0xc0c00000, 0x40ce0000, 0x40800000, 0x40700000, 0xbe800000, 0x409a0000, 0x40a60000, 0xc1120000, 0x418c8000, 0xc05c0000, 0xc14f0000, 0xc04c0000, 0xc18d0000, 0x40180000, 0xc13d0000, 0xc0100000, 0x41918000, 0x40940000, 0xc1070000, 0x41300000, 0x41630000, 0xc0400000
};
static const int32_t ae_min_axis0[] = {
0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0
};
static const int32_t ae_min_axis1[] = {
0, 2, 0, 0, 1, 2, 0, 1, 0, 2, 2, 0, 0, 2, 0, 1, 2, 1, 1, 1
};
static const int32_t ae_min_axis2[] = {
0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1
};
static const int32_t ae_min_axis3[] = {
3, 3, 4, 2, 1, 4, 2, 3, 2, 3, 0, 1
};
static const int32_t ae_max_axis0[] = {
1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1
};
static const int32_t ae_max_axis1[] = {
1, 0, 1, 2, 2, 0, 2, 2, 1, 1, 0, 1, 1, 0, 2, 0, 1, 2, 2, 0
};
static const int32_t ae_max_axis2[] = {
1, 0, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0
};
static const int32_t ae_max_axis3[] = {
1, 0, 2, 3, 2, 2, 0, 0, 4, 1, 4, 3
};
