# SPDX-FileCopyrightText: 2026 Ambiq
# SPDX-License-Identifier: Apache-2.0
"""Generate finite NumPy arg-index goldens from the rounded input dtype."""
from pathlib import Path
import numpy as np

root = Path(__file__).resolve().parent
values = np.random.default_rng(487123).integers(-300, 301, size=(2, 3, 2, 5)) / 16
for dtype, bits in [(np.float16, np.uint16), (np.float32, np.uint32)]:
    data = values.astype(dtype)
    name = "f16" if dtype is np.float16 else "f32"
    lines = ["// SPDX-FileCopyrightText: 2026 Ambiq", "// SPDX-License-Identifier: Apache-2.0",
             "// Generated by generate_arg_extrema_data.py; shape [2,3,2,5].", "#pragma once",
             "static const AE_BITS ae_golden_input[] = {",
             ", ".join(hex(int(x)) for x in data.view(bits).ravel()), "};"]
    for op, func in [("min", np.argmin), ("max", np.argmax)]:
        for axis in range(4):
            lines += [f"static const int32_t ae_{op}_axis{axis}[] = {{",
                      ", ".join(str(int(x)) for x in func(data, axis=axis).ravel()), "};"]
    (root / f"arg_extrema_{name}_data.h").write_text("\n".join(lines) + "\n")
