#!/usr/bin/env python3
# SPDX-FileCopyrightText: Copyright 2026 Ambiq
# SPDX-License-Identifier: Apache-2.0
"""Generate finite numpy extrema goldens, independent of CORE. Refs #498."""
from pathlib import Path
import numpy as np

shape = (2, 3, 5, 7)
values = (((np.arange(np.prod(shape)) * 37) % 251) - 125).reshape(shape) / 8
for dtype, bits in (("f16", 16), ("f32", 32)):
    data = values.astype(f"float{bits}")
    chunks = []
    offsets = [0]
    refs = {"min": [], "max": []}
    for mask in range(16):
        axes = tuple(i for i in range(4) if mask & (1 << i))
        for op in refs:
            result = getattr(np, op)(data, axis=axes, keepdims=True) if axes else data.copy()
            refs[op].extend(result.reshape(-1).view(f"uint{bits}").tolist())
        offsets.append(len(refs["min"]))
    def array(name, seq, ctype=f"uint{bits}_t"):
        lines = [f"static const {ctype} {name}[{len(seq)}] = {{"]
        for i in range(0, len(seq), 8):
            lines.append("    " + ", ".join(f"0x{x:0{bits // 4}x}" for x in seq[i:i + 8]) + ",")
        return "\n".join(lines) + "\n};\n"
    text = "/*\n * SPDX-FileCopyrightText: Copyright 2026 Ambiq\n * SPDX-License-Identifier: Apache-2.0\n * Generated by ../Utils/generate_reduce_extrema_data.py. Refs #498.\n */\n#pragma once\n#include <stdint.h>\n\n"
    text += array("re_golden_input", data.reshape(-1).view(f"uint{bits}").tolist())
    text += array("re_golden_offsets", offsets, "uint16_t")
    for op, ref in refs.items():
        text += array(f"re_golden_{op}", ref)
    (Path(__file__).parent / f"reduce_extrema_{dtype}_data.h").write_text(text)
