// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t int16xint8_group_batch2_dilated_bias[6] = {-3709433, 997315, -3849650, -3231086, 48812, 1250648};

const int32_t *const int16xint8_group_batch2_dilated_biases = int16xint8_group_batch2_dilated_bias;
