// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t int16xint8_group_batch2_dilated_output_multiplier[6] =
    {1982847804, 1478494007, 1503877147, 1457841023, 1341087981, 1517479173};

const int32_t *const int16xint8_group_batch2_dilated_output_mult = int16xint8_group_batch2_dilated_output_multiplier;
