// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t int16xint8_group_batch2_dilated_weights[72] = {
    -127, 97, -106, 68,  -124, 29,   67,  117, 31,  -94, -45, -82,  62,  58,  79, -38, 74,  53,
    85,   44, -93,  12,  116,  -127, -49, -34, -41, 56,  93,  -15,  59,  30,  52, -58, 120, 127,
    -68,  49, 57,   50,  -127, -97,  56,  -80, -58, 93,  63,  -108, -8,  -34, 68, -52, 96,  -92,
    -127, 91, 115,  -42, 76,   -31,  -21, 119, 17,  -14, 60,  -127, -53, 55,  27, 32,  87,  -113};
