// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t space_to_batch_nd_both_pad_s8_input_tensor[80] = {
    -112, 15, 41,   -69,  -62, 96,  -78, 31,  -18, 115,  -90,  -126, -80,  -123, 125, 61,   -96,  92,   -123, 107,
    56,   24, -113, 68,   -87, 96,  45,  8,   -39, -125, -56,  -24,  -12,  -90,  -65, -118, -118, -58,  -121, 73,
    46,   7,  111,  -69,  13,  -57, 32,  75,  -15, -37,  -110, -66,  -107, 60,   -64, -4,   111,  -118, 66,   30,
    -36,  81, 51,   -120, 27,  70,  -4,  111, 85,  -107, -43,  41,   87,   -92,  2,   73,   5,    66,   1,    11};
