// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once


#define SLICE_CASE3_INPUT_N    1
#define SLICE_CASE3_INPUT_H    4
#define SLICE_CASE3_INPUT_W    3
#define SLICE_CASE3_INPUT_C    2

#define SLICE_CASE3_BEGIN_N    0
#define SLICE_CASE3_BEGIN_H    1
#define SLICE_CASE3_BEGIN_W    0
#define SLICE_CASE3_BEGIN_C    0

#define SLICE_CASE3_END_N      1
#define SLICE_CASE3_END_H      4
#define SLICE_CASE3_END_W      3
#define SLICE_CASE3_END_C      2

#define SLICE_CASE3_STRIDES_N  1
#define SLICE_CASE3_STRIDES_H  2
#define SLICE_CASE3_STRIDES_W  1
#define SLICE_CASE3_STRIDES_C  1

#define SLICE_CASE3_OUTPUT_SIZE 12
#define SLICE_CASE3_OUTPUT_N    1
#define SLICE_CASE3_OUTPUT_H    2
#define SLICE_CASE3_OUTPUT_W    3
#define SLICE_CASE3_OUTPUT_C    2
