// Generated by generate_test_data.py using flatc version 25.2.10
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t fully_connected_int4_2_input_tensor[84] = {
    44,  -79,  -45, 124, 74,   60,   111,  -51, -76,  113, 79,  -107, 32,  -2,  71,   60,  -2,  -26, 58,   44,   122,
    39,  -108, 2,   32,  15,   23,   -76,  31,  -126, -16, 124, 70,   42,  118, 17,   105, 119, 78,  -26,  -120, -59,
    -21, 58,   81,  -35, -118, 11,   68,   -77, 114,  -25, 8,   43,   -40, 17,  53,   -16, 81,  64,  27,   77,   12,
    51,  44,   98,  87,  120,  -109, -124, 49,  -123, -15, 80,  -10,  -15, 62,  -113, -66, -27, 70,  -102, 1,    104};
