// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t reduce_min_axis_h_s8_input_tensor[16] =
    {10, -71, -99, 73, -46, 43, -61, 45, 20, -102, -26, -104, 14, 80, -82, -121};
