// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mean_axis_hwc_s8_input_tensor[72] = {
    -1,   123, 57,   -23, 105, -66, 85, -6,  99,   78,   -102, 13,   -65,  -60, 70,  54,  0,    74,
    53,   75,  -43,  -66, -6,  79,  77, 81,  -100, 97,   -54,  -106, 52,   23,  88,  27,  -63,  86,
    -44,  107, -102, -82, 3,   81,  30, -63, -12,  -74,  -59,  -67,  -35,  -89, -30, 8,   -127, 42,
    -101, 79,  -83,  55,  -38, 60,  69, 44,  -118, -116, -62,  -3,   -106, 8,   88,  125, 9,    13};
