// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t int16xint8_1x1_ns_np_nd_weights[32] = {-127, 61,   -39,  -69, 105, -16, 61,  -127, -127, 83, -64,
                                                    -120, -125, -127, 9,   112, -65, -83, -127, 49,   81, -119,
                                                    116,  127,  30,   -36, 50,  127, 109, -127, -48,  86};
