// Generated by test_settings.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t int16xint8_group_depthwise_3x3_stride_dilation_weights[36] = {
    -69, 86,  40,   -80, -88, -127, -31,  -4, 67,  13,   -68, 36, 70, 127, -1,  -107, -88, 16,
    -98, 112, -116, -35, -40, 96,   -127, 41, -12, -110, 53,  49, 6,  127, -10, -111, 126, -70};
