// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once
#include <stdint.h>

const int8_t squared_difference_broadcast_c_s8_output[24] = {-109, -90,  -98,  -126, -97,  -92, 3,    0,
                                                             -35,  -128, -124, -107, -121, -91, -69,  -125,
                                                             -119, -126, -126, 39,   -67,  -75, -127, -92};

const int8_t *const squared_difference_broadcast_c_s8_output_ref = squared_difference_broadcast_c_s8_output;
