// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t sub_scalar_s8_output[24] = {47, 13, 8,  24, 56, 60, -2, -2, 39, -48, -14, 15,
                                         0,  45, -2, -2, -2, -2, -2, -2, -2, -2,  -2,  -2};

const int8_t *const sub_scalar_s8_output_ref = sub_scalar_s8_output;
