// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t depthwise_single_in_many_out_ch_bias[12] =
    {-20594, 23279, 9783, 2603, -1995, -18400, -28902, -2171, -19318, 12179, 23815, -26764};

const int32_t *const depthwise_single_in_many_out_ch_biases = depthwise_single_in_many_out_ch_bias;
