// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define BROADCAST_TO_SCALAR_CUBE_S16_FORCE_NO_QUANTIZE true
#define BROADCAST_TO_SCALAR_CUBE_S16_INPUT_SHAPE                                                                       \
    {                                                                                                                  \
        1, 1, 1,                                                                                                       \
    }
#define BROADCAST_TO_SCALAR_CUBE_S16_OUTPUT_SHAPE                                                                      \
    {                                                                                                                  \
        2, 2, 2,                                                                                                       \
    }
#define BROADCAST_TO_SCALAR_CUBE_S16_INPUT_VALUES                                                                      \
    {                                                                                                                  \
        -700,                                                                                                          \
    }
#define BROADCAST_TO_SCALAR_CUBE_S16_RANK 3
#define BROADCAST_TO_SCALAR_CUBE_S16_INPUT_SIZE 1
#define BROADCAST_TO_SCALAR_CUBE_S16_OUTPUT_SIZE 8
