// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define MIRROR_PAD_REFLECT_S8_FORCE_NO_QUANTIZE true
#define MIRROR_PAD_REFLECT_S8_INPUT_SHAPE                                                                              \
    {                                                                                                                  \
        3,                                                                                                             \
    }
#define MIRROR_PAD_REFLECT_S8_PAD_BEFORE                                                                               \
    {                                                                                                                  \
        2,                                                                                                             \
    }
#define MIRROR_PAD_REFLECT_S8_MODE 0
#define MIRROR_PAD_REFLECT_S8_INPUT_VALUES                                                                             \
    {                                                                                                                  \
        1, 2, 3,                                                                                                       \
    }
#define MIRROR_PAD_REFLECT_S8_RANK 1
#define MIRROR_PAD_REFLECT_S8_INPUT_SIZE 3
#define MIRROR_PAD_REFLECT_S8_OUTPUT_SIZE 7
#define MIRROR_PAD_REFLECT_S8_OUTPUT_SHAPE                                                                             \
    {                                                                                                                  \
        7,                                                                                                             \
    }
