// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once

#define SQRT_SMALL_TENSOR_S8_INPUT_MIN 0
#define SQRT_SMALL_TENSOR_S8_INPUT_MAX 127
#define SQRT_SMALL_TENSOR_S8_BATCH_SIZE 1
#define SQRT_SMALL_TENSOR_S8_HEIGHT_1 2
#define SQRT_SMALL_TENSOR_S8_WIDTH_1 3
#define SQRT_SMALL_TENSOR_S8_CHANNEL_1 4
#define SQRT_SMALL_TENSOR_S8_IN_DIM                                                                                    \
    {                                                                                                                  \
        1, 2, 3, 4,                                                                                                    \
    }
#define SQRT_SMALL_TENSOR_S8_OUTPUT_LEN 24
#define SQRT_SMALL_TENSOR_S8_INPUT_SCALE 0.4979014992713928
#define SQRT_SMALL_TENSOR_S8_INPUT_ZERO_POINT -128
#define SQRT_SMALL_TENSOR_S8_OUTPUT_SCALE 0.044187720865011215
#define SQRT_SMALL_TENSOR_S8_OUTPUT_ZERO_POINT -128
