// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once
#include <stdint.h>

const int8_t sqrt_small_tensor_s8_output[24] = {59, 100, 53, 59, 65, 77,  89, 52,  119, 73,  89, 84,
                                                97, 101, 75, 85, 90, 121, 79, 104, 94,  120, 73, 112};
