// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t gather_nd_slice_hw_s8_input_tensor[24] = {-115, 92, 79,  -47,  93, -51,  -105, -80, 17, -67, 108, 17,
                                                       21,   1,  119, -125, 46, -127, 83,   40,  29, -40, -5,  16};
