// Generated by generate_comparison_data.py
#pragma once
#include <stdint.h>

const int16_t comparison_equal_ident_s16_input_1_input_tensor[24] = {
    -3840, -3456, -3072, -2688, -2304, -1920, -1536, -1152, 

    -768, -384, 0, 384, 768, 1152, 1536, 1920, 

    2304, 2688, 3072, 3456, 3840, 4224, 4608, 4992
};
