// Generated by generate_comparison_data.py
#pragma once
#include <stdint.h>

const int16_t comparison_equal_ident_s16_input_2_input_tensor[24] = {
    -4096, -3456, -3072, -2688, -2304, -2176, -1536, -1152, 

    -768, -384, -256, 384, 768, 1152, 1536, 1664, 

    2304, 2688, 3072, 3456, 3584, 4224, 4608, 4992
};
