// Generated by generate_test_data.py using tensorflow version 2.18.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.18.0 and revision v2.18.0-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int16_t pad_int16_1_input_tensor[8] = {19083, 5985, 24188, -12758, 12665, 26931, -22364, -9786};
