// Generated by generate_test_data.py using tensorflow version 2.18.-128 (Keras version 3.8.-128).
// Interpreter from tensorflow version 2.18.-128 and revision v2.18.-128-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int16_t pad_int16_1_output[50] = {
    -128, -128, -128, -128, -128, -128, 19083, 5985,  -128, -128, -128, 24188,  -12758, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128,
    -128, -128, -128, -128, -128, -128, 12665, 26931, -128, -128, -128, -22364, -9786,  -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128
};
