// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define SCATTER_ND_ROWS_S8_FORCE_NO_QUANTIZE true
#define SCATTER_ND_ROWS_S8_OUTPUT_SHAPE                                                                                \
    {                                                                                                                  \
        3, 2,                                                                                                          \
    }
#define SCATTER_ND_ROWS_S8_NUM_UPDATES 2
#define SCATTER_ND_ROWS_S8_INDEX_DEPTH 1
#define SCATTER_ND_ROWS_S8_INDICES_VALUES                                                                              \
    {                                                                                                                  \
        0, 2,                                                                                                          \
    }
#define SCATTER_ND_ROWS_S8_UPDATES_VALUES                                                                              \
    {                                                                                                                  \
        1, 2, 3, 4,                                                                                                    \
    }
#define SCATTER_ND_ROWS_S8_SLICE_SIZE 2
#define SCATTER_ND_ROWS_S8_OUTPUT_SIZE 6
#define SCATTER_ND_ROWS_S8_OUTPUT_STRIDES                                                                              \
    {                                                                                                                  \
        2,                                                                                                             \
    }
