// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_2x3_dilation_input[18] =
    {125, -53, -33, 116, 27, -63, 121, -17, 79, 88, -11, 126, -61, 12, -50, -97, 82, -107};
