// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_2x3_dilation_output_ref[18] =
    {-61, 10, -61, 0, -61, 15, -61, 0, -61, 12, -61, 40, -58, 10, -61, 44, -61, 17};
