// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_biases[15] =
    {-18991, 26147, 11479, 30536, -9386, 6014, 2116, -7149, -18883, 6999, -13719, 18536, -16604, 10683, 11200};
