// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_y_output_mult[15] = {1161948160,
                                                      1180099456,
                                                      1176494080,
                                                      1158110208,
                                                      1182949888,
                                                      1145535104,
                                                      1100416256,
                                                      1192432512,
                                                      1166661248,
                                                      1158547840,
                                                      1182134656,
                                                      2123352960,
                                                      1169444864,
                                                      1153065472,
                                                      1182944768};
