// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once

#define SQRT_MULTI_BATCH_S8_INPUT_MIN 0
#define SQRT_MULTI_BATCH_S8_INPUT_MAX 127
#define SQRT_MULTI_BATCH_S8_BATCH_SIZE 2
#define SQRT_MULTI_BATCH_S8_HEIGHT_1 3
#define SQRT_MULTI_BATCH_S8_WIDTH_1 5
#define SQRT_MULTI_BATCH_S8_CHANNEL_1 3
#define SQRT_MULTI_BATCH_S8_IN_DIM                                                                                     \
    {                                                                                                                  \
        2, 3, 5, 3,                                                                                                    \
    }
#define SQRT_MULTI_BATCH_S8_OUTPUT_LEN 90
#define SQRT_MULTI_BATCH_S8_INPUT_SCALE 0.4978196918964386
#define SQRT_MULTI_BATCH_S8_INPUT_ZERO_POINT -128
#define SQRT_MULTI_BATCH_S8_OUTPUT_SCALE 0.04418409243226051
#define SQRT_MULTI_BATCH_S8_OUTPUT_ZERO_POINT -128
