// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once
#include <stdint.h>

const int8_t sqrt_multi_batch_s8_input_tensor[90] = {
    120, 118, 1,  125, 116, 4,  82,  78,  125, 106, 31,  112, 76,  89,  76,  49, 6,  68,  49, 72,  24, 15, 109,
    59,  14,  86, 23,  27,  79, 99,  122, 31,  20,  98,  104, 56,  123, 113, 92, 82, 63,  68, 83,  42, 15, 9,
    55,  31,  31, 122, 39,  93, 98,  24,  16,  48,  1,   74,  123, 40,  41,  75, 78, 102, 41, 118, 87, 28, 127,
    120, 97,  28, 51,  2,   29, 127, 103, 76,  50,  116, 87,  41,  83,  127, 76, 26, 113, 92, 66,  64};
