// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define CONCAT_AXIS_C_TWO_INPUTS_S32_BATCH_1 1
#define CONCAT_AXIS_C_TWO_INPUTS_S32_HEIGHT_1 2
#define CONCAT_AXIS_C_TWO_INPUTS_S32_WIDTH_1 3
#define CONCAT_AXIS_C_TWO_INPUTS_S32_CHANNEL_1 2
#define CONCAT_AXIS_C_TWO_INPUTS_S32_BATCH_2 1
#define CONCAT_AXIS_C_TWO_INPUTS_S32_HEIGHT_2 2
#define CONCAT_AXIS_C_TWO_INPUTS_S32_WIDTH_2 3
#define CONCAT_AXIS_C_TWO_INPUTS_S32_CHANNEL_2 1
#define CONCAT_AXIS_C_TWO_INPUTS_S32_AXIS 3
#define CONCAT_AXIS_C_TWO_INPUTS_S32_INPUTS_COUNT 2
#define CONCAT_AXIS_C_TWO_INPUTS_S32_OUTPUT_DIMS 4
#define CONCAT_AXIS_C_TWO_INPUTS_S32_OUTPUT_SHAPE                                                                      \
    {                                                                                                                  \
        1, 2, 3, 3,                                                                                                    \
    }
#define CONCAT_AXIS_C_TWO_INPUTS_S32_INPUT_CONCAT_DIMS                                                                 \
    {                                                                                                                  \
        2, 1,                                                                                                          \
    }
#define CONCAT_AXIS_C_TWO_INPUTS_S32_OUTPUT_SIZE 18
#define CONCAT_AXIS_C_TWO_INPUTS_S32_OUTPUT_N 1
#define CONCAT_AXIS_C_TWO_INPUTS_S32_OUTPUT_H 2
#define CONCAT_AXIS_C_TWO_INPUTS_S32_OUTPUT_W 3
#define CONCAT_AXIS_C_TWO_INPUTS_S32_OUTPUT_C 3
