// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t concat_axis_c_two_inputs_s32_input_tensor_1[12] = {785722867,
                                                                 -503716352,
                                                                 1525279019,
                                                                 -2096252000,
                                                                 -633850688,
                                                                 -772158381,
                                                                 -1484942276,
                                                                 -1272196835,
                                                                 2039955582,
                                                                 -1818910296,
                                                                 -1171939360,
                                                                 808881897};
