// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t add_broadcast_hc_s16_output[24] = {6079, 15722, 12144, 49, 13989, 4418, 14999, 0,  16, 0, 0, 0,
                                                 6030, 15673, 12096, 0,  14013, 4442, 15023, 24, 16, 0, 0, 0};

const int16_t *const add_broadcast_hc_s16_output_ref = add_broadcast_hc_s16_output;
