// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define RESIZE_NN_DOWNSAMPLE_S16_INPUT_N 1
#define RESIZE_NN_DOWNSAMPLE_S16_INPUT_H 7
#define RESIZE_NN_DOWNSAMPLE_S16_INPUT_W 6
#define RESIZE_NN_DOWNSAMPLE_S16_INPUT_C 3
#define RESIZE_NN_DOWNSAMPLE_S16_OUTPUT_H 3
#define RESIZE_NN_DOWNSAMPLE_S16_OUTPUT_W 4
#define RESIZE_NN_DOWNSAMPLE_S16_ALIGN_CORNERS false
#define RESIZE_NN_DOWNSAMPLE_S16_HALF_PIXEL_CENTERS false
#define RESIZE_NN_DOWNSAMPLE_S16_ASYMMETRIC_QUANTIZE_INPUTS 0
#define RESIZE_NN_DOWNSAMPLE_S16_OUTPUT_N 1
#define RESIZE_NN_DOWNSAMPLE_S16_OUTPUT_C 3
#define RESIZE_NN_DOWNSAMPLE_S16_OUTPUT_SIZE 36
#define RESIZE_NN_DOWNSAMPLE_S16_OUTPUT_SIZE_N 1
#define RESIZE_NN_DOWNSAMPLE_S16_OUTPUT_SIZE_H 1
#define RESIZE_NN_DOWNSAMPLE_S16_OUTPUT_SIZE_W 1
#define RESIZE_NN_DOWNSAMPLE_S16_OUTPUT_SIZE_C 2
#define RESIZE_NN_DOWNSAMPLE_S16_OUTPUT_SIZE_DATA                                                                      \
    {                                                                                                                  \
        3, 4,                                                                                                          \
    }
