// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t resize_nn_downsample_s16_output[36] = {
    -10892, -3963, 32607,  -11651, -27214, -29310, 9360,   25431,  18598, -16849, 6419,   26530,
    -24382, 27889, -26695, -7023,  -22386, -728,   -25665, -21830, 5699,  23629,  -23763, -16793,
    10091,  12342, -12019, -12858, 27723,  -14841, 29269,  7135,   -2962, 23519,  -13430, 30961};
