// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t prelu_alpha_height_broadcast_s8_alpha_input_tensor[12] =
    {40, 17, 40, -92, -9, 56, -17, -17, -26, 37, 24, -61};
