// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t prelu_alpha_height_broadcast_s8_input_tensor[24] = {66,  -128, -128, 42,  -128, -79, -128, -128,
                                                                 112, -128, -128, -53, -128, 86,  65,   -126,
                                                                 79,  -128, -128, -25, -128, -30, -128, -128};
