// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t add_ident_s16_output[24] = {14082, 4389, 14901, 0, -16240, 15613, 12017, 0, 0, 0, 0, 0,
                                          0,     0,    0,     0, 0,      0,     0,     0, 0, 0, 0, 0};

const int16_t *const add_ident_s16_output_ref = add_ident_s16_output;
