// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define WHERE_ALL_TRUE_2D_S8_FORCE_NO_QUANTIZE true
#define WHERE_ALL_TRUE_2D_S8_SHAPE                                                                                     \
    {                                                                                                                  \
        2, 2,                                                                                                          \
    }
#define WHERE_ALL_TRUE_2D_S8_CONDITION_VALUES                                                                          \
    {                                                                                                                  \
        1, -1, 2, 3,                                                                                                   \
    }
#define WHERE_ALL_TRUE_2D_S8_RANK 2
#define WHERE_ALL_TRUE_2D_S8_SIZE 4
#define WHERE_ALL_TRUE_2D_S8_COND_SIZE 4
