// Generated by test data script for arm_sqrt_s16 unit tests.
#pragma once
#include <stdint.h>

const int16_t sqrt_tail_mod7_s16_input_tensor[15] = {
    127, 126, 125, 124, 123, 122, 121, 120,
    11408, 119, 115, 113, 112, 127, 127};
