// Generated by test data script for arm_sqrt_s16 unit tests.
#pragma once
#include <stdint.h>

const int16_t sqrt_tail_mod7_s16_output[15] = {
    653, 649, 644, 640, 635, 630, 626, 621,
    6162, 616, 598, 589, 584, 653, 653};
