// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t abs_long_row_s16_output[48] = {
    5115,  10814, 15193, 31380, 32419, 24152, 22872, 18206, 28246, 32514, 12288, 4177,  7192,  7490,  4327,  31797,
    12021, 31950, 6757,  20329, 12062, 22439, 18694, 29935, 24140, 29870, 3767,  8889,  3667,  28979, 1900,  19378,
    21958, 32,    24948, 19608, 13172, 23189, 8041,  24382, 13487, 14542, 2544,  29168, 32576, 31890, 11748, 8842};
