// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t batch_to_space_nd_nsquare_crops_s16_input_tensor[54] = {
    60,   -15, 42, 73,   -124, -81, 92, 56,  -110, 6,   35,  110, 93,  -108, -108, 1,  -120, 73,
    -122, 104, 9,  -15,  87,   -55, -1, 82,  -24,  -36, -53, 33,  -20, -25,  -68,  96, 122,  -125,
    2,    -42, 94, -107, -105, 97,  61, -11, -107, 66,  117, 116, 54,  -62,  -80,  -3, -47,  60};
