// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t batch_to_space_nd_nsquare_crops_s16_output[27] = {-36, 2,    66,  -53,  -42,  117, 33,  94,   116,
                                                               73,  93,   -15, -124, -108, 87,  -81, -108, -55,
                                                               -20, -107, 54,  -25,  -105, -62, -68, 97,   -80};
