// Generated by test data script for arm_sqrt_s16 unit tests.
#pragma once

#define SQRT_TAIL_MOD5_S16_BATCH_SIZE 1
#define SQRT_TAIL_MOD5_S16_HEIGHT_1 1
#define SQRT_TAIL_MOD5_S16_WIDTH_1 1
#define SQRT_TAIL_MOD5_S16_CHANNEL_1 13
#define SQRT_TAIL_MOD5_S16_IN_DIM                                                                                      \
    {                                                                                                                  \
        1, 1, 1, 13,                                                                                                   \
    }
#define SQRT_TAIL_MOD5_S16_OUTPUT_LEN 13
#define SQRT_TAIL_MOD5_S16_INPUT_SCALE 0.00028f
#define SQRT_TAIL_MOD5_S16_INPUT_ZERO_POINT 0
#define SQRT_TAIL_MOD5_S16_OUTPUT_SCALE 0.00029f
#define SQRT_TAIL_MOD5_S16_OUTPUT_ZERO_POINT 0
