// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t reduce_min_axis_n_s16_input_tensor[48] = {
    22786, -15928, 23837,  -31239, 23677,  -15856, 14059, 4058,  5796,   -29773, -3280,  19099,
    -8765, 11062,  -25335, -12002, -28266, -2613,  -3226, 16176, -30854, 5364,   -2521,  9432,
    17352, 4131,   -13183, 23047,  -2429,  -22722, 18057, 20295, -30270, -20254, -10889, 13142,
    19447, -3876,  -11354, -8992,  -7243,  17518,  -2080, 2546,  24572,  19911,  -16927, -20561};
