// Generated by generate_comparison_data.py
#pragma once
#include <stdbool.h>

const bool comparison_less_broadcast_c_s16_output[24] = {
    true, false, false, false, false, false, false, false, 

    false, false, false, false, false, false, false, false, 

    false, false, false, false, false, false, false, false
};

const bool *const comparison_less_broadcast_c_s16_output_ref = comparison_less_broadcast_c_s16_output;
