// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t mean_axis_wc_s16_output[20] = {5434,  4226,  2432, 5969, -9934, 3283, 1986,  2476, -3275, 11045,
                                             -1055, -6877, 1458, 3770, 9607,  -618, -1666, 3721, 6154,  2560};
