// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_2x2_dilation_output_ref[72] = {
    -61, -61, -61, -61, 61,  -61, -61, 107, -58, -19, -21, 7,   -61, 107, -61, 48,  -61, 107,
    -61, -61, 56,  -58, -61, -39, -61, -34, -23, -23, -61, -61, -61, -61, -61, -61, -61, 0,
    -61, -61, -61, 20,  -61, -61, -61, -61, -41, 107, -61, -44, 44,  -61, 97,  -61, -61, 48,
    -61, -41, -61, 107, -61, -61, -61, 107, -61, 65,  -61, 107, -60, -61, -61, -61, -61, -61};
