// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_2x2_dilation_weights[36] = {8,   -84, -64, -127, -125, 117, 103,  67,  101, -22, -77, -1,
                                              -75, 76,  30,  4,    -17,  116, -96,  69,  76,  -64, 121, -44,
                                              91,  -13, 41,  4,    31,   -81, -127, -11, 107, 5,   77,  45};
