// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t reduce_min_axis_h_s16_output[8] = {-11399, 20505, -26128, -23724, -31590, 13684, -8880, 5110};
