// Generated by generate_reduce_sum_s16_test_data.py
#pragma once
#include <stdint.h>

const int16_t reduce_sum_s16_test_input_tensor[16] = {
  30447, 7891, -32119, 10873, -20541, 17895, -1967, -5058,
  15569, 9764, 28753, 32767, 27491, 8992, 27930, 11862
};
