// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define BROADCAST_TO_MID_DIM_S16_FORCE_NO_QUANTIZE true
#define BROADCAST_TO_MID_DIM_S16_INPUT_SHAPE                                                                           \
    {                                                                                                                  \
        2, 1, 3,                                                                                                       \
    }
#define BROADCAST_TO_MID_DIM_S16_OUTPUT_SHAPE                                                                          \
    {                                                                                                                  \
        2, 4, 3,                                                                                                       \
    }
#define BROADCAST_TO_MID_DIM_S16_INPUT_VALUES                                                                          \
    {                                                                                                                  \
        100, -200, 300, 400, -500, 600,                                                                                \
    }
#define BROADCAST_TO_MID_DIM_S16_RANK 3
#define BROADCAST_TO_MID_DIM_S16_INPUT_SIZE 6
#define BROADCAST_TO_MID_DIM_S16_OUTPUT_SIZE 24
