// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define SPACE_TO_BATCH_ND_BATCH_S16_IN_DIM                                                                             \
    {                                                                                                                  \
        2, 8, 6, 2,                                                                                                    \
    }
#define SPACE_TO_BATCH_ND_BATCH_S16_BLOCK_SHAPE                                                                        \
    {                                                                                                                  \
        2, 1,                                                                                                          \
    }
#define SPACE_TO_BATCH_ND_BATCH_S16_PADDINGS                                                                           \
    {                                                                                                                  \
        0, 0, 0, 0,                                                                                                    \
    }
#define SPACE_TO_BATCH_ND_BATCH_S16_OUT_DIM                                                                            \
    {                                                                                                                  \
        4, 4, 6, 2,                                                                                                    \
    }
#define SPACE_TO_BATCH_ND_BATCH_S16_PAD_NHWC4                                                                          \
    {                                                                                                                  \
        0, 0, 0, 0,                                                                                                    \
    }
#define SPACE_TO_BATCH_ND_BATCH_S16_INPUT_SIZE 192
#define SPACE_TO_BATCH_ND_BATCH_S16_OUTPUT_SIZE 192
#define SPACE_TO_BATCH_ND_BATCH_S16_INPUT_OFFSET 0
#define SPACE_TO_BATCH_ND_BATCH_S16_OUTPUT_OFFSET 0
