// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_5_input[68] = {-71,  10,   -117, -121, -54,  -15,  100, 23,  -2,   21,  82,  -21,  30,  -18,
                                       99,   86,   120,  116,  45,   117,  92,  -10, -118, 43,  64,  -38,  -23, 115,
                                       9,    93,   -89,  61,   47,   30,   2,   34,  123,  -24, -14, -1,   61,  -114,
                                       -122, 90,   19,   77,   60,   -99,  79,  72,  108,  10,  58,  -114, 56,  -91,
                                       -102, -112, 15,   13,   -107, -126, 40,  16,  -93,  -64, -49, -11};
