// Generated by generate_test_data.py using tensorflow version 2.18.-128 (Keras version 3.8.-128).
// Interpreter from tensorflow version 2.18.-128 and revision v2.18.-128-rc2-4-g6550e4bd802.
#pragma once
#include <stdint.h>

const int16_t pad_int16_2_output[50] = {
    -128,    -128,      -128,      -128, -128, -128, -128, -128, -128, -128,      -128,     -128,    -128,      -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -25145,
    4495, -10741, -28328, -128, -128, -128, -128, -128, -128, -30560, -3366, 2400, -31099, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128};
