// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t sub_ident_neg_offset_s8_output[24] = {77,  -23, 58, -51, 84,  0,   -37, -73, 16,  -92, 10, -13,
                                                   -35, 57,  0,  4,   -32, -43, 18,  27,  -25, -86, 28, -4};

const int8_t *const sub_ident_neg_offset_s8_output_ref = sub_ident_neg_offset_s8_output;
