// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t sub_ident_neg_offset_s8_rhs_input_tensor[24] = {
    -107, 27, 5, -25, -58, -1, 80, 27, 26, 55, -91, -59, 39, -121, -17, 92, 44, 125, 63, -114, 14, 51, -115, 93};
