// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t minimum_broadcast_ch_int16_input_tensor_1[16] = {-31912,
                                                               16134,
                                                               2273,
                                                               -17843,
                                                               -25054,
                                                               -21923,
                                                               21768,
                                                               -11439,
                                                               5190,
                                                               17222,
                                                               -11631,
                                                               -28818,
                                                               -20543,
                                                               22992,
                                                               -19738,
                                                               29294};
