// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tflite_micro runtime version 0.dev20250802032821-g14638b6.
#pragma once
#include <stdint.h>

const int8_t depth_to_space_min_depth_s8_input_tensor[36] = {-103, 90,  -44, 34, -21, 42,  103, -108, 111, 39, 80, 54,
                                                             -19,  -31, 47,  80, 0,   -40, 125, 33,   -88, 19, -2, -121,
                                                             3,    -72, -35, 98, 104, 23,  -56, -77,  49,  38, 87, 66};
