// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.4).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t int16xint8xint32_1x1_ch24_bias[7] = {1531790, 1738362, 2914965, 1165060, 283794, 2606879, 1293225};

const int32_t *const int16xint8xint32_1x1_ch24_biases = int16xint8xint32_1x1_ch24_bias;
