// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.4).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t int16xint8xint32_1x1_ch24_output[42] = {
    -10746, -645, 2304,  1855, 7204,  606,   -4314,  110,    160,   -9134, 9824,  4487,  5434,  3316,
    1188,   107,  10137, 5746, 3252,  -4365, -19702, 1702,   18086, 17401, 19119, -1182, 14198, -1077,
    17699,  3737, 17432, 4234, 11996, 15925, 9692,   -19869, 21529, -4578, -2764, 10227, 7956,  2435};

const int16_t *const int16xint8xint32_1x1_ch24_output_ref = int16xint8xint32_1x1_ch24_output;
