// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tflite_micro runtime version 0.dev20250802032821-g14638b6.
#pragma once
#include <stdint.h>

const int16_t space_to_depth_min_spatial_s16_output[20] = {86,  -5,  14, -115, -44, -92, 53, -12, 47,   -107,
                                                          -12, 100, 91, -95,  -35, -89, 1,  -14, -117, 108};
