// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once
#include <stdint.h>

const int8_t squared_difference_broadcast_h_s8_rhs_input_tensor[24] = {
    -33, -97, 18, -62, 41, 104, -41, 104, 64, 56, 19, -58, -57, 8, 8, 89, 19, 57, 78, 104, 118, -122, -97, 124};
