// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_2_output_ref[40] = {
    -79, 13, -40, 85, -27, -27, -19, -66, 49, -43, -63, 11, -31, 79,  -35, -71, 29, -50, 81, -31,
    -50, 15, -56, 66, -15, -78, 10,  -87, 87, -54, -99, 31, -40, 101, -39, -65, -7, -34, 77, -26};
