// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_y_2_weights[25] = {-127, 33, -73, -98, -42, 127, -30, 82, 91,   -103, 104, -94, -127,
                                                   -80,  -9, 127, -23, 85,  78,  31,  3,  -127, 36,   -54, -68};
