// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t space_to_batch_nd_basic_2x2_s16_input_tensor[72] = {
    49,  -40,  118, 39,  -81,  -28,  25,  3,   16,   -21, -100, -62, 94,   -110, 51,  84,  -122, 43,
    -13, 96,   -91, 75,  101,  -52,  77,  -66, 42,   109, -88,  17,  -100, 32,   -26, -37, -99,  45,
    -44, -127, 118, -51, -2,   -121, 36,  -7,  -125, -85, 43,   8,   121,  -76,  -34, -39, -117, -16,
    -87, 94,   53,  -56, -112, 97,   -26, 68,  15,   -72, 60,   3,   22,   40,   22,  3,   -51,  -90};
