// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t space_to_batch_nd_basic_2x2_s16_output[72] = {
    49, -40,  118, 25,  3,    16,  77,  -66,  42,   -100, 32,  -26,  121, -76,  -34, -87, 94,   53,
    39, -81,  -28, -21, -100, -62, 109, -88,  17,   -37,  -99, 45,   -39, -117, -16, -56, -112, 97,
    94, -110, 51,  -13, 96,   -91, -44, -127, 118,  36,   -7,  -125, -26, 68,   15,  22,  40,   22,
    84, -122, 43,  75,  101,  -52, -51, -2,   -121, -85,  43,  8,    -72, 60,   3,   3,   -51,  -90};
