// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t gather_axis_c_basic_s8_input_tensor[24] = {63, 16,  -90, -21, 15,  15,  15,  -76, 119, -35, -79, -99,
                                                        8,  -46, 61,  -61, -23, -33, -50, 22,  -77, 0,   -83, -83};
