// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t gather_axis_c_basic_s8_output[18] =
    {-21, 63, -90, -76, 15, 15, -99, 119, -79, -61, 8, 61, 22, -23, -50, -83, -77, -83};
