// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t kernel1x1_stride_x_output_mult[5] = {1200681984, 1194433280, 1997888000, 1324457344, 1278991104};
