// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t kernel1x1_stride_x_weights[45] = {
    -81, 30,  -47, -5, 31, 127, 32,  22, 31,  126, -8,   -7,   -122, -127, -37,  123, -93, 17,  -109, 10, -84, -123, -7,
    -73, 127, 58,  35, 92, 50,  -46, 83, -35, 107, -127, -110, -92,  10,   -127, -7,  -72, -97, 72,   19, 2,   -99};
