// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t space_to_batch_nd_bs1_identity_pad_s8_input_tensor[9] = {75, -11, -111, 59, -87, 100, -97, 17, -53};
