// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t space_to_batch_nd_bs1_identity_pad_s8_output[24] = {-128, -128, -128, -128, -128, -128, -128, -128,
                                                                 75,   -11,  -111, -128, -128, -128, 59,   -87,
                                                                 100,  -128, -128, -128, -97,  17,   -53,  -128};
