// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once

#define RELU6_BASIC_BATCH_SIZE 100
#define RELU6_BASIC_BATCH_1 1
#define RELU6_BASIC_HEIGHT_1 1
#define RELU6_BASIC_WIDTH_1 10
#define RELU6_BASIC_CHANNEL_1 1
#define RELU6_BASIC_PAD SAME
#define RELU6_BASIC_INPUT_MIN -128
#define RELU6_BASIC_INPUT_MAX 127
#define RELU6_BASIC_LOWER 0
#define RELU6_BASIC_UPPER 6
#define RELU6_BASIC_OUTPUT_LEN 10
