// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mul_broadcast_w_s8_output[24] = {-63, -63, -63, -63, -63, -63, -63, -63, -63, -63, -63, -63,
                                              -63, -63, -63, -63, -63, -63, -63, -63, -63, -63, -63, -63};

const int8_t *const mul_broadcast_w_s8_output_ref = mul_broadcast_w_s8_output;
