// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t grouped_conv_2_output_ref[28] = {-12,  127, 105, 123, -128, 108, 23,  127, 17,  67,  -103, 66,  -128, 127,
                                              -128, 127, -27, 126, -19,  127, -27, 127, -29, 127, -50,  127, 15,   81};
