// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t relu_basic_output[10] = {
    1, 2, 3, 4, 5, 0, 0, 0, 0, 0
};
