// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define GATHER_NEG_AXIS_WIDE_S8_INPUT_DIM                                                                              \
    {                                                                                                                  \
        1, 2, 4, 3,                                                                                                    \
    }
#define GATHER_NEG_AXIS_WIDE_S8_INPUT_RANK 4
#define GATHER_NEG_AXIS_WIDE_S8_INDICES_DIM                                                                            \
    {                                                                                                                  \
        3, 1, 1, 1,                                                                                                    \
    }
#define GATHER_NEG_AXIS_WIDE_S8_INDICES_RANK 1
#define GATHER_NEG_AXIS_WIDE_S8_INDICES_VALUES                                                                         \
    {                                                                                                                  \
        0, 3, 1,                                                                                                       \
    }
#define GATHER_NEG_AXIS_WIDE_S8_AXIS -2
#define GATHER_NEG_AXIS_WIDE_S8_BATCH_DIMS 0
#define GATHER_NEG_AXIS_WIDE_S8_INPUT_N 1
#define GATHER_NEG_AXIS_WIDE_S8_INPUT_H 2
#define GATHER_NEG_AXIS_WIDE_S8_INPUT_W 4
#define GATHER_NEG_AXIS_WIDE_S8_INPUT_C 3
#define GATHER_NEG_AXIS_WIDE_S8_INDICES_N 3
#define GATHER_NEG_AXIS_WIDE_S8_INDICES_H 1
#define GATHER_NEG_AXIS_WIDE_S8_INDICES_W 1
#define GATHER_NEG_AXIS_WIDE_S8_INDICES_C 1
#define GATHER_NEG_AXIS_WIDE_S8_COORDS_RANK 1
#define GATHER_NEG_AXIS_WIDE_S8_INDICES_LENGTH 3
#define GATHER_NEG_AXIS_WIDE_S8_OUTPUT_N 1
#define GATHER_NEG_AXIS_WIDE_S8_OUTPUT_H 2
#define GATHER_NEG_AXIS_WIDE_S8_OUTPUT_W 3
#define GATHER_NEG_AXIS_WIDE_S8_OUTPUT_C 3
#define GATHER_NEG_AXIS_WIDE_S8_OUTPUT_SIZE 18
