// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t gather_neg_axis_wide_s8_output[18] =
    {106, -113, -29, -106, 22, 113, -41, 17, 61, 32, -59, 30, -69, 48, -63, 123, 11, -72};
