// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t prelu_per_channel_s8_alpha_input_tensor[8] = {20, 53, -55, -72, -95, 12, -4, -47};
