// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t prelu_per_channel_s8_output[48] = {-128, -128, -128, -102, 77,   -128, -128, 39,   -127, -128, 115,  -107,
                                                12,   -128, -34,  -128, 96,   -128, -106, -128, -128, -89,  -128, 94,
                                                -119, -128, -27,  -128, -128, -128, -128, -128, -128, -128, -128, 39,
                                                -128, -128, -128, -52,  -75,  10,   -128, -128, -128, 93,   -128, -128};
