// Generated by test_settings.py using tensorflow version 2.20.0 (Keras version 3.13.0).
// Interpreter from tensorflow version 2.20.0 and revision v2.20.0-rc0-4-g72fbba3d20f.
#pragma once
#include <stdint.h>

const int64_t transpose_conv_s16_5_biases[6] = {3628793, -2021698, 3210544, -1262485, -2651605, -2475430};
