// Generated by test_settings.py using tensorflow version 2.20.0 (Keras version 3.13.0).
// Interpreter from tensorflow version 2.20.0 and revision v2.20.0-rc0-4-g72fbba3d20f.
#pragma once
#include <stdint.h>

const int32_t transpose_conv_s16_5_output_mult[6] =
    {1142326077, 1172602335, 1176453641, 2082240670, 1175011080, 1192698464};
