// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define REDUCE_MIN_AXIS_C_S16_IN_DIM                                                                                   \
    {                                                                                                                  \
        1, 2, 2, 4,                                                                                                    \
    }
#define REDUCE_MIN_AXIS_C_S16_AXIS                                                                                     \
    {                                                                                                                  \
        3,                                                                                                             \
    }
#define REDUCE_MIN_AXIS_C_S16_KEEP_DIMS true
#define REDUCE_MIN_AXIS_C_S16_OUT_DIM                                                                                  \
    {                                                                                                                  \
        1, 2, 2, 1,                                                                                                    \
    }
#define REDUCE_MIN_AXIS_C_S16_AXIS_DIM                                                                                 \
    {                                                                                                                  \
        0, 0, 0, 1,                                                                                                    \
    }
#define REDUCE_MIN_AXIS_C_S16_AXIS_MASK 1
#define REDUCE_MIN_AXIS_C_S16_INPUT_SIZE 16
#define REDUCE_MIN_AXIS_C_S16_OUTPUT_SIZE 4
#define REDUCE_MIN_AXIS_C_S16_INPUT_OFFSET 0
#define REDUCE_MIN_AXIS_C_S16_OUTPUT_OFFSET 0
#define REDUCE_MIN_AXIS_C_S16_OUTPUT_MULTIPLIER 1073741824
#define REDUCE_MIN_AXIS_C_S16_OUTPUT_SHIFT 1
#define REDUCE_MIN_AXIS_C_S16_REDUCTION_SIZE 4
