// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t reduce_min_axis_c_s16_input_tensor[16] =
    {10895, 27150, -28661, -22928, -12236, -16112, 29110, 4367, 25625, 21145, 17221, 30436, 14016, -8508, 27853, 5451};
