// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once
#include <stdint.h>

const int8_t squared_difference_broadcast_hc_s8_output[24] = {-85,  -124, -127, -67,  -128, -15,  -106, -125,
                                                              -127, 48,   -110, -122, -111, 29,   -32,  -120,
                                                              -124, 23,   -87,  -128, -40,  -119, -92,  -69};

const int8_t *const squared_difference_broadcast_hc_s8_output_ref = squared_difference_broadcast_hc_s8_output;
