// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once
#include <stdint.h>

const int8_t squared_difference_broadcast_hc_s8_rhs_input_tensor[12] =
    {-15, 118, 75, -35, 80, -80, 13, 116, 79, -116, 26, 53};
