// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.4).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t int16xint8xint32_1x1_ch8_bias[12] =
    {2947919, 3589613, 411995, 1805943, 2459758, 2947759, 1411158, 2191891, 1727373, 1079560, 1204979, 1106490};

const int32_t *const int16xint8xint32_1x1_ch8_biases = int16xint8xint32_1x1_ch8_bias;
