// Generated by test_settings.py using tensorflow version 2.20.0 (Keras version 3.13.0).
// Interpreter from tensorflow version 2.20.0 and revision v2.20.0-rc0-4-g72fbba3d20f.
#pragma once
#include <stdint.h>

const int16_t transpose_conv_s16_7_input[36] = {6392,   -165,  3179,   -20171, -27233, 5499,   -1973,  -30748, 29270,
                                                4781,   5050,  17386,  23067,  19430,  13180,  -29135, -24662, -22310,
                                                -1760,  7711,  -18389, -8224,  29823,  -19255, -20113, 20172,  6148,
                                                -18674, 19765, 13855,  18919,  3143,   4351,   -8577,  5473,   -4052};
