// Generated by test_settings.py using tensorflow version 2.20.0 (Keras version 3.13.0).
// Interpreter from tensorflow version 2.20.0 and revision v2.20.0-rc0-4-g72fbba3d20f.
#pragma once
#include <stdint.h>

const int8_t transpose_conv_s16_7_weights[80] = {
    -1, -5, -1, 2,  -1, 2,  -5, 2, -1, -1, -5, -2, 2,  -4, -1, 2, -3, 4,  -3, 1,  2, 0,  7, -1, -5, -3, 5,
    -5, 5,  -3, 3,  7,  0,  -1, 0, 0,  -1, 0,  0,  -1, 0,  1,  0, 0,  0,  0,  0,  0, 1,  0, 0,  -1, 1,  1,
    -1, -1, -1, -1, 1,  -1, 1,  1, -1, 0,  -1, 2,  -2, 6,  -7, 2, -4, -8, 4,  -1, 3, -6, 1, -3, 4,  -7};
