// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t reduce_max_axis_hwc_s8_input_tensor[72] = {
    25,   31,   63,   86,  37,  62,  -94, 44,   -37,  -78,  104,  8,    -31, 14,  -105, -116, -34,  -112,
    58,   -111, 51,   1,   -84, -71, 62,  108,  -113, -87,  62,   -24,  -62, -67, 59,   -128, -109, -39,
    -123, -82,  51,   91,  -92, 99,  77,  -123, 12,   -116, -111, -119, -69, 16,  93,   -41,  70,   -52,
    78,   3,    -102, -62, -17, 74,  -44, -83,  93,   -118, 37,   120,  100, 104, 106,  -22,  -13,  -108};
