// Generated by generate_reduce_sum_s16_test_data.py
#pragma once
#include <stdint.h>

const int16_t reduce_sum_s16_output[16] = {
  25575, -14471, 32767, 32767, -32768, 32767, 10763, 15958,
  -32768, 32767, -32768, -32768, -32768, -32768, -15235, 5897
};
