// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t batch_to_space_nd_basic_2x2_s8_input_tensor[72] = {
    -101, 34,   -25, -108, 107, 87,   39,   -30, -71, -61, 59,  -88, 102, 98,   -126, -87, -87, -26,
    14,   -2,   9,   107,  6,   -118, 28,   110, 117, 5,   -67, 5,   12,  61,   23,   -29, 7,   86,
    4,    126,  120, 84,   -73, -110, -114, -83, -59, -31, -45, -72, -18, -105, -48,  54,  24,  -27,
    -3,   -111, -50, 126,  -4,  -27,  51,   -57, -78, 49,  -99, -22, 99,  -18,  50,   14,  -12, -51};
