// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t batch_to_space_nd_basic_2x2_s8_output[72] = {
    -101, 34,  -25,  14,  -2,  9,   -108, 107,  87,  107, 6,   -118, 4,   126, 120,  -3, -111, -50,
    84,   -73, -110, 126, -4,  -27, 39,   -30,  -71, 28,  110, 117,  -61, 59,  -88,  5,  -67,  5,
    -114, -83, -59,  51,  -57, -78, -31,  -45,  -72, 49,  -99, -22,  102, 98,  -126, 12, 61,   23,
    -87,  -87, -26,  -29, 7,   86,  -18,  -105, -48, 99,  -18, 50,   54,  24,  -27,  14, -12,  -51};
