set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR arm)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(CMAKE_TRY_COMPILE_PLATFORM_VARIABLES TARGET_CPU ATFE_DIR)

if(NOT DEFINED TARGET_CPU OR TARGET_CPU STREQUAL "")
  message(FATAL_ERROR "TARGET_CPU must be set for atfe.cmake")
endif()

set(ATFE_DIR "${ATFE_DIR}" CACHE PATH "Root directory of the Arm Toolchain for Embedded")

if(ATFE_DIR STREQUAL "")
  if(DEFINED ENV{ATFE_DIR} AND NOT "$ENV{ATFE_DIR}" STREQUAL "")
    set(ATFE_DIR "$ENV{ATFE_DIR}")
  elseif(EXISTS "/opt/atfe/bin/clang")
    set(ATFE_DIR "/opt/atfe")
  else()
    message(FATAL_ERROR "ATFE_DIR must point to the ATFE installation root")
  endif()
endif()

set(ATFE_BIN_DIR "${ATFE_DIR}/bin")

foreach(tool IN ITEMS clang llvm-ar llvm-ranlib llvm-strip)
  if(NOT EXISTS "${ATFE_BIN_DIR}/${tool}")
    message(FATAL_ERROR "Required ATFE tool missing: ${ATFE_BIN_DIR}/${tool}")
  endif()
endforeach()

if(TARGET_CPU STREQUAL "cortex-m0")
  set(ATFE_ARCH_FLAGS "-mthumb -march=armv6m")
elseif(TARGET_CPU STREQUAL "cortex-m4")
  set(ATFE_ARCH_FLAGS "-mthumb -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard")
elseif(TARGET_CPU STREQUAL "cortex-m55")
  set(ATFE_ARCH_FLAGS "-mthumb -march=armv8.1-m.main+mve.fp -mfloat-abi=hard")
else()
  message(FATAL_ERROR "Unsupported TARGET_CPU for ATFE: ${TARGET_CPU}")
endif()

set(CMAKE_C_COMPILER "${ATFE_BIN_DIR}/clang")
set(CMAKE_CXX_COMPILER "${ATFE_BIN_DIR}/clang++")
set(CMAKE_ASM_COMPILER "${ATFE_BIN_DIR}/clang")
set(CMAKE_AR "${ATFE_BIN_DIR}/llvm-ar")
set(CMAKE_RANLIB "${ATFE_BIN_DIR}/llvm-ranlib")
set(CMAKE_STRIP "${ATFE_BIN_DIR}/llvm-strip")
set(CMAKE_C_COMPILER_TARGET arm-none-eabi)
set(CMAKE_CXX_COMPILER_TARGET arm-none-eabi)
set(CMAKE_ASM_COMPILER_TARGET arm-none-eabi)

set(CMAKE_C_FLAGS_INIT "${ATFE_ARCH_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "${ATFE_ARCH_FLAGS}")
set(CMAKE_ASM_FLAGS_INIT "${ATFE_ARCH_FLAGS}")

set(CMAKE_EXECUTABLE_SUFFIX ".elf")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
