// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t abs_small_tensor_s8_input_tensor[24] = {-105, 100, 118, 52, 117, 8,  0,  6,    45, -44, 125, 1,
                                                     15,   30,  1,   73, -96, 81, 38, -101, 71, 30,  -58, 100};
