// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t slice_strided_2x3_s32_output_tensor[6] =
    {591770244, 26724321, 2098598577, 952279710, 517333070, 1057610243};
