// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t slice_strided_2x3_s32_output[6] = {883892498, 1866677521, 689231057, 2051164439, 373056993, 565183623};
