// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int64_t requantize_s64_biases[8] = {497215, 2290130, 1036743, 2671215, 818507, 1731228, 1543489, 411193};
