// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t requantize_s64_output_shift[8] = {-9, -9, -9, -9, -9, -9, -9, -9};
