/*
 * SPDX-FileCopyrightText: Copyright 2010-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by conv_settings_flt.py using PyTorch version 2.13.0+cpu.
const float16_t conv_small_kernel_nhwc_f16_biases_data[12] = {(float16_t)0.329345703f,
                                                              (float16_t)0.167480469f,
                                                              (float16_t)0.329589844f,
                                                              (float16_t)0.136230469f,
                                                              (float16_t)-0.151733398f,
                                                              (float16_t)0.477050781f,
                                                              (float16_t)0.149902344f,
                                                              (float16_t)-0.269287109f,
                                                              (float16_t)0.468505859f,
                                                              (float16_t)-0.362304688f,
                                                              (float16_t)0.285644531f,
                                                              (float16_t)-0.247314453f};
