/*
 * SPDX-FileCopyrightText: Copyright 2010-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by conv_settings_flt.py using PyTorch version 2.13.0+cpu.
const float16_t conv_small_kernel_nhwc_f16_weights_data[96] = {
    (float16_t)0.706542969f,    (float16_t)0.709960938f,    (float16_t)0.568359375f,    (float16_t)-0.21875f,
    (float16_t)-0.00842285156f, (float16_t)-0.276367188f,   (float16_t)-0.219116211f,   (float16_t)0.253662109f,
    (float16_t)0.33203125f,     (float16_t)-0.129882812f,   (float16_t)-0.0530395508f,  (float16_t)0.0603637695f,
    (float16_t)-0.174316406f,   (float16_t)-0.441894531f,   (float16_t)-0.624511719f,   (float16_t)0.291503906f,
    (float16_t)-0.705566406f,   (float16_t)0.296630859f,    (float16_t)-0.408691406f,   (float16_t)0.133911133f,
    (float16_t)0.0141296387f,   (float16_t)-0.579589844f,   (float16_t)0.485351562f,    (float16_t)0.47265625f,
    (float16_t)0.474609375f,    (float16_t)0.106018066f,    (float16_t)0.494384766f,    (float16_t)0.0629272461f,
    (float16_t)-0.468505859f,   (float16_t)-0.254150391f,   (float16_t)-0.211425781f,   (float16_t)0.699707031f,
    (float16_t)0.119689941f,    (float16_t)-0.235473633f,   (float16_t)0.609863281f,    (float16_t)0.144287109f,
    (float16_t)0.36328125f,     (float16_t)0.749023438f,    (float16_t)0.0523376465f,   (float16_t)0.741210938f,
    (float16_t)0.606445312f,    (float16_t)-0.422607422f,   (float16_t)-0.00157546997f, (float16_t)0.607910156f,
    (float16_t)0.697753906f,    (float16_t)0.417724609f,    (float16_t)-0.237548828f,   (float16_t)0.456054688f,
    (float16_t)0.125976562f,    (float16_t)0.196899414f,    (float16_t)0.183227539f,    (float16_t)-0.602050781f,
    (float16_t)0.665039062f,    (float16_t)-0.277587891f,   (float16_t)-0.177978516f,   (float16_t)0.196655273f,
    (float16_t)0.071105957f,    (float16_t)0.573730469f,    (float16_t)0.0783081055f,   (float16_t)0.501464844f,
    (float16_t)-0.341552734f,   (float16_t)0.473632812f,    (float16_t)0.172119141f,    (float16_t)-0.575195312f,
    (float16_t)-0.703125f,      (float16_t)-0.472167969f,   (float16_t)-0.065612793f,   (float16_t)-0.111083984f,
    (float16_t)0.576660156f,    (float16_t)0.164550781f,    (float16_t)0.209838867f,    (float16_t)-0.287597656f,
    (float16_t)-0.259521484f,   (float16_t)-0.60546875f,    (float16_t)0.247802734f,    (float16_t)-0.74609375f,
    (float16_t)-0.236450195f,   (float16_t)0.443359375f,    (float16_t)-0.599121094f,   (float16_t)-0.0445556641f,
    (float16_t)0.0314025879f,   (float16_t)0.103515625f,    (float16_t)-0.216796875f,   (float16_t)0.539550781f,
    (float16_t)0.17956543f,     (float16_t)-0.0616149902f,  (float16_t)0.725097656f,    (float16_t)-0.108581543f,
    (float16_t)0.481201172f,    (float16_t)-0.00428771973f, (float16_t)0.459960938f,    (float16_t)0.432373047f,
    (float16_t)0.0455627441f,   (float16_t)0.273681641f,    (float16_t)0.65234375f,     (float16_t)0.614746094f};
