// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t sub_ident_s16_output[24] = {0,  0, 0, 0, -19678, -27847, 30502,  0, 0,  0, 0, 0,
                                          -8, 0, 0, 0, 11444,  -32320, -10962, 0, -8, 0, 0, 0};

const int16_t *const sub_ident_s16_output_ref = sub_ident_s16_output;
