// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t conv_1_x_n_6_generic_biases[16] =
    {-6829, 12049, 26765, -5165, 13638, -17399, 18726, 2156, 23354, -6555, 13869, 4664, 13004, 30566, -17183, -22665};
