// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_1_x_n_6_generic_output_ref[16] = {-11, 68, -8, -37, 14, 37, 38, -11, 71, 38, 5, 7, -27, 63, -25, -56};
