/* AUTOGENERATED FILE. DO NOT EDIT. */

/*=======Automagically Detected Files To Include=====*/
#include "unity.h"
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/*=======External Functions This Runner Calls=====*/
extern void test_int16xint8_arm_convolve_s16(void);
extern void test_requantize_s64_arm_convolve_s16(void);
extern void test_int16xint8_dilation_1_arm_convolve_s16(void);
extern void test_int16xint8_dilation_2_arm_convolve_s16(void);
extern void test_int16xint8_dilation_3_arm_convolve_s16(void);
extern void test_buffer_size_arm_convolve_s16(void);
extern void test_buffer_size_mve_arm_convolve_s16(void);
extern void test_buffer_size_dsp_arm_convolve_s16(void);
extern void test_int16xint8_spill_arm_convolve_s16(void);
extern void test_int16xint8_spill2_arm_convolve_s16(void);
extern void test_int16xint8xint32_1_arm_convolve_s16(void);
extern void test_int16xint8xint32_2_arm_convolve_s16(void);
extern void test_int16xint8xint32_3_arm_convolve_s16(void);
extern void test_int16xint8xint32_4_arm_convolve_s16(void);
extern void test_int16xint8xint32_5_arm_convolve_s16(void);
extern void test_int16xint8xint32_6_arm_convolve_s16(void);
extern void test_int16xint8_group2_arm_convolve_s16(void);
extern void test_int16xint8_group_same_arm_convolve_s16(void);
extern void test_int16xint8_group_batch2_dilated_arm_convolve_s16(void);
extern void test_int16xint8_group_depthwise_arm_convolve_s16(void);
extern void test_int16xint8_group_depthwise_3x3_arm_convolve_s16(void);
extern void test_int16xint8_group_depthwise_3x3_pad_arm_convolve_s16(void);
extern void test_int16xint8_group_depthwise_3x3_stride_dilation_arm_convolve_s16(void);
extern void test_int16xint8_kernel_less_than_9_arm_convolve_s16(void);
extern void test_int16xint8_1x1_ns_np_nd_arm_convolve_s16(void);


/*=======Mock Management=====*/
static void CMock_Init(void)
{
}
static void CMock_Verify(void)
{
}
static void CMock_Destroy(void)
{
}

/*=======Test Reset Options=====*/
void resetTest(void)
{
  tearDown();
  CMock_Verify();
  CMock_Destroy();
  CMock_Init();
  setUp();
}
void verifyTest(void)
{
  CMock_Verify();
}

/*=======Test Runner Used To Run Each Test=====*/
static void run_test(UnityTestFunction func, const char* name, UNITY_LINE_TYPE line_num)
{
    Unity.CurrentTestName = name;
    Unity.CurrentTestLineNumber = (UNITY_UINT) line_num;
#ifdef UNITY_USE_COMMAND_LINE_ARGS
    if (!UnityTestMatches())
        return;
#endif
    Unity.NumberOfTests++;
    UNITY_CLR_DETAILS();
    UNITY_EXEC_TIME_START();
    CMock_Init();
    if (TEST_PROTECT())
    {
        setUp();
        func();
    }
    if (TEST_PROTECT())
    {
        tearDown();
        CMock_Verify();
    }
    CMock_Destroy();
    UNITY_EXEC_TIME_STOP();
    UnityConcludeTest();
}

/*=======MAIN=====*/
int main(void)
{
  UnityBegin("TestCases/test_arm_convolve_s16/Unity/unity_test_arm_convolve_s16.c");
  run_test(test_int16xint8_arm_convolve_s16, "test_int16xint8_arm_convolve_s16", 46);
  run_test(test_requantize_s64_arm_convolve_s16, "test_requantize_s64_arm_convolve_s16", 47);
  run_test(test_int16xint8_dilation_1_arm_convolve_s16, "test_int16xint8_dilation_1_arm_convolve_s16", 48);
  run_test(test_int16xint8_dilation_2_arm_convolve_s16, "test_int16xint8_dilation_2_arm_convolve_s16", 49);
  run_test(test_int16xint8_dilation_3_arm_convolve_s16, "test_int16xint8_dilation_3_arm_convolve_s16", 50);
  run_test(test_buffer_size_arm_convolve_s16, "test_buffer_size_arm_convolve_s16", 51);
  run_test(test_buffer_size_mve_arm_convolve_s16, "test_buffer_size_mve_arm_convolve_s16", 52);
  run_test(test_buffer_size_dsp_arm_convolve_s16, "test_buffer_size_dsp_arm_convolve_s16", 53);
  run_test(test_int16xint8_spill_arm_convolve_s16, "test_int16xint8_spill_arm_convolve_s16", 54);
  run_test(test_int16xint8_spill2_arm_convolve_s16, "test_int16xint8_spill2_arm_convolve_s16", 55);
  run_test(test_int16xint8xint32_1_arm_convolve_s16, "test_int16xint8xint32_1_arm_convolve_s16", 56);
  run_test(test_int16xint8xint32_2_arm_convolve_s16, "test_int16xint8xint32_2_arm_convolve_s16", 57);
  run_test(test_int16xint8xint32_3_arm_convolve_s16, "test_int16xint8xint32_3_arm_convolve_s16", 58);
  run_test(test_int16xint8xint32_4_arm_convolve_s16, "test_int16xint8xint32_4_arm_convolve_s16", 59);
  run_test(test_int16xint8xint32_5_arm_convolve_s16, "test_int16xint8xint32_5_arm_convolve_s16", 60);
  run_test(test_int16xint8xint32_6_arm_convolve_s16, "test_int16xint8xint32_6_arm_convolve_s16", 61);
  run_test(test_int16xint8_group2_arm_convolve_s16, "test_int16xint8_group2_arm_convolve_s16", 62);
  run_test(test_int16xint8_group_same_arm_convolve_s16, "test_int16xint8_group_same_arm_convolve_s16", 63);
  run_test(test_int16xint8_group_batch2_dilated_arm_convolve_s16, "test_int16xint8_group_batch2_dilated_arm_convolve_s16", 64);
  run_test(test_int16xint8_group_depthwise_arm_convolve_s16, "test_int16xint8_group_depthwise_arm_convolve_s16", 68);
  run_test(test_int16xint8_group_depthwise_3x3_arm_convolve_s16, "test_int16xint8_group_depthwise_3x3_arm_convolve_s16", 69);
  run_test(test_int16xint8_group_depthwise_3x3_pad_arm_convolve_s16, "test_int16xint8_group_depthwise_3x3_pad_arm_convolve_s16", 70);
  run_test(test_int16xint8_group_depthwise_3x3_stride_dilation_arm_convolve_s16, "test_int16xint8_group_depthwise_3x3_stride_dilation_arm_convolve_s16", 71);
  run_test(test_int16xint8_kernel_less_than_9_arm_convolve_s16, "test_int16xint8_kernel_less_than_9_arm_convolve_s16", 75);
  run_test(test_int16xint8_1x1_ns_np_nd_arm_convolve_s16, "test_int16xint8_1x1_ns_np_nd_arm_convolve_s16", 76);

  exit(UNITY_END());
}
