// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t int16xint8_spill2_output_mult[9] =
    {1219117056, 1224130432, 1226159360, 1223721088, 1223394944, 1220552704, 1225579648, 1226373248, 1222086528};
