// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t int16xint8xint32_3_output_mult[8] =
    {1769495680, 1805088128, 1724993280, 1693185792, 1843989760, 1596953600, 1817795712, 1768424192};
