// Generated by test data script for arm_sqrt_s16 unit tests.
#pragma once

#define SQRT_MULTI_BATCH_S16_BATCH_SIZE 2
#define SQRT_MULTI_BATCH_S16_HEIGHT_1 1
#define SQRT_MULTI_BATCH_S16_WIDTH_1 1
#define SQRT_MULTI_BATCH_S16_CHANNEL_1 8
#define SQRT_MULTI_BATCH_S16_IN_DIM                                                                                    \
    {                                                                                                                  \
        2, 1, 1, 8,                                                                                                    \
    }
#define SQRT_MULTI_BATCH_S16_OUTPUT_LEN 16
#define SQRT_MULTI_BATCH_S16_INPUT_SCALE 0.0003f
#define SQRT_MULTI_BATCH_S16_INPUT_ZERO_POINT 0
#define SQRT_MULTI_BATCH_S16_OUTPUT_SCALE 0.00025f
#define SQRT_MULTI_BATCH_S16_OUTPUT_ZERO_POINT 0
