// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t minimum_broadcast_width_int16_input_tensor_2[38] = {
    -1330, 15005,  4997,  11038,  -28722, -30762, 13599,  17251, -14795, -19792, -10173, 4839,  -17141,
    -2494, -21955, 13769, -28343, 29965,  29087,  -16512, 8907,  -8044,  18411,  12963,  31765, -26200,
    20457, -15198, 31211, 213,    -16822, 26568,  -3004,  15894, 17047,  9667,   8500,   -18467};
