// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t space_to_batch_nd_both_pad_s16_input_tensor[80] = {
    -112, -98, -101, -29, -6,  48,  98,   56,   -115, 26,  -41, 109, 125, -57,  17,  96, -104, -68,  -31,  -114,
    -60,  87,  65,   -38, 72,  -89, -110, -42,  -58,  31,  -72, 103, 15,  120,  22,  11, 82,   -104, 75,   69,
    126,  31,  116,  90,  -23, 103, -89,  127,  -101, -71, 25,  51,  -27, -9,   -21, 15, -39,  -65,  -64,  6,
    37,   -30, -27,  55,  -40, -67, 8,    -103, -110, 49,  44,  65,  46,  -114, -56, 86, -57,  -40,  0, -46};
