// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tflite_micro runtime version 0.dev20250802032821-g14638b6.
#pragma once
#include <stdint.h>

const int16_t depth_to_space_min_depth_s16_input_tensor[36] = {
    -94, -95, -56, 1,   -31,  -38, -12, -15, 93,  86, -11, -103, 5,   -74, 93,  -127, -39, -121,
    -35, -12, 8,   -10, -112, -60, 82,  12,  -74, 26, 24,  17,   114, 66,  -55, -110, 57,  100};
