// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tflite_micro runtime version 0.dev20250802032821-g14638b6.
#pragma once
#include <stdint.h>

const int16_t depth_to_space_min_depth_s16_output[36] = {-94, -95, -31, -38,  93,  86,   -56, 1,    -12, -15, -11,  -103,
                                                        5,   -74, -39, -121, 8,   -10,  93,  -127, -35, -12, -112, -60,
                                                        82,  12,  24,  17,   -55, -110, -74, 26,   114, 66,  57,   100};
