// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t fc_per_channel_s16_1_input_tensor[12] =
    {-11823, 1812, 31043, -15478, -815, 27729, 10749, 23539, 22949, 14278, -15821, -31218};
