// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t fc_per_channel_s16_1_output[8] = {0, 0, 0, 17517, 11075, 0, 0, 12534};

const int16_t *const fc_per_channel_s16_1_output_ref = fc_per_channel_s16_1_output;
