// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t fc_per_channel_s16_1_weights[24] = {-28,  -45, -4,  125, 127, -69, 127, 125, -126, 56,   46,  90,
                                                 -127, 26,  -89, 101, 27,  35,  97,  69,  13,   -107, 127, 3};
