// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once

#define TRANSPOSE_S16_NHCW_IN_DIM                                                                                      \
    {                                                                                                                  \
        1, 1, 127, 127,                                                                                                \
    }
#define TRANSPOSE_S16_NHCW_PERM                                                                                        \
    {                                                                                                                  \
        0, 1, 3, 2,                                                                                                    \
    }
#define TRANSPOSE_S16_NHCW_SIZE 16129
#define TRANSPOSE_S16_NHCW_PERM_SIZE 4
#define TRANSPOSE_S16_NHCW_OUT_DIM                                                                                     \
    {                                                                                                                  \
        1, 1, 127, 127,                                                                                                \
    }
