// Generated by generate_comparison_data.py
#pragma once
#include <stdint.h>

const int8_t comparison_greater_broadcast_h_s8_input_2_input_tensor[24] = {
    -11, -5, -2, 1, 4, 4, 10, 13, 

    16, 19, 19, 25, 28, 31, 34, 34, 

    40, 43, 46, 49, 49, 55, 58, 61
};
