// Generated by generate_comparison_data.py
#pragma once
#include <stdbool.h>

const bool comparison_greater_broadcast_h_s8_output[24] = {
    false, false, false, false, false, true, false, false, 

    false, false, false, false, false, false, false, false, 

    false, false, false, false, false, false, false, false
};

const bool *const comparison_greater_broadcast_h_s8_output_ref = comparison_greater_broadcast_h_s8_output;
