// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t reduce_max_axis_n_s16_input_tensor[48] = {
    -21759, -29856, 27388, -7962, 14368,  13774,  855,    14361,  10513,  25006,  -28274, -4779,
    -26436, -12256, 16423, -7799, -27268, -3348,  -29930, -14369, 30255,  -12054, 19145,  -18485,
    7640,   -12809, 27701, 6258,  19268,  -29078, 22971,  29743,  -17340, 3668,   -28831, 28767,
    -21491, -18000, 25030, -7368, 518,    8786,   -12822, -15985, 23889,  -23907, 22062,  -8393};
