// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t reduce_max_axis_n_s16_output[24] = {7640,  -12809, 27701,  6258,   19268,  13774,  22971, 29743,
                                                  10513, 25006,  -28274, 28767,  -21491, -12256, 25030, -7368,
                                                  518,   8786,   -12822, -14369, 30255,  -12054, 22062, -8393};
