// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.13.2).
// Interpreter from tflite_micro runtime version 0.dev20251103221221-gv1.3.0-45-gac157ac1-dirty.
#pragma once
#include <stdint.h>

const int16_t squared_difference_broadcast_h_s16_output[24] = {135,   21151, 2158,  14535, 17114, 8107,  6856,  7815,
                                                               17041, 24407, 32767, 5650,  95,    32767, 11285, 17572,
                                                               21946, 0,     4917,  2158,  1916,  32767, 1249,  6060};

const int16_t *const squared_difference_broadcast_h_s16_output_ref = squared_difference_broadcast_h_s16_output;
