// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.13.2).
// Interpreter from tflite_micro runtime version 0.dev20251103221221-gv1.3.0-45-gac157ac1-dirty.
#pragma once
#include <stdint.h>

const int16_t squared_difference_broadcast_c_s16_lhs_input_tensor[24] = {
    -11070, -13713, -26404, -28988, 13147,  -23579, 10185, -32207, 25526,  3133,   30183,  -19653,
    31853,  -19336, -26706, 32404,  -15461, -17533, 2280,  24297,  -13265, -25596, -23712, -15086};
