// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t basic_output_ref[20] = {-117, 104, -40, 77, -45, 113, -9,  -9,  22,  -70,
                                     -61,  15,  14,  -3, 20,  21,  -79, -97, -53, -50};
