// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int16_t int16xint8xint32_1_output_ref[40] = {
    -4890, 1243,  537,    15446, 9801,   -7711, 13270, -1348,  1588, 4061,  -8991, -7648, -7608, -9075,
    526,   -662,  1806,   -9664, 561,    11267, 6412,  -20355, 1267, -8923, 4875,  5281,  -3721, 4339,
    16908, -5029, -11806, -4982, -11125, 16480, -2508, -620,   5434, 5921,  7060,  -3019};
