// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define SPACE_TO_BATCH_ND_SMALL_PAD_S8_IN_DIM                                                                          \
    {                                                                                                                  \
        1, 1, 3, 2,                                                                                                    \
    }
#define SPACE_TO_BATCH_ND_SMALL_PAD_S8_BLOCK_SHAPE                                                                     \
    {                                                                                                                  \
        2, 3,                                                                                                          \
    }
#define SPACE_TO_BATCH_ND_SMALL_PAD_S8_PADDINGS                                                                        \
    {                                                                                                                  \
        1, 0, 0, 0,                                                                                                    \
    }
#define SPACE_TO_BATCH_ND_SMALL_PAD_S8_OUT_DIM                                                                         \
    {                                                                                                                  \
        6, 1, 1, 2,                                                                                                    \
    }
#define SPACE_TO_BATCH_ND_SMALL_PAD_S8_PAD_NHWC4                                                                       \
    {                                                                                                                  \
        1, 0, 0, 0,                                                                                                    \
    }
#define SPACE_TO_BATCH_ND_SMALL_PAD_S8_INPUT_SIZE 6
#define SPACE_TO_BATCH_ND_SMALL_PAD_S8_OUTPUT_SIZE 12
#define SPACE_TO_BATCH_ND_SMALL_PAD_S8_INPUT_OFFSET 128
#define SPACE_TO_BATCH_ND_SMALL_PAD_S8_OUTPUT_OFFSET -128
