// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once
#include <stdint.h>

const int8_t squared_difference_broadcast_w_s8_lhs_input_tensor[24] = {
    -123, 40, -25, -70, -123, -91, -42, 63, -27, 111, 14, 73, 95, 110, 72, 4, 19, -60, 6, -50, 36, 45, 83, -47};
