// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_dilation_golden_input[48] = {37,  -76,  -93, -43, 62,  -8,  -108, 47,  -107, -67, -21,  94,
                                               -17, -118, 77,  86,  -49, 48,  30,   -15, 73,   -12, -125, 40,
                                               -32, 109,  -21, 90,  81,  -56, -69,  -69, -6,   -15, -103, 8,
                                               24,  111,  18,  -35, -61, 118, -28,  -66, -114, -41, 68,   74};
