// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_dilation_golden_weights[12] = {116, -92, 127, -7, -20, -74, -127, 12, 40, -59, -58, 127};
