// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t maxpooling_5_input[20] = {19,   119, -110, 49,  70,  40, -94, 126, 123, 13,
                                       -109, -64, -1,   -18, -85, 65, 84,  -50, -28, 7};
