// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t sub_broadcast_c_s8_input_data[24] = {32, 30, 18, 50, 113, 120, 0,  0,  -80, -24, -48, 32,
                                                  3,  91, 0,  0,  -64, -78, 35, 50, 113, 120, 0,   0};
