// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t sub_broadcast_c_s8_output[24] = {9,  8,  2,  18, 57,  61,  -1, -1, -43, -14, -26, 15,
                                              -3, 42, -5, -5, -35, -42, 17, 24, 56,  60,  -2,  -2};

const int8_t *const sub_broadcast_c_s8_output_ref = sub_broadcast_c_s8_output;
