// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.4).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t int16xint8xint32_1x1_ch16_output_multiplier[8] =
    {1781952689, 1796170333, 1593561559, 1649729270, 1671897499, 1688241580, 1786371425, 1681967899};

const int32_t *const int16xint8xint32_1x1_ch16_output_mult = int16xint8xint32_1x1_ch16_output_multiplier;
