// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define WHERE_2D_S16_FORCE_NO_QUANTIZE true
#define WHERE_2D_S16_SHAPE                                                                                             \
    {                                                                                                                  \
        2, 3,                                                                                                          \
    }
#define WHERE_2D_S16_CONDITION_VALUES                                                                                  \
    {                                                                                                                  \
        0, 100, 0, 200, 0, 300,                                                                                        \
    }
#define WHERE_2D_S16_RANK 2
#define WHERE_2D_S16_SIZE 6
#define WHERE_2D_S16_COND_SIZE 6
