// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once

#define RELU_BASIC_S16_BATCH_SIZE 100
#define RELU_BASIC_S16_BATCH_1 1
#define RELU_BASIC_S16_HEIGHT_1 1
#define RELU_BASIC_S16_WIDTH_1 10
#define RELU_BASIC_S16_CHANNEL_1 1
#define RELU_BASIC_S16_PAD SAME
#define RELU_BASIC_S16_INPUT_MIN -32768
#define RELU_BASIC_S16_INPUT_MAX 32767
#define RELU_BASIC_S16_INPUT_OFFSET 0
#define RELU_BASIC_S16_OUTPUT_OFFSET 0
#define RELU_BASIC_S16_OUTPUT_MULTIPLIER 1 << 30
#define RELU_BASIC_S16_OUTPUT_SHIFT 1
#define RELU_BASIC_S16_OUTPUT_LEN 10
