// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mean_axis_c_s8_input_tensor[16] =
    {116, 66, 50, -128, 61, -106, -7, -45, 42, -96, -12, -6, 41, 108, -70, -61};
