// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t batch_to_space_nd_basic_2x2_s16_input_tensor[72] = {
    -54, 106,  -17, -62,  -16, -101, 126, -78,  -118, 35,   -55, -30,  92,  56,  -114, -8,  -111, 78,
    104, -109, 84,  109,  40,  -59,  77,  67,   53,   -121, 60,  -31,  -19, 5,   -126, -86, -59,  -66,
    53,  -87,  -27, -106, 109, -90,  -2,  -115, -35,  -41,  -12, 64,   -91, 119, -49,  -61, 97,   51,
    42,  -14,  111, -47,  8,   -51,  70,  -116, 77,   -43,  -14, -128, -66, -6,  -65,  3,   -48,  125};
