// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t batch_to_space_nd_basic_2x2_s16_output[72] = {
    -54,  106,  -17, 104, -109, 84,  -62, -16, -101, 109, 40,  -59,  53,  -87, -27,  42,   -14, 111,
    -106, 109,  -90, -47, 8,    -51, 126, -78, -118, 77,  67,  53,   35,  -55, -30,  -121, 60,  -31,
    -2,   -115, -35, 70,  -116, 77,  -41, -12, 64,   -43, -14, -128, 92,  56,  -114, -19,  5,   -126,
    -8,   -111, 78,  -86, -59,  -66, -91, 119, -49,  -66, -6,  -65,  -61, 97,  51,   3,    -48, 125};
