// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t wide_k3_1d_valid_35ch_255w_bias[35] = {
    22499, -16215, -5592,  8424,   49201,  27402,  28468, -25265, 4894,   36820,  37498,  -26128,
    41042, -46983, -31400, 35244,  -46077, -17000, -5186, 8135,   -49725, 8199,   -10442, 41946,
    12529, -22120, 5707,   -21331, 0,      -14924, 31920, 16141,  -20678, -10828, -27577};

const int32_t *const wide_k3_1d_valid_35ch_255w_biases = wide_k3_1d_valid_35ch_255w_bias;
