// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define SPACE_TO_DEPTH_BS4_SMALL_S8_IN_DIM                                                                             \
    {                                                                                                                  \
        1, 8, 8, 1,                                                                                                    \
    }
#define SPACE_TO_DEPTH_BS4_SMALL_S8_BLOCK_SIZE 4
#define SPACE_TO_DEPTH_BS4_SMALL_S8_OUT_DIM                                                                            \
    {                                                                                                                  \
        1, 2, 2, 16,                                                                                                   \
    }
#define SPACE_TO_DEPTH_BS4_SMALL_S8_INPUT_SIZE 64
#define SPACE_TO_DEPTH_BS4_SMALL_S8_OUTPUT_SIZE 64
#define SPACE_TO_DEPTH_BS4_SMALL_S8_INPUT_OFFSET 128
#define SPACE_TO_DEPTH_BS4_SMALL_S8_OUTPUT_OFFSET -128
