// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t space_to_depth_bs4_small_s8_output[64] = {
    -121, 101, -98,  -27, 92,   35,   3,   -55, 9,   -5,   -65, -92, 63,  -72, 3,   13, -92, 86,  34,  19,  125, -115,
    113,  -54, 113,  41,  -23,  -118, 116, -78, 59,  -30,  79,  -84, -70, 124, 122, 71, 93,  105, 93,  -98, 67,  127,
    -9,   -62, -118, -81, -114, 47,   96,  -66, -14, -108, 15,  27,  -56, -74, 59,  63, -59, 17,  -25, 116};
