// Generated by generate_test_data.py using tensorflow version 2.19.0 (Keras version 3.9.2).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const float dequantize_s8_f32_output[8] =
    {0.55256, 0.348804, 0.590549, 0.863376, 0.279734, 0.172675, 0.355711, 0.863376};
