// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int64_t fc_per_channel_s16_bias[3] = {2480747, -1835077, -244309};

const int64_t *const fc_per_channel_s16_biases = fc_per_channel_s16_bias;
