// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int16_t fc_per_channel_s16_input_tensor[8] = {21789, -745, 31060, 1809, 4193, 23000, -17362, 24171};
