// Generated by test_settings.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t int16xint8_kernel_less_than_9_output_mult[8] =
    {1129633144, 2101918987, 1231933015, 1167055013, 1239998554, 2006291314, 1158910757, 1262488257};
