// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t int16xint8_kernel_less_than_9_output_mult[6] =
    {1604713600, 1166893440, 1361706624, 1325842304, 1232063488, 1601215872};
