// Generated by test_settings.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t int16xint8_kernel_less_than_9_output_mult[6] =
    {1980335903, 2140320779, 2084336171, 1599479828, 2114244907, 1862640634};
