// Generated by test_settings.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t int16xint8_kernel_less_than_9_weights[48] = {
    -41, -13,  -56,  81,   48,  -66,  127, -20, 51,   127, 120,  -98, 51,   -113, 31,  84,
    122, -114, -125, 61,   47,  -127, -62, 12,  -43,  12,  -127, -14, 123,  85,   -12, 107,
    105, -127, 92,   -110, -20, 55,   71,  116, -127, 95,  78,   70,  -108, -108, -77, -117};
