// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t int16xint8_kernel_less_than_9_weights[48] = {
    -99, 127,  38,  0,   56,  -8,  -62, -53, 42,   119, 59, 114,  125, 110, -127, 15,
    107, -112, -34, -15, -62, 82,  48,  127, -127, -33, 49, 106,  125, 83,  -65,  -126,
    -21, 34,   118, -4,  127, 107, 62,  22,  -64,  8,   70, -127, 41,  26,  96,   -123};
