// Generated by test_settings.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t int16xint8_kernel_less_than_9_weights[64] = {
    78,  -30,  101, -12, -40,  82,  127, -21, -89, 27,  -25, 106, 127, 95,   24,  -38,  89,  1,    37,  -34, 44,  77,
    55,  -127, -19, 127, 53,   118, 53,  92,  64,  -16, 55,  -66, -5,  -108, -63, -119, -15, 127,  -14, -92, -16, 127,
    -57, 120,  122, -54, -125, -17, 30,  -34, 127, 110, 17,  50,  -33, 54,   72,  41,   26,  -127, -10, 83};
