// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once
#include <stdint.h>

const int8_t squared_difference_broadcast_n_s8_lhs_input_tensor[24] = {
    24, -56, -62, 9, 25, 12, 22, 23, 51, -106, 63, -122, -86, -97, 22, 69, -41, -48, 114, 117, -66, -26, 116, 92};
