// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once
#include <stdint.h>

const int8_t squared_difference_broadcast_n_s8_rhs_input_tensor[48] = {
    64,  -32,  23,  -54, -95,  2,   121, -35, 60,   74,  30,  68,  -80, -90, -75,  36,
    -13, -109, -8,  114, -33,  -31, 13,  124, 65,   11,  -61, -34, -39, 105, -106, -35,
    97,  -83,  -94, 116, -100, 11,  -51, -92, -105, -28, 85,  -84, 79,  -44, 36,   124};
