// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t medium_k5_1d_valid_20ch_80h_bias[20] = {-886,  -32218, 6178,   19128,  -28563, 15626, 20731,
                                                      10766, 23517,  -18280, -21756, 915,    51448, -10759,
                                                      -9002, -37930, 12401,  -38529, -20112, 18681};

const int32_t *const medium_k5_1d_valid_20ch_80h_biases = medium_k5_1d_valid_20ch_80h_bias;
