// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t medium_k5_1d_valid_20ch_80h_output_multiplier[20] = {
    2133821319, 1849421122, 1760419981, 1557549905, 1572853291, 1634174649, 1254590581,
    1756968929, 1829918588, 1215879471, 1847623128, 2068056454, 1801594661, 1450520992,
    1576044409, 1483661370, 1715963598, 1215093815, 1199147611, 1696017310};

const int32_t *const medium_k5_1d_valid_20ch_80h_output_mult = medium_k5_1d_valid_20ch_80h_output_multiplier;
