// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t conv_1_x_n_7_output_mult[15] = {1240951936,
                                              1240507136,
                                              1240984832,
                                              1237815040,
                                              1238327296,
                                              1236538240,
                                              1240404224,
                                              1239791616,
                                              1236264960,
                                              1241041152,
                                              1239269120,
                                              1238901888,
                                              1239635840,
                                              1239717504,
                                              1239602944};
