/*
 * SPDX-FileCopyrightText: Copyright 2010-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by conv_settings_flt.py using PyTorch version 2.13.0+cpu.
const float16_t conv_small_kernel_grouped_nhwc_f16_biases_data[8] = {(float16_t)-0.349609375f,
                                                                     (float16_t)0.288085938f,
                                                                     (float16_t)0.099609375f,
                                                                     (float16_t)0.294433594f,
                                                                     (float16_t)-0.0370178223f,
                                                                     (float16_t)-0.412109375f,
                                                                     (float16_t)0.184936523f,
                                                                     (float16_t)-0.495605469f};
