/*
 * SPDX-FileCopyrightText: Copyright 2010-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by conv_settings_flt.py using PyTorch version 2.13.0+cpu.
const float16_t conv_small_kernel_grouped_nhwc_f16_input_data[120] = {
    (float16_t)0.659667969f,   (float16_t)0.334960938f,  (float16_t)-0.559570312f, (float16_t)0.98046875f,
    (float16_t)-0.505859375f,  (float16_t)-0.324707031f, (float16_t)-0.55859375f,  (float16_t)0.365722656f,
    (float16_t)-0.929199219f,  (float16_t)-0.458496094f, (float16_t)-0.811035156f, (float16_t)0.963867188f,
    (float16_t)-0.923828125f,  (float16_t)-0.887207031f, (float16_t)-0.763183594f, (float16_t)-0.5859375f,
    (float16_t)0.802246094f,   (float16_t)0.203735352f,  (float16_t)-0.28125f,     (float16_t)-0.792480469f,
    (float16_t)0.995117188f,   (float16_t)0.520019531f,  (float16_t)-0.374755859f, (float16_t)0.53515625f,
    (float16_t)-0.85546875f,   (float16_t)-0.666503906f, (float16_t)0.223266602f,  (float16_t)0.242675781f,
    (float16_t)-0.280517578f,  (float16_t)-0.306884766f, (float16_t)-0.410888672f, (float16_t)0.155273438f,
    (float16_t)0.642089844f,   (float16_t)0.225341797f,  (float16_t)-0.239257812f, (float16_t)0.392578125f,
    (float16_t)-0.0958251953f, (float16_t)0.881835938f,  (float16_t)-0.549316406f, (float16_t)0.530273438f,
    (float16_t)-0.701171875f,  (float16_t)-0.506347656f, (float16_t)-0.459228516f, (float16_t)0.0946044922f,
    (float16_t)-0.631835938f,  (float16_t)0.109985352f,  (float16_t)0.918945312f,  (float16_t)0.721679688f,
    (float16_t)-0.905273438f,  (float16_t)0.075378418f,  (float16_t)-0.253662109f, (float16_t)-0.313964844f,
    (float16_t)-0.0411682129f, (float16_t)0.895507812f,  (float16_t)0.896972656f,  (float16_t)0.100708008f,
    (float16_t)-0.457275391f,  (float16_t)-0.568847656f, (float16_t)0.224975586f,  (float16_t)0.201538086f,
    (float16_t)0.189819336f,   (float16_t)0.0786132812f, (float16_t)-0.649414062f, (float16_t)-0.834960938f,
    (float16_t)-0.271972656f,  (float16_t)0.129394531f,  (float16_t)0.269775391f,  (float16_t)-0.157958984f,
    (float16_t)0.61328125f,    (float16_t)-0.966796875f, (float16_t)0.442138672f,  (float16_t)-0.338867188f,
    (float16_t)-0.812011719f,  (float16_t)-0.396972656f, (float16_t)-0.465087891f, (float16_t)0.536621094f,
    (float16_t)0.286376953f,   (float16_t)0.0616149902f, (float16_t)-0.437255859f, (float16_t)0.359619141f,
    (float16_t)0.0948486328f,  (float16_t)0.916015625f,  (float16_t)0.232788086f,  (float16_t)0.11315918f,
    (float16_t)0.478027344f,   (float16_t)0.955566406f,  (float16_t)-0.876464844f, (float16_t)0.4921875f,
    (float16_t)-0.630371094f,  (float16_t)-0.263916016f, (float16_t)-0.954101562f, (float16_t)-0.221191406f,
    (float16_t)-0.808105469f,  (float16_t)-0.465087891f, (float16_t)0.12487793f,   (float16_t)0.0268249512f,
    (float16_t)0.409667969f,   (float16_t)0.233886719f,  (float16_t)0.891113281f,  (float16_t)-0.745605469f,
    (float16_t)-0.0372314453f, (float16_t)0.677734375f,  (float16_t)-0.532226562f, (float16_t)-0.545898438f,
    (float16_t)-0.537109375f,  (float16_t)-0.786132812f, (float16_t)-0.244628906f, (float16_t)-0.331787109f,
    (float16_t)-0.135498047f,  (float16_t)0.240234375f,  (float16_t)0.9140625f,    (float16_t)-0.832519531f,
    (float16_t)0.170166016f,   (float16_t)0.787109375f,  (float16_t)-0.368408203f, (float16_t)0.457275391f,
    (float16_t)-0.583496094f,  (float16_t)-0.799316406f, (float16_t)0.0740966797f, (float16_t)0.775878906f};
