/*
 * SPDX-FileCopyrightText: Copyright 2010-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by conv_settings_flt.py using PyTorch version 2.13.0+cpu.
const float16_t conv_small_kernel_grouped_nhwc_f16_output_ref_data[160] = {
    (float16_t)-0.407714844f,  (float16_t)0.313232422f,   (float16_t)-0.375488281f,   (float16_t)-0.519042969f,
    (float16_t)0.637207031f,   (float16_t)-0.0696411133f, (float16_t)-0.0105819702f,  (float16_t)0.151367188f,
    (float16_t)-0.943847656f,  (float16_t)-0.438720703f,  (float16_t)-0.149414062f,   (float16_t)-0.332763672f,
    (float16_t)-0.521972656f,  (float16_t)0.217285156f,   (float16_t)0.358398438f,    (float16_t)0.635742188f,
    (float16_t)-0.65625f,      (float16_t)-0.125610352f,  (float16_t)0.141235352f,    (float16_t)0.118103027f,
    (float16_t)0.762207031f,   (float16_t)-0.456787109f,  (float16_t)-0.338378906f,   (float16_t)-0.359130859f,
    (float16_t)-0.406494141f,  (float16_t)-0.391113281f,  (float16_t)-0.945800781f,   (float16_t)0.00949859619f,
    (float16_t)-0.195922852f,  (float16_t)-0.450683594f,  (float16_t)0.205932617f,    (float16_t)-0.979492188f,
    (float16_t)0.322265625f,   (float16_t)1.0078125f,     (float16_t)-0.241943359f,   (float16_t)-0.194824219f,
    (float16_t)-1.15039062f,   (float16_t)-0.110900879f,  (float16_t)0.128540039f,    (float16_t)0.614257812f,
    (float16_t)-0.387451172f,  (float16_t)-0.616699219f,  (float16_t)-0.602050781f,   (float16_t)-0.801269531f,
    (float16_t)-0.0706787109f, (float16_t)-0.133666992f,  (float16_t)-0.232421875f,   (float16_t)0.228393555f,
    (float16_t)-0.241088867f,  (float16_t)-0.0262908936f, (float16_t)-0.293457031f,   (float16_t)0.534179688f,
    (float16_t)0.539550781f,   (float16_t)-0.0661621094f, (float16_t)-0.00399017334f, (float16_t)0.403320312f,
    (float16_t)-0.317871094f,  (float16_t)0.698242188f,   (float16_t)0.396484375f,    (float16_t)0.418212891f,
    (float16_t)0.436523438f,   (float16_t)0.492431641f,   (float16_t)0.521484375f,    (float16_t)-0.169555664f,
    (float16_t)-0.0894165039f, (float16_t)0.257080078f,   (float16_t)0.754394531f,    (float16_t)0.879394531f,
    (float16_t)0.106506348f,   (float16_t)-0.301025391f,  (float16_t)-0.0972290039f,  (float16_t)0.00104236603f,
    (float16_t)-1.28125f,      (float16_t)-0.818359375f,  (float16_t)-0.510742188f,   (float16_t)0.049041748f,
    (float16_t)0.0112609863f,  (float16_t)-0.666503906f,  (float16_t)0.215332031f,    (float16_t)-0.266357422f,
    (float16_t)-0.379394531f,  (float16_t)-0.491455078f,  (float16_t)-0.0502929688f,  (float16_t)0.207397461f,
    (float16_t)-0.82421875f,   (float16_t)-1.15429688f,   (float16_t)0.52734375f,     (float16_t)-1.23730469f,
    (float16_t)0.198852539f,   (float16_t)0.486572266f,   (float16_t)1.18164062f,     (float16_t)0.923828125f,
    (float16_t)-0.651855469f,  (float16_t)-0.502441406f,  (float16_t)0.257324219f,    (float16_t)-0.75390625f,
    (float16_t)-0.227783203f,  (float16_t)-0.0430908203f, (float16_t)0.496826172f,    (float16_t)0.575195312f,
    (float16_t)0.409423828f,   (float16_t)-0.510253906f,  (float16_t)0.14050293f,     (float16_t)-0.953125f,
    (float16_t)-0.298339844f,  (float16_t)0.455566406f,   (float16_t)0.509765625f,    (float16_t)1.24511719f,
    (float16_t)-0.949707031f,  (float16_t)-0.565917969f,  (float16_t)0.860839844f,    (float16_t)-1.375f,
    (float16_t)0.00124359131f, (float16_t)-0.0621032715f, (float16_t)-1.1015625f,     (float16_t)-0.930664062f,
    (float16_t)-0.709960938f,  (float16_t)-0.992675781f,  (float16_t)0.211303711f,    (float16_t)-1.24023438f,
    (float16_t)-0.22644043f,   (float16_t)0.135498047f,   (float16_t)0.159912109f,    (float16_t)0.396972656f,
    (float16_t)1.0078125f,     (float16_t)0.0768432617f,  (float16_t)0.298583984f,    (float16_t)0.0382080078f,
    (float16_t)-0.360107422f,  (float16_t)0.364501953f,   (float16_t)0.221801758f,    (float16_t)1.16601562f,
    (float16_t)-0.0462341309f, (float16_t)-0.67578125f,   (float16_t)0.262695312f,    (float16_t)-0.742675781f,
    (float16_t)0.333007812f,   (float16_t)0.658691406f,   (float16_t)0.587402344f,    (float16_t)0.661132812f,
    (float16_t)0.0813598633f,  (float16_t)0.771484375f,   (float16_t)-0.00601577759f, (float16_t)0.565429688f,
    (float16_t)0.174926758f,   (float16_t)0.524414062f,   (float16_t)1.30371094f,     (float16_t)1.03515625f,
    (float16_t)1.12402344f,    (float16_t)-0.201660156f,  (float16_t)-0.158203125f,   (float16_t)0.406982422f,
    (float16_t)-0.871582031f,  (float16_t)-0.506835938f,  (float16_t)-0.385009766f,   (float16_t)0.434082031f,
    (float16_t)-0.469970703f,  (float16_t)-0.778808594f,  (float16_t)0.035949707f,    (float16_t)-0.217773438f};
