/*
 * SPDX-FileCopyrightText: Copyright 2010-2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the License); you may
 * not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an AS IS BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Generated by conv_settings_flt.py using PyTorch version 2.13.0+cpu.
const float16_t conv_small_kernel_grouped_nhwc_f16_weights_data[64] = {
    (float16_t)0.0268859863f,    (float16_t)0.493652344f,   (float16_t)0.391357422f,  (float16_t)-0.0206756592f,
    (float16_t)-0.100891113f,    (float16_t)0.132324219f,   (float16_t)-0.204711914f, (float16_t)0.34375f,
    (float16_t)0.614257812f,     (float16_t)0.075012207f,   (float16_t)0.188354492f,  (float16_t)0.140991211f,
    (float16_t)0.485595703f,     (float16_t)-0.243164062f,  (float16_t)-0.224975586f, (float16_t)0.240600586f,
    (float16_t)0.170410156f,     (float16_t)0.734863281f,   (float16_t)-0.176635742f, (float16_t)0.345703125f,
    (float16_t)0.427001953f,     (float16_t)0.346923828f,   (float16_t)0.319091797f,  (float16_t)0.406494141f,
    (float16_t)-0.000313282013f, (float16_t)0.724121094f,   (float16_t)-0.166259766f, (float16_t)0.601074219f,
    (float16_t)0.600097656f,     (float16_t)0.586914062f,   (float16_t)0.109375f,     (float16_t)0.0310974121f,
    (float16_t)-0.270019531f,    (float16_t)0.623535156f,   (float16_t)-0.122192383f, (float16_t)-0.532714844f,
    (float16_t)0.663085938f,     (float16_t)0.00524139404f, (float16_t)0.12878418f,   (float16_t)-0.375f,
    (float16_t)0.0246734619f,    (float16_t)-0.146362305f,  (float16_t)-0.737304688f, (float16_t)0.336669922f,
    (float16_t)0.127807617f,     (float16_t)0.2265625f,     (float16_t)0.114868164f,  (float16_t)-0.4609375f,
    (float16_t)0.143676758f,     (float16_t)-0.362792969f,  (float16_t)0.0622253418f, (float16_t)0.35546875f,
    (float16_t)-0.0757446289f,   (float16_t)-0.052734375f,  (float16_t)-0.464355469f, (float16_t)-0.10168457f,
    (float16_t)-0.287841797f,    (float16_t)0.032409668f,   (float16_t)-0.641113281f, (float16_t)0.619628906f,
    (float16_t)0.256347656f,     (float16_t)-0.0326843262f, (float16_t)0.509277344f,  (float16_t)0.18762207f};
