// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int32_t conv_1_x_n_8_output_mult[10] = {1383688192,
                                              1381677824,
                                              1383904000,
                                              1383905664,
                                              1384835072,
                                              1380558080,
                                              1383598592,
                                              1382050816,
                                              1384758144,
                                              1385245312};
