// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t gather_nd_batch_dims_s8_input_tensor[16] =
    {97, -84, 23, -52, -55, 125, -82, -67, 19, -100, 22, -81, 8, -87, -65, 87};
