// Generated by generate_comparison_data.py
#pragma once
#include <stdint.h>

const int16_t comparison_greater_equal_broadcast_w_s16_input_1_input_tensor[24] = {
    -2880, -2520, -2160, -1800, -1440, -1080, -720, -360, 

    0, 360, 720, 1080, 1440, 1800, 2160, 2520, 

    2880, 3240, 3600, 3960, 4320, 4680, 5040, 5400
};
