// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t fc_conv_int8_non_4_multiple_output[33] = {-10, 114, -37, -25, 14,  17,  37,  -3,   -11, 26,  -7,
                                                       61,  84,  33,  58,  -19, -40, -43, -128, 56,  33,  23,
                                                       -8,  -24, 55,  -11, -78, 3,   -26, -46,  33,  -83, 17};

const int8_t *const fc_conv_int8_non_4_multiple_output_ref = fc_conv_int8_non_4_multiple_output;
