// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t add_ident_neg_offset_s8_lhs_input_tensor[24] = {102, -28, 37,  28, 94,  -56, 124, -19, 117, 116, 87, -118,
                                                             63,  -39, -89, 79, -30, 75,  39,  86,  31,  42,  87, 83};
