// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t add_ident_neg_offset_s8_output[24] = {16, -20, -9, -34, 24, 12, 26, 33, 125, 2,  105, -58,
                                                   87, -37, -8, 0,   27, -8, 1,  52, 75,  10, -14, 11};

const int8_t *const add_ident_neg_offset_s8_output_ref = add_ident_neg_offset_s8_output;
