// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t add_ident_neg_offset_s8_rhs_input_tensor[24] = {
    -69, -8, -52, -91, -45, 81, -72, 86, 127, -109, 118, 8, 107, -29, 76, -76, 84, -87, -34, 17, 117, -20, -111, -59};
