// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once

#define SQRT_LONG_ROW_S8_INPUT_MIN 0
#define SQRT_LONG_ROW_S8_INPUT_MAX 127
#define SQRT_LONG_ROW_S8_BATCH_SIZE 1
#define SQRT_LONG_ROW_S8_HEIGHT_1 1
#define SQRT_LONG_ROW_S8_WIDTH_1 64
#define SQRT_LONG_ROW_S8_CHANNEL_1 1
#define SQRT_LONG_ROW_S8_IN_DIM                                                                                        \
    {                                                                                                                  \
        1,                                                                                                             \
        1,                                                                                                             \
        64,                                                                                                            \
        1,                                                                                                             \
    }
#define SQRT_LONG_ROW_S8_OUTPUT_LEN 64
#define SQRT_LONG_ROW_S8_INPUT_SCALE 0.4980311691761017
#define SQRT_LONG_ROW_S8_INPUT_ZERO_POINT -128
#define SQRT_LONG_ROW_S8_OUTPUT_SCALE 0.04419347643852234
#define SQRT_LONG_ROW_S8_OUTPUT_ZERO_POINT -128
