// Generated by generate_test_data.py using tensorflow version 2.21.0 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.21.0 and revision v2.21.0-rc1-5-ga481b10260d.
#pragma once
#include <stdint.h>

const int8_t sqrt_long_row_s8_output[64] = {
    119, 118, 110, 92, 115, 111, 92,  93,  71,  72,  58,  75,  75,  72,  96, 94,  85,  107, 65,  121, 68, 115,
    125, 76,  106, 93, 125, 123, 91,  125, 73,  100, 115, 110, 102, 88,  64, 117, 91,  66,  57,  92,  85, 80,
    75,  55,  124, 81, 87,  121, 116, 103, 117, 116, 81,  90,  113, 109, 78, 112, 105, 69,  120, 105};
