// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once

#define WHERE_3D_SPARSE_S8_FORCE_NO_QUANTIZE true
#define WHERE_3D_SPARSE_S8_SHAPE                                                                                       \
    {                                                                                                                  \
        2, 2, 2,                                                                                                       \
    }
#define WHERE_3D_SPARSE_S8_CONDITION_VALUES                                                                            \
    {                                                                                                                  \
        0, 5, 0, 0, -1, 0, 2, 0,                                                                                       \
    }
#define WHERE_3D_SPARSE_S8_RANK 3
#define WHERE_3D_SPARSE_S8_SIZE 8
#define WHERE_3D_SPARSE_S8_COND_SIZE 8
