// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.13.2).
// Interpreter from tflite_micro runtime version 0.dev20251103221221-gv1.3.0-45-gac157ac1-dirty.
#pragma once
#include <stdint.h>

const int16_t squared_difference_broadcast_n_s16_lhs_input_tensor[24] = {
    -21528, -19715, -2949,  12252, -18742, 29066, -6828, -23097, 22560, 32378,  15307, -23627,
    860,    -16955, -27969, 23982, -2031,  -6826, 31729, -367,   28703, -21167, 28973, 8492};
