// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.13.2).
// Interpreter from tflite_micro runtime version 0.dev20251103221221-gv1.3.0-45-gac157ac1-dirty.
#pragma once
#include <stdint.h>

const int16_t squared_difference_broadcast_n_s16_output[48] = {
    11244, 6131,  782,   2465, 100,   32767, 1195,  32767, 1064,  21366, 1578,  288,  0,   32767, 2799,  1932,
    23034, 10792, 32767, 234,  32767, 10745, 32767, 18475, 32767, 32767, 11,    327,  644, 32767, 4135,  32767,
    872,   32767, 32767, 3507, 20983, 32767, 17114, 32767, 12125, 2756,  32767, 1510, 136, 32767, 32767, 24};

const int16_t *const squared_difference_broadcast_n_s16_output_ref = squared_difference_broadcast_n_s16_output;
