// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.13.2).
// Interpreter from tflite_micro runtime version 0.dev20251103221221-gv1.3.0-45-gac157ac1-dirty.
#pragma once
#include <stdint.h>

const int16_t squared_difference_broadcast_n_s16_rhs_input_tensor[48] = {
    -2695, -5808, 2018,   3433,   -20521, -15100, -688,  26838, 28354, 6417,  8253,   -26641,
    821,   31490, -18573, 16177,  24926,  11625,  -7598, -3080, -4838, -2755, -8688,  -15649,
    11556, 24889, -3528,  9042,   -23249, -17894, 4591,  12189, 27805, -7056, -18687, -13108,
    26588, 16376, -4733,  -23601, -21587, -16150, -3099, -7268, 30773, 13511, -26873, 7629};
