// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_5_output_ref[32] = {31, 30, 57, 52, 53, 1,   44,  -74, -6,  7, -47, -26, 45,  -11, -4, 27,
                                      9,  20, -5, 19, 6,  -20, -54, 83,  -78, 0, -6,  -87, -45, 71,  45, -16};
