// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once

#define REDUCE_MAX_AXIS_HW_S8_IN_DIM                                                                                   \
    {                                                                                                                  \
        5, 10, 13, 4,                                                                                                  \
    }
#define REDUCE_MAX_AXIS_HW_S8_AXIS                                                                                     \
    {                                                                                                                  \
        1, 2,                                                                                                          \
    }
#define REDUCE_MAX_AXIS_HW_S8_KEEP_DIMS true
#define REDUCE_MAX_AXIS_HW_S8_OUT_DIM                                                                                  \
    {                                                                                                                  \
        5, 1, 1, 4,                                                                                                    \
    }
#define REDUCE_MAX_AXIS_HW_S8_AXIS_DIM                                                                                 \
    {                                                                                                                  \
        0, 1, 1, 0,                                                                                                    \
    }
#define REDUCE_MAX_AXIS_HW_S8_AXIS_MASK 6
#define REDUCE_MAX_AXIS_HW_S8_INPUT_SIZE 2600
#define REDUCE_MAX_AXIS_HW_S8_OUTPUT_SIZE 20
#define REDUCE_MAX_AXIS_HW_S8_INPUT_OFFSET 128
#define REDUCE_MAX_AXIS_HW_S8_OUTPUT_OFFSET -128
#define REDUCE_MAX_AXIS_HW_S8_OUTPUT_MULTIPLIER 1073741824
#define REDUCE_MAX_AXIS_HW_S8_OUTPUT_SHIFT 1
#define REDUCE_MAX_AXIS_HW_S8_REDUCTION_SIZE 130
