/*
 * SPDX-FileCopyrightText: 2025 Ambiq
 *
 * SPDX-License-Identifier: LicenseRef-Ambiq-Apollo-SDK
 *
 * Licensed under the Ambiq Apollo SDK License.
 * See LICENSE (root) or LICENSES/LicenseRef-Ambiq-Apollo-SDK.txt for the full text.
 */

#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "../test_arm_reduce_max_s8.c"
#include "unity.h"

#ifdef USING_FVP_CORSTONE_300
extern void uart_init(void);
#endif

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void setUp(void)
{ /* This is run before EACH TEST */
#ifdef USING_FVP_CORSTONE_300
    uart_init();
#endif
}

/* This function is called from the autogenerated file.
 * The name must be exactly like this
 */
void tearDown(void) {}

void test_reduce_max_axis_n_arm_reduce_max_s8(void) { reduce_max_axis_n_arm_reduce_max_s8(); }
void test_reduce_max_axis_h_arm_reduce_max_s8(void) { reduce_max_axis_h_arm_reduce_max_s8(); }
void test_reduce_max_axis_w_arm_reduce_max_s8(void) { reduce_max_axis_w_arm_reduce_max_s8(); }
void test_reduce_max_axis_c_arm_reduce_max_s8(void) { reduce_max_axis_c_arm_reduce_max_s8(); }
void test_reduce_max_axis_hw_arm_reduce_max_s8(void) { reduce_max_axis_hw_arm_reduce_max_s8(); }
void test_reduce_max_axis_nhwc_arm_reduce_max_s8(void) { reduce_max_axis_nhwc_arm_reduce_max_s8(); }
void test_reduce_max_axis_hwc_arm_reduce_max_s8(void) { reduce_max_axis_hwc_arm_reduce_max_s8(); }
void test_reduce_max_axis_wc_arm_reduce_max_s8(void) { reduce_max_axis_wc_arm_reduce_max_s8(); }
