// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t reduce_max_axis_hw_s16_output[20] = {30952, 31999, 32724, 32302, 32759, 32479, 32492,
                                                   32199, 31634, 30235, 32668, 32341, 32456, 32703,
                                                   31544, 32595, 32671, 31911, 32030, 31627};
