// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_2_output_ref[72] = {
    85, -37, 19,  -30, 34, 5,   110, 26,  42,  -5,  80,  -9, 25,  -41, 5,   -32, 64, -39, 71,  42, 12,  5,   40, -9,
    38, -48, -29, 4,   43, -64, 0,   57,  24,  -20, -44, 60, 18,  -14, 34,  48,  21, -63, 49,  58, -77, 44,  27, 45,
    2,  -73, -35, 55,  -2, -97, -78, 116, -24, -48, -80, 72, -30, -17, -34, 59,  53, -98, -29, 41, 14,  -34, 13, 51};
