// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_2_weights[72] = {-52, -102, 51,  -127, -85, 22,   -122, 119,  42,  -10, 123,  126, 58,  -86,  -20,
                                   -21, -8,   81,  101,  -21, -119, 64,   101,  -89, 91,  -47,  8,   20,  -125, -71,
                                   12,  -4,   80,  127,  31,  -49,  -82,  -115, 85,  -66, -3,   -89, -91, 84,   107,
                                   -77, -127, 8,   9,    112, 48,   88,   -77,  54,  65,  94,   0,   -25, -1,   122,
                                   -60, 76,   127, -90,  -1,  -10,  -85,  78,   52,  -48, -120, 4};
