// Generated by generate_test_data.py using flatc version 24.12.23
// Interpreter from tflite_micro runtime version 0.dev20250207030249-gef64591.
#pragma once
#include <stdint.h>

const int32_t fc_conv_int8_dilated_input_bias[96] = {
    -98, 63,  25,  51,   -23,  91,   118, -111, 57,  -1,   -22, 99,  -35,  38,  -50, -76, 30,  -98, 120, 39,
    75,  -71, -42, 80,   122,  19,   -45, 0,    -56, -117, 37,  -15, 25,   -35, -65, -65, -23, 102, 61,  -105,
    69,  37,  20,  -118, 126,  17,   -51, 121,  16,  119,  -36, 19,  60,   93,  103, -28, -91, 103, -38, -107,
    -66, 69,  -15, 112,  -108, -52,  -48, 61,   -93, 109,  -5,  8,   119,  95,  -94, 30,  44,  64,  -71, 12,
    15,  85,  -43, -26,  -49,  -121, -79, 6,    87,  87,   25,  -48, -118, 63,  23,  -50};

const int32_t *const fc_conv_int8_dilated_biases = fc_conv_int8_dilated_input_bias;
