// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t fc_conv_int8_dilated_output[96] = {
    -84, -52,  32,  54,  -59, -21, -10, 5,   64,  -27, -19, 72,  38,  -2,  59,   -81, 36,  -20, -34, -68,
    5,   77,   79,  98,  -69, 9,   116, -75, -15, -42, 56,  9,   36,  -32, 56,   72,  -26, -35, -62, 30,
    -39, -78,  -70, -36, -69, -7,  28,  59,  -30, -42, -18, 73,  -17, 14,  7,    29,  -31, -87, -33, -119,
    36,  48,   77,  -13, 12,  49,  83,  5,   -43, -77, -25, -3,  -8,  -66, 8,    27,  -2,  -24, 47,  2,
    -69, -109, -15, 63,  -83, 66,  -39, -17, -78, 17,  3,   -36, -34, 30,  -128, -3};

const int8_t *const fc_conv_int8_dilated_output_ref = fc_conv_int8_dilated_output;
