// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t fc_conv_int8_dilated_output[96] = {
    18,  -22, 1,    -31, -74, -52, 30,  -64, -107, -21, 34,  26, -15, -12, -57, -14, 42,  -64, -2,  13,
    -60, -7,  -102, 46,  3,   39,  16,  24,  -44,  -15, -18, 54, -34, -90, -99, -14, -67, 64,  7,   -6,
    -96, 39,  18,   -8,  7,   50,  -87, -46, -84,  30,  -47, 11, -92, -42, -40, 32,  6,   71,  -55, -39,
    78,  -59, 27,   -17, -32, -41, -32, -43, -55,  85,  -36, 80, 8,   -86, 19,  -21, -9,  -98, -40, -42,
    100, -14, 3,    72,  -64, 54,  0,   0,   -51,  -57, -28, -4, -34, -57, 7,   78};

const int8_t *const fc_conv_int8_dilated_output_ref = fc_conv_int8_dilated_output;
