// Generated by test_settings.py using tensorflow version 2.17.1 (Keras version 3.12.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t int16xint8_group_depthwise_3x3_pad_weights[72] = {
    -22,  -24,  -37, -34,  77,   52,  100, -127, -31, 48,   28,  -127, 109,  -75,  1,   -96, -96,  78,
    21,   -118, 18,  112,  62,   -45, 79,  -41,  127, 7,    -30, -9,   10,   -127, 39,  -36, 79,   -52,
    36,   -77,  102, 0,    -85,  117, 47,  126,  127, -127, -90, -1,   -117, -43,  -84, 42,  -111, 15,
    -122, -31,  20,  -103, -127, -71, 94,  -88,  44,  124,  84,  -127, 69,   90,   18,  -64, 35,   -31};
