// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_4_weights[54] = {4,   -54, 123,  82,  -102, -49, 30, 114, 93,  113, 118, -119, 35,  47,
                                   -52, -82, 93,   127, 121,  -70, 69, -24, 94,  54,  127, -127, 3,   -32,
                                   19,  65,  -104, 83,  -72,  41,  85, 53,  -59, -98, 100, -100, 127, -114,
                                   18,  62,  117,  71,  92,   53,  95, -43, 92,  -99, 40,  -127};
