// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t hard_swish_basic_output[24] = {34,  -92, 25, 90, -115, -75, 126, -108, -57, 71, 53, -106,
                                            103, -75, 15, -3, -88,  30,  -40, -25,  80,  60, 49, 55};
