// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t prelu_alpha_hw_broadcast_s8_alpha_input_tensor[20] = {29, -99, -46, -101, -27, -19, 16,  12,   -108, -30,
                                                                   17, 51,  48,  -67,  -27, 47,  -73, -112, -2,   -2};
