// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t sub_broadcast_h_s8_output[24] = {32, 15, 9, 25, 57, 60, 32, 15, 7, 25, 57, 60,
                                              32, 15, 9, 25, 57, 60, 32, 15, 9, 25, 57, 60};

const int8_t *const sub_broadcast_h_s8_output_ref = sub_broadcast_h_s8_output;
