// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.0).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t resize_nn_align_corners_s8_input_tensor[20] = {-25, -96, 47, 113, -117, -14, -115, -113, -89, -39,
                                                            22,  99,  92, -46, 61,   46,  -76,  64,   -10, -66};
