// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mean_axis_hw_s8_output[20] = {108, 125, 96,  115, 95, 102, 120, 114, 107, 95,
                                           107, 97,  113, 97,  91, 112, 77,  116, 106, 108};
