// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t reduce_max_axis_c_s16_input_tensor[16] = {-28623,
                                                        -29564,
                                                        24932,
                                                        -26145,
                                                        -8124,
                                                        23360,
                                                        -29628,
                                                        19894,
                                                        -5297,
                                                        32042,
                                                        18265,
                                                        -5984,
                                                        3434,
                                                        21727,
                                                        -20115,
                                                        -20362};
