// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_3x2_dilation_output_ref[18] =
    {102, 6, -61, 25, -18, -23, -10, 50, 0, 104, -18, 66, -59, 14, -61, 107, -61, 97};
