// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t conv_3x2_dilation_weights[36] = {-91, -30, -51,  -23,  -22, 43,  -106, 10, -20, -73, -118, 127,
                                              -16, 32,  -115, 127,  30,  0,   -15,  11, -25, 127, 24,   11,
                                              94,  -5,  60,   -110, 99,  -45, -106, 0,  -6,  -80, 8,    -26};
