// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t add_broadcast_h_s8_output[24] = {-58, 4, -32, 57, 16, 68, 4,  4,   -29, 4,  4, 4,
                                              4,   4, 4,   4,  62, 15, 13, -42, 25,  49, 4, 4};

const int8_t *const add_broadcast_h_s8_output_ref = add_broadcast_h_s8_output;
