// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t add_broadcast_h_s8_rhs_transposed_tensor[24] = {-120, 103, 0, 23,  -69, 124, 0,  0,  0,   0, -63, 0,
                                                             0,    0,   0, 112, 0,   22,  17, 88, -89, 0, 40,  0};
