// Generated by test_settings.py using tensorflow version 2.19.0 (Keras version 3.10.0).
// Interpreter from tensorflow version 2.19.0 and revision v2.19.0-rc0-6-ge36baa30292.
#pragma once
#include <stdint.h>

const int8_t maxpooling_2_input[60] = {84, 38,  66,   22,   108, -104, -4,  14,   105,  -92, -40, -94, 1,    84,  23,
                                       59, 84,  -50,  52,   107, -104, -43, -69,  -102, -83, 42,  -99, -93,  12,  -83,
                                       90, -76, 47,   23,   -16, -89,  78,  -104, -36,  101, 25,  -40, -106, -35, 122,
                                       -9, 6,   -105, -122, -42, -53,  -53, -57,  -34,  -73, -4,  -20, 1,    83,  93};
