// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t mul_broadcast_h_s8_output[24] = {-61, -61, -61, -61, -59, -61, -61, -61, -61, -69, -62, -62,
                                              -62, -62, -62, -62, -61, -61, -61, -61, -61, -61, -61, -61};

const int8_t *const mul_broadcast_h_s8_output_ref = mul_broadcast_h_s8_output;
