// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.3).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int32_t large_k9_1d_valid_28ch_200h_bias[28] = {
    -19562, 32381, 31746, -20909, 6005,  17843, -11916, 32439, -16281, -17069, 28305,  -956, 20321, -30086,
    -37689, 31146, 7656,  -14942, 28912, 11654, 13518,  40079, -16232, 19334,  -13372, 1029, -4374, 23096};

const int32_t *const large_k9_1d_valid_28ch_200h_biases = large_k9_1d_valid_28ch_200h_bias;
