// Generated by generate_comparison_data.py
#pragma once
#include <stdint.h>

const int8_t comparison_equal_ident_s8_input_1_input_tensor[24] = {
    -30, -27, -24, -21, -18, -15, -12, -9, 

    -6, -3, 0, 3, 6, 9, 12, 15, 

    18, 21, 24, 27, 30, 33, 36, 39
};
