// Generated by generate_comparison_data.py
#pragma once
#include <stdbool.h>

const bool comparison_equal_ident_s8_output[24] = {
    false, true, true, true, true, true, true, false, 

    true, true, true, true, true, true, false, true, 

    true, true, true, true, true, false, true, true
};

const bool *const comparison_equal_ident_s8_output_ref = comparison_equal_ident_s8_output;
