# SPDX-FileCopyrightText: 2026 Ambiq
# SPDX-License-Identifier: Apache-2.0
"""Regenerate goldens: pip install ai-edge-litert==2.1.6 numpy==2.5.1.

The checked-in single-op FlatBuffers are the complete reference inputs. No AOT
checkout or CORE executable is used. Parameters follow the existing
RefactoredTestGen/Lib/op_hard_swish.py Q31-to-Q15 derivation; expected bytes come
only from LiteRT's BUILTIN_REF interpreter. Models contain no learned weights.
"""
import hashlib
import importlib.metadata
import json
import math
from pathlib import Path

import numpy as np
from ai_edge_litert.interpreter import Interpreter, OpResolverType


def multiplier(scale):
    fraction, exponent = math.frexp(scale)
    q31 = math.floor(fraction * 2**31 + 0.5)
    if q31 == 2**31:
        q31 //= 2
        exponent += 1
    return min((q31 + 2**15) // 2**16, 32767), exponent


def main():
    version = importlib.metadata.version("ai-edge-litert")
    if version != "2.1.6" or np.__version__ != "2.5.1":
        raise RuntimeError("Use ai-edge-litert==2.1.6 and numpy==2.5.1 for these goldens")
    root = Path(__file__).parent
    rows, metadata = [], []
    for path in sorted((root / "models").glob("case*.tflite")):
        model = path.read_bytes()
        ref = Interpreter(model_content=model, experimental_op_resolver_type=OpResolverType.BUILTIN_REF)
        ref.allocate_tensors()
        inp, out = ref.get_input_details()[0], ref.get_output_details()[0]
        values = np.arange(-128, 128, dtype=np.int8).reshape(inp["shape"])
        ref.set_tensor(inp["index"], values)
        ref.invoke()
        expected = ref.get_tensor(out["index"]).reshape(-1)
        si, zi = inp["quantization"]
        so, zo = out["quantization"]
        ofp, oe = multiplier(si / 128 / so)
        rfp, re = multiplier((si / 128) / (3 / 32768))
        assert oe <= 0 and expected.size == 256
        params = [zi, zo, ofp, oe, rfp, re]
        rows.append("    {" + ", ".join(map(str, params)) + ", {\n" +
                    "\n".join("        " + ", ".join(map(str, expected[i:i+16])) + "," for i in range(0, 256, 16)) +
                    "\n    }},")
        metadata.append(dict(model=path.name, sha256=hashlib.sha256(model).hexdigest(),
                             input_quant=[si, zi], output_quant=[so, zo], params=params,
                             output_sha256=hashlib.sha256(expected.tobytes()).hexdigest()))
    assert len(rows) == 8 and {m["params"][-1] for m in metadata} >= {-1, 0, 1, 4}
    (root / "goldens.h").write_text(
        "// SPDX-FileCopyrightText: 2026 Ambiq\n// SPDX-License-Identifier: Apache-2.0\n"
        "// Generated by generate.py using LiteRT 2.1.6 BUILTIN_REF; input is -128..127.\n"
        "#ifndef HARD_SWISH_COMPAT_GOLDENS_H\n#define HARD_SWISH_COMPAT_GOLDENS_H\n#include <stdint.h>\n"
        "typedef struct {\n    int32_t zi, zo, ofp, oe, rfp, re;\n    int8_t expected[256];\n} hs_litert_case;\n"
        "static const hs_litert_case hs_litert_cases[] = {\n" + "\n".join(rows) + "\n};\n#endif\n")
    (root / "models.json").write_text(json.dumps(dict(litert=version, numpy=np.__version__,
        resolver="BUILTIN_REF", input="int8 ramp -128..127, shape [1,256]", cases=metadata), indent=2) + "\n")


if __name__ == "__main__":
    main()
