// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.11.1).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t hard_swish_plateau_edges_input_tensor[64] = {
    -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128, -128,
    127,  127,  127,  127,  127,  127,  127,  127,  127,  127,  127,  127,  127,  127,  127,  127,
    -4,   2,    -3,   3,    3,    -3,   2,    2,    3,    -2,   -2,   4,    -3,   0,    -2,   2,
    -11,  10,   14,   -1,   8,    -8,   -16,  1,    7,    11,   6,    -12,  -3,   -2,   10,   15};
