// Generated by generate_test_data.py using tensorflow version 2.17.1 (Keras version 3.12.2).
// Interpreter from tensorflow version 2.17.1 and revision v2.17.0-18-g3c92ac03cab.
#pragma once
#include <stdint.h>

const int8_t reverse_sequence_full_and_single_s8_input_tensor[12] = {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};
