// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int16_t mean_axis_h_s16_input_tensor[16] =
    {-8769, 2497, -18139, 2138, 29789, 12946, -32435, 28111, 22223, 861, -27937, -19157, 12415, -10351, 808, -24011};
