// Generated by generate_test_data.py using tensorflow version 2.17.0 (Keras version 3.8.0).
// Interpreter from tensorflow version 2.17.0 and revision v2.17.0-rc1-2-gad6d8cc177d.
#pragma once
#include <stdint.h>

const int8_t reduce_max_axis_w_s8_input_tensor[16] =
    {-40, 127, -38, 73, 93, -62, 74, -115, 0, -71, -48, -95, -92, -7, -110, -50};
