name: CI/CD Pipeline

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  legacy-tests:
    uses: ./.github/workflows/legacy-tester.yml

  helia-core-tester:
    uses: ./.github/workflows/helia-core-tester.yml
