name: Tests Entry Point

on:
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  ci-run:
    uses: ./.github/workflows/ci.yml
    with:
      trigger-sha: ${{ github.event.pull_request.head.sha }}
