// Generated by generate_sqrt_s16_test_data.py
// Deterministic integer-sqrt reference for arm_sqrt_s16.
#pragma once
#include <stdint.h>

const int16_t sqrt_long_row_s16_output[32] = {
  0, 0, 0, 0, 0, 0, 1810, 2217,
  2560, 3135, 4047, 5430, 6526, 7463, 8295, 9050,
  9748, 10398, 11010, 11590, 16291, 19912, 22968, 25663,
  26910, 28101, 29244, 30344, 31405, 31923, 32432, 32733
};
